var e=ctx.roles.encounter,i=ctx.input,ROUND='dnd2024.encounter.round',TURN='dnd2024.encounter.turn',BUDGET='dnd2024.combat.turn-budget',ACTIVEROUND='encounter.active-round',ACTIVETURN='encounter.active-turn';
function closed(v,k){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length!==k.length)return false;for(var n=0;n<k.length;n++)if(!Object.prototype.hasOwnProperty.call(v,k[n]))return false;return true;}
function id(v){return typeof v==='string'&&v.length>0&&v.length<=200&&v===v.trim();}
function integer(v,min,max){return typeof v==='number'&&isFinite(v)&&Math.floor(v)===v&&v>=min&&v<=max;}
function parse(raw,name){try{return typeof raw==='string'?JSON.parse(raw):raw;}catch(error){throw new Error(name+' is corrupt.');}}
function ref(v){return closed(v,['entityId'])&&id(v.entityId);}
function related(kind){var all=e.related||[],values=[];for(var n=0;n<all.length;n++)if(all[n].kind===kind)values.push(all[n]);return values;}
if(!e||!closed(i,[]))throw new Error('Ending encounter turns requires exactly an empty object input.');var rounds=related(ACTIVEROUND),turns=related(ACTIVETURN);if(rounds.length!==1||turns.length!==1)throw new Error('Encounter active lifecycle links are missing or ambiguous.');var roundNode=rounds[0],turnNode=turns[0],round=parse(roundNode.components&&roundNode.components[ROUND],'Active round'),turn=parse(turnNode.components&&turnNode.components[TURN],'Active turn'),budget=parse(turnNode.components&&turnNode.components[BUDGET],'Active turn budget');if(!closed(round,['encounter','number','status'])||!ref(round.encounter)||round.encounter.entityId!==e.id||!integer(round.number,1,9007199254740991)||round.status!=='active'||!closed(turn,['encounter','round','participant','ordinal','status'])||!ref(turn.encounter)||!ref(turn.round)||!ref(turn.participant)||turn.encounter.entityId!==e.id||turn.round.entityId!==roundNode.id||!integer(turn.ordinal,0,99)||turn.status!=='active'||!closed(budget,['turn','remaining','movementSpent','interactionsUsed'])||!ref(budget.turn)||budget.turn.entityId!==turnNode.id)throw new Error('Encounter active lifecycle state is invalid.');
return {narration:e.name+' ends.',data:{test:'encounter-turn-end',status:'ended',round:round.number,roundId:roundNode.id,turnIndex:turn.ordinal,turnId:turnNode.id,finalParticipationId:turn.participant.entityId},effects:[{type:'component.set',entityId:turnNode.id,definitionId:TURN,data:JSON.stringify({encounter:turn.encounter,round:turn.round,participant:turn.participant,ordinal:turn.ordinal,status:'complete'})},{type:'component.set',entityId:roundNode.id,definitionId:ROUND,data:JSON.stringify({encounter:round.encounter,number:round.number,status:'complete'})},{type:'relationship.remove',entityId:e.id,toEntityId:turnNode.id,kind:ACTIVETURN},{type:'relationship.remove',entityId:e.id,toEntityId:roundNode.id,kind:ACTIVEROUND}],events:[],notifications:[]};
