var ordered=['str','dex','con','int','wis','cha'],ABILITY_REFS={str:'dnd2024.vocabulary.ability.strength',dex:'dnd2024.vocabulary.ability.dexterity',con:'dnd2024.vocabulary.ability.constitution',int:'dnd2024.vocabulary.ability.intelligence',wis:'dnd2024.vocabulary.ability.wisdom',cha:'dnd2024.vocabulary.ability.charisma'},EP='dnd2024.rest-episode',LINK='rest.world',GRANTS='dnd2024.character-feature-grants',SID='source.dnd2024.srd-5.2.1',ALERT='content.dnd2024.feature.alert.v1',ALERTLOC='Feats > Origin Feats > Alert, PDF page 87',SHORTLOC='Rules Glossary > Short Rest, PDF page 187',LONGLOC='Rules Glossary > Long Rest, PDF page 185',RESTMAX=1000000000;
function closed(value,keys){if(value===null||Array.isArray(value)||typeof value!=='object')return false;var actual=Object.keys(value).sort(),expected=keys.slice().sort();if(actual.length!==expected.length)return false;for(var index=0;index<expected.length;index++)if(actual[index]!==expected[index])return false;return true;}
function integer(value,min,max){return typeof value==='number'&&isFinite(value)&&Math.floor(value)===value&&value>=min&&value<=max;}
function text(value,max){return typeof value==='string'&&value.length>0&&value===value.trim()&&Array.from(value).length<=max;}
function parse(raw,label){if(typeof raw!=='string')throw new Error(label+' is corrupt.');try{return JSON.parse(raw);}catch(error){throw new Error(label+' is corrupt.');}}
function source(value,locator){return closed(value,['sourceId','locator'])&&value.sourceId===SID&&value.locator===locator;}
function boundedId(value){return text(value,200)&&Array.from(value).length>=20&&/^[a-z0-9.-]+$/.test(value);}
function validGrantSource(value){return closed(value,['sourceId','locator'])&&value.sourceId===SID&&text(value.locator,200)&&Array.from(value.locator).length>=4;}
function validGrant(value){if(!value||!boundedId(value.definitionId)||!boundedId(value.grantedByDefinitionId)||!validGrantSource(value.sourceRef))return false;if(value.grantKind==='origin-feat')return closed(value,['definitionId','grantedByDefinitionId','grantKind','configurationKey','sourceRef'])&&text(value.configurationKey,80)&&/^[a-z0-9-]+$/.test(value.configurationKey);if(value.grantKind==='class-feature')return closed(value,['definitionId','grantedByDefinitionId','grantKind','classLevel','sourceRef'])&&integer(value.classLevel,1,20);return false;}
function grantIdentity(value){return value.grantKind+'\n'+value.definitionId+'\n'+value.grantedByDefinitionId+'\n'+(value.configurationKey||value.classLevel)+'\n'+value.sourceRef.sourceId+'\n'+value.sourceRef.locator;}
function validAlertGrant(value){return value.definitionId===ALERT&&value.grantKind==='origin-feat'&&value.configurationKey==='default';}
function grantsState(value){if(!closed(value,['grants'])||!Array.isArray(value.grants)||value.grants.length<1||value.grants.length>64)return {valid:false,alert:false};var seen={},alertCount=0;for(var grantIndex=0;grantIndex<value.grants.length;grantIndex++){var grant=value.grants[grantIndex];if(!validGrant(grant))return {valid:false,alert:false};var identity=grantIdentity(grant);if(seen[identity])return {valid:false,alert:false};seen[identity]=true;if(grant.definitionId===ALERT){if(!validAlertGrant(grant))return {valid:false,alert:false};alertCount++;}}return {valid:alertCount<=1,alert:alertCount===1};}
function validEpisode(value){if(!value||value.policyEntityId!=='content.dnd2024.rest-policy.standard.v1'||!text(value.worldId,200)||!integer(value.startedAtMinute,0,RESTMAX)||!integer(value.observedAtMinute,value.startedAtMinute,RESTMAX)||!integer(value.observedClockRevision,0,2147483647)||(value.status!=='active'&&value.status!=='ready'))return false;var elapsed=value.observedAtMinute-value.startedAtMinute;if(value.kind==='short'){if(!closed(value,['policyEntityId','kind','worldId','startedAtMinute','observedAtMinute','observedClockRevision','requiredMinutes','lightActivityMinutes','status','sourceRef'])||value.requiredMinutes!==60||!integer(value.lightActivityMinutes,0,RESTMAX)||value.lightActivityMinutes!==elapsed||!source(value.sourceRef,SHORTLOC))return false;return (value.status==='ready')===(value.lightActivityMinutes>=value.requiredMinutes);}if(value.kind==='long'){if(!closed(value,['policyEntityId','kind','worldId','startedAtMinute','observedAtMinute','observedClockRevision','requiredMinutes','sleepMinutes','lightActivityMinutes','interruptionCount','status','sourceRef'])||!integer(value.sleepMinutes,0,RESTMAX)||!integer(value.lightActivityMinutes,0,120)||!integer(value.interruptionCount,0,16666658)||value.requiredMinutes!==480+60*value.interruptionCount||value.requiredMinutes>RESTMAX||value.sleepMinutes+value.lightActivityMinutes!==elapsed||!source(value.sourceRef,LONGLOC))return false;var ready=elapsed>=value.requiredMinutes&&value.sleepMinutes>=360&&value.lightActivityMinutes<=120;return (value.status==='ready')===ready;}return false;}
function edge(value){return closed(value,['data','fromEntityId','kind','toEntityId'])&&typeof value.data==='string'&&typeof value.fromEntityId==='string'&&typeof value.kind==='string'&&typeof value.toEntityId==='string';}
function derivedLevel(subject){var children=ctx.children&&ctx.children.level;if(!Array.isArray(children)||children.length!==1||!children[0].roleEntityIds||children[0].roleEntityIds.subject!==subject.id)throw new Error('Exactly one matching character-level result is required.');var value=parse(children[0].output&&children[0].output.data,'Character-level result');if(!closed(value,['membershipCount','present','problem','proficiencyBonus','subjectId','test','totalLevel','valid'])||value.test!=='character-level-read'||value.subjectId!==subject.id)return null;return value;}
var subject=ctx.roles.subject,input=ctx.input;if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Initiative input must be an object.');var keys=Object.keys(input).sort();
if(!subject||!subject.components||typeof subject.components['dnd2024.creature.ability-scores']!=='string'||!Array.isArray(subject.relationships))throw new Error('Initiative requires subject ability scores and relationships.');
if(keys.length>2)throw new Error('Initiative input must contain only optional rollCircumstances and useAlertInitiativeProficiency.');for(var inputKeyIndex=0;inputKeyIndex<keys.length;inputKeyIndex++)if(keys[inputKeyIndex]!=='rollCircumstances'&&keys[inputKeyIndex]!=='useAlertInitiativeProficiency')throw new Error('Initiative input must contain only optional rollCircumstances and useAlertInitiativeProficiency.');
var useAlert=Object.prototype.hasOwnProperty.call(input,'useAlertInitiativeProficiency')?input.useAlertInitiativeProficiency:false;if(typeof useAlert!=='boolean')throw new Error('useAlertInitiativeProficiency must be Boolean when supplied.');
var state;try{state=JSON.parse(subject.components['dnd2024.creature.ability-scores']);}catch(error){throw new Error('Subject ability scores are corrupt.');}if(!closed(state,['scores'])||!closed(state.scores,ordered.map(function(key){return ABILITY_REFS[key];})))throw new Error('Subject ability scores are invalid.');for(var abilityIndex=0;abilityIndex<ordered.length;abilityIndex++)if(!integer(state.scores[ABILITY_REFS[ordered[abilityIndex]]],1,30))throw new Error('Subject ability scores are invalid.');
var grantRaw=subject.components[GRANTS],alertAvailable=false,proficiencyBonus=0;if(grantRaw!==undefined){var grantValue=parse(grantRaw,'Subject Feature Grants'),grantState=grantsState(grantValue);if(!grantState.valid)throw new Error('Subject Feature Grants are invalid.');alertAvailable=grantState.alert;}if(useAlert&&!alertAvailable)throw new Error('Alert Initiative Proficiency requires exactly one valid Alert grant.');if(alertAvailable){var level=derivedLevel(subject);if(!level||!level.present||!level.valid||!integer(level.totalLevel,1,20)||!integer(level.proficiencyBonus,2,6))throw new Error('Subject Character Level is invalid for Alert Initiative Proficiency.');proficiencyBonus=level.proficiencyBonus;}
var episodeRaw=subject.components[EP],episode=episodeRaw?parse(episodeRaw,'Subject Rest Episode'):null,restLinks=[];for(var relationshipIndex=0;relationshipIndex<subject.relationships.length;relationshipIndex++){var relationship=subject.relationships[relationshipIndex];if(!edge(relationship))throw new Error('Subject relationship projection is corrupt.');if(relationship.kind===LINK){if(relationship.toEntityId!==subject.id||relationship.data!=='{}')throw new Error('Subject rest-world membership is corrupt.');restLinks.push(relationship);}}
if(episode){if(!validEpisode(episode))throw new Error('Subject Rest Episode is invalid.');if(restLinks.length!==1||restLinks[0].fromEntityId!==episode.worldId)throw new Error('Subject Rest Episode requires exactly one matching world membership.');}else if(restLinks.length)throw new Error('Subject has rest-world membership without a Rest Episode.');
var hasCircumstances=Object.prototype.hasOwnProperty.call(input,'rollCircumstances'),circumstances=hasCircumstances?input.rollCircumstances:[];if(!Array.isArray(circumstances))throw new Error('rollCircumstances must be an array when supplied.');if(hasCircumstances&&circumstances.length===0)throw new Error('rollCircumstances must be nonempty when supplied.');var hasAdvantage=false,hasDisadvantage=false,pairs={},accepted=[];for(var circumstanceIndex=0;circumstanceIndex<circumstances.length;circumstanceIndex++){var circumstance=input.rollCircumstances[circumstanceIndex];if(!closed(circumstance,['kind','source'])||(circumstance.kind!=='advantage'&&circumstance.kind!=='disadvantage')||typeof circumstance.source!=='string'||circumstance.source.length===0||circumstance.source!==circumstance.source.trim()||circumstance.source.indexOf('condition:')===0)throw new Error('Each roll circumstance must be an explicit advantage or disadvantage source.');var pair=circumstance.kind+'\n'+circumstance.source;if(pairs[pair])throw new Error('rollCircumstances must not repeat the same kind and source.');pairs[pair]=true;accepted.push({kind:circumstance.kind,source:circumstance.source});if(circumstance.kind==='advantage')hasAdvantage=true;else hasDisadvantage=true;}
var rollMode=hasAdvantage&&hasDisadvantage?'normal':hasAdvantage?'advantage':hasDisadvantage?'disadvantage':'normal',rolls=[ctx.randomInt(1,20)];if(rollMode!=='normal')rolls.push(ctx.randomInt(1,20));var roll=rolls.length===1?rolls[0]:rollMode==='advantage'?Math.max(rolls[0],rolls[1]):Math.min(rolls[0],rolls[1]),dexterityScore=state.scores[ABILITY_REFS.dex],dexterityModifier=Math.floor((dexterityScore-10)/2),alertBonus=useAlert?proficiencyBonus:0,initiative=roll+dexterityModifier+alertBonus,modifiers=[{source:'dex '+dexterityScore,value:dexterityModifier}],restInterruption=null;if(useAlert)modifiers.push({source:'feat:alert',value:alertBonus});
if(episode&&episode.status==='active'){if(episode.kind==='short')restInterruption={outcome:'short-stopped',worldId:episode.worldId,benefitsGranted:false};else{if(episode.requiredMinutes>RESTMAX-60||episode.interruptionCount>=16666658)throw new Error('Long Rest Initiative interruption exceeds the supported duration bounds.');var next={policyEntityId:episode.policyEntityId,kind:'long',worldId:episode.worldId,startedAtMinute:episode.startedAtMinute,observedAtMinute:episode.observedAtMinute,observedClockRevision:episode.observedClockRevision,requiredMinutes:episode.requiredMinutes+60,sleepMinutes:episode.sleepMinutes,lightActivityMinutes:episode.lightActivityMinutes,interruptionCount:episode.interruptionCount+1,status:'active',sourceRef:episode.sourceRef};restInterruption={outcome:'long-resumed',worldId:episode.worldId,episode:next,benefitsGranted:false};}}
return {narration:subject.name+' rolls Initiative: '+roll+' + '+dexterityModifier+(useAlert?' + '+alertBonus:'')+' = '+initiative+'.',data:{test:'initiative',subjectId:subject.id,ability:'dex',die:'1d20',rollMode:rollMode,rolls:rolls,roll:roll,rollCircumstances:accepted,modifiers:modifiers,initiative:initiative,source:'SRD 5.2.1 - Playing the Game > Combat > The Order of Combat > Initiative',alertInitiativeProficiency:{available:alertAvailable,used:useAlert,bonus:alertAvailable?proficiencyBonus:0,sourceRef:alertAvailable?{sourceId:SID,locator:ALERTLOC}:null},restInterruption:restInterruption},effects:[],events:[],notifications:[]};
