var s=ctx.roles.subject,w=ctx.roles.world,ROOT='game.core.world.root',CLOCK='game.core.world.clock',ACTIVE='dnd2024.effect.active-effect-state',POISON='dnd2024.hazard.poison-application',CONTAGION='dnd2024.hazard.contagion-application',EXPOSURE='dnd2024.hazard.environment-exposure',LINK='dnd2024.core.definition-link',AFFLICTION='affliction.subject',EXPOSURE_SUBJECT='hazard.exposure.subject';
function object(v){return v!==null&&!Array.isArray(v)&&typeof v==='object';}
function parse(raw,label){try{var v=JSON.parse(raw);if(!object(v))throw 0;return v;}catch(e){throw new Error(label+' is malformed.');}}
function ref(v){return object(v)&&typeof v.entityId==='string'&&v.entityId.length>0;}
if(!s||!w||!object(ctx.input)||Object.keys(ctx.input).length!==0||!ctx.audience||(ctx.audience.perspective!=='player'&&ctx.audience.perspective!=='dm'))throw new Error('Hazard status requires subject, world, empty input, and a host-authorized audience.');
var root=parse(w.components[ROOT],'World root'),clock=parse(w.components[CLOCK],'World clock');if(root.status!=='active'||!Number.isSafeInteger(clock.currentMinute)||clock.currentMinute<0||!Number.isSafeInteger(clock.revision)||clock.revision<0)throw new Error('Hazard status world or clock is invalid.');
var dm=ctx.audience.perspective==='dm',related=s.related||[],afflictions=[],exposures=[];
for(var n=0;n<related.length;n++){var row=related[n],components=row.components||{};if(row.kind===AFFLICTION&&row.toEntityId===s.id&&typeof components[ACTIVE]==='string'){var state=parse(components[ACTIVE],'Affliction state'),parameters=state.parameters||{},kind=parameters.kind;if(['poison','contagion','curse'].indexOf(kind)<0||!ref(state.definition)||!ref(state.target)||state.target.entityId!==s.id||typeof state.status!=='string'||!Number.isSafeInteger(state.stacks)||state.stacks<0||!Number.isSafeInteger(parameters.definitionRevision)||parameters.definitionRevision<1||typeof parameters.definitionFingerprint!=='string'||!/^[0-9A-F]{64}$/.test(parameters.definitionFingerprint))throw new Error('An affliction state is invalid.');if(kind==='curse'&&parameters.concealed===true&&!dm)continue;var dueMinute=Number.isSafeInteger(parameters.nextDueMinute)&&parameters.nextDueMinute>=0?parameters.nextDueMinute:null,special=null;if(kind==='poison'&&typeof components[POISON]==='string')special=parse(components[POISON],'Poison application');if(kind==='contagion'&&typeof components[CONTAGION]==='string')special=parse(components[CONTAGION],'Contagion application');afflictions.push({id:row.id,name:row.name,kind:kind,status:state.status,definitionId:state.definition.entityId,definitionRevision:parameters.definitionRevision,definitionFingerprint:parameters.definitionFingerprint,stacks:state.stacks,nextDueMinute:dueMinute,due:dueMinute!==null&&clock.currentMinute>=dueMinute,concealed:kind==='curse'&&parameters.concealed===true,phaseId:special&&ref(special.phase)?special.phase.entityId:null});}else if(row.kind===EXPOSURE_SUBJECT&&row.toEntityId===s.id&&typeof components[EXPOSURE]==='string'&&typeof components[LINK]==='string'){var exposure=parse(components[EXPOSURE],'Environmental exposure'),link=parse(components[LINK],'Environmental definition link');if(!ref(link.definition)||!Number.isSafeInteger(link.definitionRevision)||link.definitionRevision<1||!Number.isSafeInteger(exposure.exposureCount)||exposure.exposureCount<0||!Number.isSafeInteger(exposure.failedChecks)||exposure.failedChecks<0)throw new Error('An environmental exposure is invalid.');exposures.push({id:row.id,name:row.name,definitionId:link.definition.entityId,definitionRevision:link.definitionRevision,exposureCount:exposure.exposureCount,failedChecks:exposure.failedChecks});}}
afflictions.sort(function(a,b){return a.kind.localeCompare(b.kind)||a.id.localeCompare(b.id);});exposures.sort(function(a,b){return a.id.localeCompare(b.id);});if(afflictions.length>64||exposures.length>64)throw new Error('Hazard status exceeds the bounded related-record limit.');var dueCount=afflictions.filter(function(v){return v.due;}).length;
return {narration:'Projected authorized hazard status for '+s.name+'.',effects:[],events:[],notifications:[],data:{version:1,subject:{id:s.id,name:s.name},worldId:w.id,clock:{calendarId:clock.calendarId,minute:clock.currentMinute,revision:clock.revision},perspective:ctx.audience.perspective,summary:{afflictionCount:afflictions.length,exposureCount:exposures.length,dueCount:dueCount},afflictions:afflictions,environmentalExposures:exposures}};
