var source=ctx.roles.source,target=ctx.roles.target,i=ctx.input,HP='dnd2024.creature.hit-points',TEMP='dnd2024.creature.temporary-hit-points',TYPES=['acid','bludgeoning','cold','fire','force','lightning','necrotic','piercing','poison','psychic','radiant','slashing','thunder'],DICE={'dnd2024.vocabulary.die.d4':4,'dnd2024.vocabulary.die.d6':6,'dnd2024.vocabulary.die.d8':8,'dnd2024.vocabulary.die.d10':10,'dnd2024.vocabulary.die.d12':12},MAX=Number.MAX_SAFE_INTEGER;
function object(v){return v!==null&&!Array.isArray(v)&&typeof v==='object';}function closed(v,k){if(!object(v)||Object.keys(v).length!==k.length)return false;for(var n=0;n<k.length;n++)if(!Object.prototype.hasOwnProperty.call(v,k[n]))return false;return true;}function integer(v,a,b){return Number.isSafeInteger(v)&&v>=a&&v<=b;}function parse(v,l){try{var x=typeof v==='string'?JSON.parse(v):v;if(!object(x))throw 0;return x;}catch(e){throw new Error(l+' is malformed.');}}
if(!source||!target||!closed(i,['amount','damageType','saveSucceeded','successfulSaveBehavior'])||TYPES.indexOf(i.damageType)<0||typeof i.saveSucceeded!=='boolean'||['none','half','full'].indexOf(i.successfulSaveBehavior)<0)throw new Error('Hazard damage input is invalid.');
var hp=parse(target.components[HP],'Hit Point state');if(!integer(hp.current,0,MAX)||!integer(hp.maximum,1,MAX)||hp.current>hp.maximum)throw new Error('Hit Point state is invalid.');var raw=0,rolls=[];
if(integer(i.amount,0,1000000))raw=i.amount;else{if(!closed(i.amount,['count','dieRef','modifier'])||!integer(i.amount.count,1,100)||!object(i.amount.dieRef)||Object.keys(i.amount.dieRef).length!==1||!DICE[i.amount.dieRef.entityId]||!integer(i.amount.modifier,-1000,1000))throw new Error('Hazard damage amount is invalid.');for(var d=0;d<i.amount.count;d++){var roll=ctx.randomInt(1,DICE[i.amount.dieRef.entityId]);rolls.push(roll);raw+=roll;}raw=Math.max(0,raw+i.amount.modifier);}
if(i.saveSucceeded){if(i.successfulSaveBehavior==='none')raw=0;else if(i.successfulSaveBehavior==='half')raw=Math.floor(raw/2);}var children=ctx.children&&ctx.children.mitigation;if(!Array.isArray(children)||children.length!==1)throw new Error('Exactly one mitigation result is required.');var m=parse(children[0].output&&children[0].output.data,'Mitigation result');if(m.test!=='damage-mitigation-profile'||m.defenderId!==target.id||!Array.isArray(m.immunities)||!Array.isArray(m.resistances)||!Array.isArray(m.vulnerabilities))throw new Error('Mitigation result is invalid.');
var immune=m.immunities.indexOf(i.damageType)>=0,resistant=m.resistances.indexOf(i.damageType)>=0||m.petrified===true,vulnerable=m.vulnerabilities.indexOf(i.damageType)>=0,damage=immune?0:resistant&&vulnerable?raw:resistant?Math.floor(raw/2):vulnerable?raw*2:raw;if(!Number.isSafeInteger(damage)||damage<0)throw new Error('Resolved hazard damage exceeds the safe boundary.');
var effects=[],temporaryBefore=0,temporaryAfter=0,absorbed=0;if(Object.prototype.hasOwnProperty.call(target.components,TEMP)){var temporary=parse(target.components[TEMP],'Temporary Hit Points');if(!closed(temporary,['current'])||!integer(temporary.current,1,MAX))throw new Error('Temporary Hit Point state is invalid.');temporaryBefore=temporary.current;absorbed=Math.min(temporaryBefore,damage);temporaryAfter=temporaryBefore-absorbed;if(absorbed>0)effects.push(temporaryAfter>0?{type:'component.set',entityId:target.id,definitionId:TEMP,data:JSON.stringify({current:temporaryAfter})}:{type:'component.remove',entityId:target.id,definitionId:TEMP});}
var hitPointDamage=damage-absorbed,after=Math.max(0,hp.current-hitPointDamage);if(after!==hp.current){var next={current:after,maximum:hp.maximum};if(Object.prototype.hasOwnProperty.call(hp,'maximumReduction'))next.maximumReduction=hp.maximumReduction;effects.push({type:'component.set',entityId:target.id,definitionId:HP,data:JSON.stringify(next)});}return {narration:target.name+' takes '+damage+' hazard damage.',effects:effects,events:[],notifications:[],data:{test:'hazard-damage-apply',sourceId:source.id,targetId:target.id,damageType:i.damageType,rolls:rolls,rawDamage:raw,damage:damage,saveSucceeded:i.saveSucceeded,successfulSaveBehavior:i.successfulSaveBehavior,immune:immune,resistant:resistant,vulnerable:vulnerable,temporaryAbsorbed:absorbed,beforeCurrent:hp.current,afterCurrent:after}};
