var SID='source.dnd2024.srd-5.2.1',LOC='Playing the Game > Playing on a Grid > Creature Size',POS='dnd2024.encounter-position',SIZE='dnd2024.creature-size',SPACE='dnd2024.encounter-space',s=ctx.roles.subject,e=ctx.roles.encounter,i=ctx.input;
function closed(v,k){if(!v||typeof v!=='object'||Array.isArray(v))return false;var a=Object.keys(v);if(a.length!==k.length)return false;for(var n=0;n<k.length;n++)if(!Object.prototype.hasOwnProperty.call(v,k[n]))return false;return true;}
function parse(v){try{return typeof v==='string'?JSON.parse(v):v;}catch(x){return null;}}
function int(v,a,b){return typeof v==='number'&&isFinite(v)&&Math.floor(v)===v&&v>=a&&v<=b;}
function units(v){return v==='tiny'?1:(v==='small'||v==='medium')?2:v==='large'?4:v==='huge'?6:v==='gargantuan'?8:0;}
function cell(v,w,h){return closed(v,['x','y'])&&int(v.x,0,w-1)&&int(v.y,0,h-1);}
function cells(a,w,h,other){if(!Array.isArray(a)||a.length>1000)return false;var seen={},p,n;for(n=0;n<a.length;n++){p=a[n];if(!cell(p,w,h)||seen[p.x+','+p.y]||(n&&((a[n-1].y>p.y)||(a[n-1].y===p.y&&a[n-1].x>=p.x))))return false;seen[p.x+','+p.y]=true;if(other&&other[p.x+','+p.y])return false;}return true;}
function validSpace(v){if(!closed(v,['widthSquares','heightSquares','blockedCells','difficultCells','sourceRef'])||!int(v.widthSquares,1,100)||!int(v.heightSquares,1,100)||!closed(v.sourceRef,['sourceId','locator'])||v.sourceRef.sourceId!==SID||v.sourceRef.locator!=='Playing the Game > Playing on a Grid')return false;var blocked={};for(var n=0;n<v.blockedCells.length;n++)blocked[v.blockedCells[n].x+','+v.blockedCells[n].y]=true;return cells(v.blockedCells,v.widthSquares,v.heightSquares)&&cells(v.difficultCells,v.widthSquares,v.heightSquares,blocked);}
function validPos(v){return closed(v,['encounterId','anchorX','anchorY','sourceRef'])&&typeof v.encounterId==='string'&&v.encounterId.length>0&&int(v.anchorX,0,199)&&int(v.anchorY,0,199)&&closed(v.sourceRef,['sourceId','locator'])&&v.sourceRef.sourceId===SID&&v.sourceRef.locator===LOC;}
function overlaps(a,au,b,bu){return a.x<b.x+bu&&b.x<a.x+au&&a.y<b.y+bu&&b.y<a.y+au;}
if(!s||!e||!closed(i,['mode','anchorX','anchorY'])||(i.mode!=='record'&&i.mode!=='correct'))throw new Error('Input must contain exactly record/correct mode and anchor coordinates.');
var space=parse(e.components&&e.components[SPACE]),size=parse(s.components&&s.components[SIZE]);if(!validSpace(space)||!size||!closed(size,['size'])||!units(size.size))throw new Error('Encounter space and subject Size must both be valid.');
var roster=e.contains||[],inRoster=false,n,entry;for(n=0;n<roster.length;n++)if(roster[n].id===s.id&&roster[n].slot==='participant')inRoster=true;if(!inRoster)throw new Error('The subject is not an encounter participant.');
var reports={},kids=ctx.children&&ctx.children.participants;if(!Array.isArray(kids)||kids.length!==roster.length)throw new Error('Exactly one tactical snapshot is required per participant.');for(n=0;n<kids.length;n++){var kid=kids[n],id=kid&&kid.roleEntityIds&&kid.roleEntityIds.participant,data=parse(kid&&kid.output&&kid.output.data);if(!id||reports[id]||!data||!closed(data,['test','participantId','sizePresent','sizeValid','size','positionPresent','positionValid','position'])||data.test!=='encounter-participant-tactical-state-read'||data.participantId!==id)throw new Error('A participant tactical snapshot is invalid.');reports[id]=data;}
var u=units(size.size),next={encounterId:e.id,anchorX:i.anchorX,anchorY:i.anchorY,sourceRef:{sourceId:SID,locator:LOC}};if(!validPos(next)||next.anchorX+u>space.widthSquares*2||next.anchorY+u>space.heightSquares*2)throw new Error('The Size-derived footprint must remain within encounter bounds.');
for(n=0;n<space.blockedCells.length;n++){entry=space.blockedCells[n];if(overlaps({x:next.anchorX,y:next.anchorY},u,{x:entry.x*2,y:entry.y*2},2))throw new Error('Placement overlaps blocked terrain.');}
for(n=0;n<roster.length;n++){entry=roster[n];var report=reports[entry.id];if(!report)throw new Error('A participant snapshot is missing.');if(entry.id===s.id)continue;if(!report.sizePresent||!report.sizeValid||!report.size||!units(report.size.size))throw new Error('Another participant has invalid or absent Size.');if(!report.positionPresent)continue;if(!report.positionValid||!report.position||!validPos(report.position))throw new Error('Another participant has invalid position state.');if(report.position.encounterId!==e.id)throw new Error('Another participant position names a different encounter.');if(overlaps({x:next.anchorX,y:next.anchorY},u,{x:report.position.anchorX,y:report.position.anchorY},units(report.size.size)))throw new Error('Placement overlaps another participant.');}
var raw=s.components&&s.components[POS];if(raw){var old=parse(raw);if(!validPos(old))throw new Error('Existing position is invalid.');}if(i.mode==='record'&&raw)throw new Error('Position already exists.');if(i.mode==='correct'&&!raw)throw new Error('Position is absent.');
return {narration:s.name+' placement is '+i.mode+'ed.',data:{test:'encounter-position-write',mode:i.mode,subjectId:s.id,position:next,footprintUnits:u},effects:[{type:i.mode==='record'?'component.add':'component.set',entityId:s.id,definitionId:POS,data:JSON.stringify(next)}]};
