[CmdletBinding()]
param(
    [ValidateSet('5A', '5B', '5C')][string]$Stage = '5C',
    [string]$NpxCommand = 'npx'
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$repo = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..\..\..')).Path
$root = Join-Path $repo 'ruleset/dnd2024/adoption/transformation'
$contracts = Join-Path $root 'contracts'; $fixtures = Join-Path $root 'fixtures'
$transformer = Join-Path $PSScriptRoot 'Invoke-ContentTransformation.ps1'
$temporary = Join-Path ([IO.Path]::GetTempPath()) ('dantesroleplay-content-transform-' + [guid]::NewGuid().ToString('N'))
[IO.Directory]::CreateDirectory($temporary) | Out-Null

function Invoke-Ajv { param([string[]]$Arguments) $output=@(& $NpxCommand --yes ajv-cli@5.0.0 @Arguments 2>&1|ForEach-Object{"$_"});return [pscustomobject]@{exitCode=$LASTEXITCODE;output=$output} }
function Require-AjvSuccess { param([string[]]$Arguments,[string]$Message) $result=Invoke-Ajv $Arguments;if($result.exitCode -ne 0){throw "${Message}: $($result.output -join [Environment]::NewLine)"} }
function Set-JsonPointer { param($Root,[string]$Pointer,$Value) $segments=@($Pointer.TrimStart('/').Split('/')|ForEach-Object{$_.Replace('~1','/').Replace('~0','~')});$cursor=$Root;for($index=0;$index -lt $segments.Count-1;$index++){$segment=$segments[$index];if($cursor -is [System.Array]){$cursor=$cursor[[int]$segment]}else{$property=$cursor.PSObject.Properties[$segment];if($null -eq $property){throw "Pointer does not resolve: $Pointer"};$cursor=$property.Value}};$last=$segments[-1];if($cursor -is [System.Array]){$cursor[[int]$last]=$Value}else{$property=$cursor.PSObject.Properties[$last];if($null -eq $property){$cursor|Add-Member -NotePropertyName $last -NotePropertyValue $Value}else{$property.Value=$Value}} }
function Write-Json { param($Value,[string]$Path) [IO.File]::WriteAllText($Path,($Value|ConvertTo-Json -Depth 100),[Text.UTF8Encoding]::new($false)) }
function Run-Transformer { param([string[]]$Arguments) & pwsh -NoProfile -File $transformer @Arguments 2>$null | Out-Null;return $LASTEXITCODE }

try {
    $manifestSchema=Join-Path $contracts 'content-transform-manifest.schema.json';$candidateSchema=Join-Path $contracts 'staged-content-candidate.schema.json';$manifestFixture=Join-Path $fixtures 'content-transform-manifest.valid.json'
    Require-AjvSuccess @('compile','--spec=draft2020','--strict=false','-s',$manifestSchema) 'Manifest schema compilation failed'
    Require-AjvSuccess @('validate','--spec=draft2020','--strict=false','-s',$manifestSchema,'-d',$manifestFixture) 'Manifest fixture validation failed'
    $dndOwned=Get-Content -Raw $manifestFixture|ConvertFrom-Json -Depth 100;$dndOwned.entries[0].ruleset.alignment='dnd2024-owned';$dndOwned.entries[0].ruleset.sourceId='source.dnd2024.srd-5.2.1';$dndOwned.entries[0].ruleset.locator='Playing the Game > Ability Checks';$dndOwned.entries[0].ruleset.officialVerified=$true;$dndOwned.entries[0].source.commit=('a' * 40);$dndOwned.entries[0].source.lockSha256=('B' * 64);$dndOwnedPath=Join-Path $temporary 'dnd-owned-positive.json';Write-Json $dndOwned $dndOwnedPath;Require-AjvSuccess @('validate','--spec=draft2020','--strict=false','-s',$manifestSchema,'-d',$dndOwnedPath) 'D&D-owned provenance fixture validation failed';foreach($pointer in @('/entries/0/source/commit','/entries/0/source/lockSha256','/entries/0/source/review/evidence','/entries/0/ruleset/officialVerified')){$negativeDnd=Get-Content -Raw $dndOwnedPath|ConvertFrom-Json -Depth 100;Set-JsonPointer $negativeDnd $pointer $null;$path=Join-Path $temporary ('dnd-negative-' + [guid]::NewGuid().ToString('N') + '.json');Write-Json $negativeDnd $path;$result=Invoke-Ajv @('validate','--spec=draft2020','--strict=false','-s',$manifestSchema,'-d',$path);if($result.exitCode -eq 0){throw "D&D-owned provenance negative unexpectedly validated: $pointer"}}
    $invalid=Get-Content -Raw (Join-Path $fixtures 'content-transform-manifest.invalid-cases.json')|ConvertFrom-Json -Depth 100
    foreach($case in $invalid.cases){$document=Get-Content -Raw $manifestFixture|ConvertFrom-Json -Depth 100;foreach($mutation in $case.mutations){Set-JsonPointer $document $mutation.pointer $mutation.value};$path=Join-Path $temporary ('invalid-' + [guid]::NewGuid().ToString('N') + '.json');Write-Json $document $path;$result=Invoke-Ajv @('validate','--spec=draft2020','--strict=false','-s',$manifestSchema,'-d',$path);if($result.exitCode -eq 0){throw "Manifest negative validation unexpectedly succeeded: $($case.name)"}}
    $negativeCount=@($invalid.cases).Count
    if($Stage -eq '5A'){[ordered]@{format='application-adoption-content-transform-test/v1';stage='5A';schemaCompilations=1;positiveDocuments=1;negativeDocuments=$negativeCount}|ConvertTo-Json;return}

    Require-AjvSuccess @('compile','--spec=draft2020','--strict=false','-s',$candidateSchema,'-r',$manifestSchema) 'Candidate schema compilation failed'
    $report1=Join-Path $temporary 'dry-run-1.json';$report2=Join-Path $temporary 'dry-run-2.json';$common=@('-ManifestPath',$manifestFixture,'-SourceRoot',$root,'-DryRun')
    if((Run-Transformer ($common + @('-ReportPath',$report1))) -ne 0 -or (Run-Transformer ($common + @('-ReportPath',$report2))) -ne 0){throw 'Valid dry-run transformation failed.'}
    if((Get-FileHash $report1 -Algorithm SHA256).Hash -cne (Get-FileHash $report2 -Algorithm SHA256).Hash){throw 'Dry-run report was not deterministic.'}
    $report=Get-Content -Raw $report1|ConvertFrom-Json -Depth 100;if($report.status -ne 'ready' -or @($report.candidates).Count -ne 2){throw 'Dry-run report did not plan all candidates.'}
    $stage1=Join-Path $temporary 'stage-1';$stage2=Join-Path $temporary 'stage-2';if((Run-Transformer @('-ManifestPath',$manifestFixture,'-SourceRoot',$root,'-StagingDirectory',$stage1,'-ReportPath',(Join-Path $temporary 'stage-1-report.json'))) -ne 0 -or (Run-Transformer @('-ManifestPath',$manifestFixture,'-SourceRoot',$root,'-StagingDirectory',$stage2,'-ReportPath',(Join-Path $temporary 'stage-2-report.json'))) -ne 0){throw 'Valid staging transformation failed.'}
    foreach($target in @('staged/sample.content.one.json','staged/sample.content.two.json')){$left=Join-Path $stage1 $target;$right=Join-Path $stage2 $target;if(-not(Test-Path $left -PathType Leaf) -or -not(Test-Path $right -PathType Leaf)){throw "Staged candidate is missing: $target"};if((Get-FileHash $left -Algorithm SHA256).Hash -cne (Get-FileHash $right -Algorithm SHA256).Hash){throw "Staged candidate was not deterministic: $target"};Require-AjvSuccess @('validate','--spec=draft2020','--strict=false','-s',$candidateSchema,'-r',$manifestSchema,'-d',$left) "Staged candidate validation failed: $target"}
    $badHash=Get-Content -Raw $manifestFixture|ConvertFrom-Json -Depth 100;$badHash.entries[0].source.sha256='0000000000000000000000000000000000000000000000000000000000000000';$badHashPath=Join-Path $temporary 'bad-hash.json';Write-Json $badHash $badHashPath;$badHashStage=Join-Path $temporary 'bad-hash-stage';if((Run-Transformer @('-ManifestPath',$badHashPath,'-SourceRoot',$root,'-StagingDirectory',$badHashStage,'-ReportPath',(Join-Path $temporary 'bad-hash-report.json'))) -eq 0){throw 'Hash mismatch did not reject the batch.'};if(Test-Path $badHashStage){if(@(Get-ChildItem -Recurse -File $badHashStage).Count -ne 0){throw 'Rejected hash batch wrote staged candidates.'}}
    foreach($hashTarget in @(@{name='schema';pointer='/entries/0/target/schemaSha256'},@{name='mapping';pointer='/entries/0/transformation/mappingSha256'},@{name='tool';pointer='/entries/0/transformation/toolSha256'})){$mutated=Get-Content -Raw $manifestFixture|ConvertFrom-Json -Depth 100;Set-JsonPointer $mutated $hashTarget.pointer '0000000000000000000000000000000000000000000000000000000000000000';$mutatedPath=Join-Path $temporary ("bad-$($hashTarget.name)-hash.json");Write-Json $mutated $mutatedPath;if((Run-Transformer @('-ManifestPath',$mutatedPath,'-SourceRoot',$root,'-DryRun','-ReportPath',(Join-Path $temporary ("bad-$($hashTarget.name)-report.json")))) -eq 0){throw "$($hashTarget.name) hash mismatch did not reject the batch."}}
    if($Stage -eq '5B'){[ordered]@{format='application-adoption-content-transform-test/v1';stage='5B';schemaCompilations=2;negativeDocuments=$negativeCount;deterministicDryRun=1;deterministicCandidates=2;hashMismatch='rejected'}|ConvertTo-Json;return}

    $blockedLicense=Get-Content -Raw $manifestFixture|ConvertFrom-Json -Depth 100;$blockedLicense.entries[0].license.classification='unknown';$blockedLicense.entries[0].license.disposition='blocked-mixed-or-unknown';$blockedLicense.entries[0].license.review.state='not-reviewed';$blockedLicense.entries[0].license.review.evidence=$null;$blockedPath=Join-Path $temporary 'blocked-license.json';Write-Json $blockedLicense $blockedPath;$blockedStage=Join-Path $temporary 'blocked-stage';if((Run-Transformer @('-ManifestPath',$blockedPath,'-SourceRoot',$root,'-StagingDirectory',$blockedStage,'-ReportPath',(Join-Path $temporary 'blocked-report.json'))) -eq 0){throw 'Blocked license did not reject the batch.'};if(Test-Path $blockedStage){if(@(Get-ChildItem -Recurse -File $blockedStage).Count -ne 0){throw 'Rejected license batch wrote staged candidates.'}}
    $duplicate=Get-Content -Raw $manifestFixture|ConvertFrom-Json -Depth 100;$duplicate.entries[1].target.path=$duplicate.entries[0].target.path;$duplicatePath=Join-Path $temporary 'duplicate-target.json';Write-Json $duplicate $duplicatePath;$duplicateStage=Join-Path $temporary 'duplicate-stage';if((Run-Transformer @('-ManifestPath',$duplicatePath,'-SourceRoot',$root,'-StagingDirectory',$duplicateStage,'-ReportPath',(Join-Path $temporary 'duplicate-report.json'))) -eq 0){throw 'Duplicate target path did not reject the batch.'};if(Test-Path $duplicateStage){if(@(Get-ChildItem -Recurse -File $duplicateStage).Count -ne 0){throw 'Rejected duplicate batch wrote staged candidates.'}}
    $normalizedAlias=Get-Content -Raw $manifestFixture|ConvertFrom-Json -Depth 100;$normalizedAlias.entries[1].target.path='staged/./sample.content.one.json';$normalizedAliasPath=Join-Path $temporary 'normalized-alias.json';Write-Json $normalizedAlias $normalizedAliasPath;$normalizedAliasStage=Join-Path $temporary 'normalized-alias-stage';if((Run-Transformer @('-ManifestPath',$normalizedAliasPath,'-SourceRoot',$root,'-StagingDirectory',$normalizedAliasStage,'-ReportPath',(Join-Path $temporary 'normalized-alias-report.json'))) -eq 0){throw 'Normalized target alias did not reject the batch.'};if(Test-Path $normalizedAliasStage){if(@(Get-ChildItem -Recurse -File $normalizedAliasStage).Count -ne 0){throw 'Rejected normalized-alias batch wrote staged candidates.'}}
    $reparseStage=Join-Path $temporary 'reparse-stage';$outsideStage=Join-Path $temporary 'outside-stage';[IO.Directory]::CreateDirectory($reparseStage)|Out-Null;[IO.Directory]::CreateDirectory($outsideStage)|Out-Null;New-Item -ItemType Junction -Path (Join-Path $reparseStage 'staged') -Target $outsideStage | Out-Null;if((Run-Transformer @('-ManifestPath',$manifestFixture,'-SourceRoot',$root,'-StagingDirectory',$reparseStage,'-ReportPath',(Join-Path $temporary 'reparse-report.json'))) -eq 0){throw 'Reparse-point target did not reject the batch.'};if(@(Get-ChildItem -Recurse -File $outsideStage).Count -ne 0){throw 'Reparse-point target wrote outside the staging root.'}
    $sourceRootLink=Join-Path $temporary 'source-root-link';New-Item -ItemType Junction -Path $sourceRootLink -Target $root | Out-Null;if((Run-Transformer @('-ManifestPath',$manifestFixture,'-SourceRoot',$sourceRootLink,'-DryRun','-ReportPath',(Join-Path $temporary 'source-root-link-report.json'))) -eq 0){throw 'Reparse-point source root did not reject the batch.'};$stagingRootLink=Join-Path $temporary 'staging-root-link';New-Item -ItemType Junction -Path $stagingRootLink -Target $outsideStage | Out-Null;if((Run-Transformer @('-ManifestPath',$manifestFixture,'-SourceRoot',$root,'-StagingDirectory',$stagingRootLink,'-ReportPath',(Join-Path $temporary 'staging-root-link-report.json'))) -eq 0){throw 'Reparse-point staging root did not reject the batch.'}
    if((Run-Transformer @('-ManifestPath',$manifestFixture,'-SourceRoot',$root,'-DryRun','-ExistingTargetRoot',$stage1,'-ReportPath',(Join-Path $temporary 'existing-collision-report.json'))) -eq 0){throw 'Existing target collision did not reject the batch.'}
    [ordered]@{format='application-adoption-content-transform-test/v1';stage='5C';schemaCompilations=2;negativeDocuments=$negativeCount;deterministicDryRun=1;deterministicCandidates=2;hashMismatch='rejected';schemaMappingToolHashes='rejected';blockedLicense='rejected';duplicateTarget='rejected';normalizedAlias='rejected';reparsePoint='rejected';existingTarget='rejected'}|ConvertTo-Json
}
finally { if(Test-Path -LiteralPath $temporary){Remove-Item -LiteralPath $temporary -Recurse -Force} }
