var a=ctx.roles.left,b=ctx.roles.right,w=ctx.roles.world,LOCATION='game.core.world.location',KIND='game.core.world.location.connected-to';
function exact(v,keys){if(v===null||Array.isArray(v)||typeof v!=='object')return false;var a=Object.keys(v).sort(),b=keys.slice().sort();return JSON.stringify(a)===JSON.stringify(b);}
function parse(v,n){if(typeof v!=='string')throw new Error(n+' is corrupt.');try{return JSON.parse(v);}catch(e){throw new Error(n+' is corrupt.');}}
function text(v,n){return typeof v==='string'&&v.trim()===v&&v.length>0&&Array.from(v).length<=n;}
function active(v){return exact(v,['kind','status','summary','visibility'])&&['region','settlement','site','interior'].indexOf(v.kind)>=0&&v.status==='active'&&text(v.summary,1000)&&['public','party','gm'].indexOf(v.visibility)>=0;}
function find(items,id){if(!Array.isArray(items))return null;for(var i=0;i<items.length;i++){var n=items[i];if(n.id===id)return n;var nested=find(n.contains,id);if(nested)return nested;}return null;}
var pending=exact(ctx.input,['locationId','locationName','locationStatus','targetLocationId'])?ctx.input:null;
if(pending){if(a||pending.locationStatus!=='active'||pending.locationId===pending.targetLocationId)throw new Error('Pending adjacency requires one active shell and one distinct target.');var target=b;if(!target&&w)target=find(w.contains,pending.targetLocationId);if(!target||target.id!==pending.targetLocationId||!target.components||!target.components[LOCATION]||!active(parse(target.components[LOCATION],'Target location state')))throw new Error('The adjacency target is not an active projected location.');a={id:pending.locationId,name:pending.locationName,relationships:[]};b={id:target.id,name:target.name};}
else{if(!exact(ctx.input,[])||!a||!b||!a.components||!b.components||!a.components[LOCATION]||!b.components[LOCATION]||!Array.isArray(a.relationships)||!active(parse(a.components[LOCATION],'Left location state'))||!active(parse(b.components[LOCATION],'Right location state')))throw new Error('Adjacency creation requires two distinct active location roles with input {}.');}
if(a.id===b.id)throw new Error('A location cannot connect to itself.');
for(var x=0;x<a.relationships.length;x++){var e=a.relationships[x];if(!exact(e,['data','fromEntityId','kind','toEntityId'])||typeof e.data!=='string')throw new Error('Location relationship evidence is corrupt.');if(e.kind===KIND&&((e.fromEntityId===a.id&&e.toEntityId===b.id)||(e.fromEntityId===b.id&&e.toEntityId===a.id)))throw new Error('The locations are already connected.');}
var from=a.id<b.id?a:b,to=a.id<b.id?b:a;
return {narration:a.name+' and '+b.name+' are connected.',effects:[{type:'relationship.create',entityId:from.id,toEntityId:to.id,kind:KIND,data:'{}'}],events:[],notifications:[],data:{fromLocationId:from.id,toLocationId:to.id,kind:KIND}};
