var SID='source.dnd2024.srd-5.2.1',LOC='Playing the Game > Combat > The Order of Combat',ORDER='dnd2024.encounter-initiative-order',STATE='dnd2024.encounter-turn-state',e=ctx.roles.encounter,i=ctx.input,MAX=9007199254740991;
function closed(v,keys){if(!v||typeof v!=='object'||Array.isArray(v))return false;var a=Object.keys(v);if(a.length!==keys.length)return false;for(var z=0;z<keys.length;z++)if(!Object.prototype.hasOwnProperty.call(v,keys[z]))return false;return true;}
function safeInt(v,min,max){return typeof v==='number'&&isFinite(v)&&Math.floor(v)===v&&v>=min&&v<=max;}
function source(v,locator){return closed(v,['sourceId','locator'])&&v.sourceId===SID&&v.locator===locator;}
function validSpeed(v){return closed(v,['walkFeet','burrowFeet','climbFeet','flyFeet','swimFeet','sourceRef'])&&safeInt(v.walkFeet,5,1000)&&v.walkFeet%5===0&&safeInt(v.burrowFeet,0,1000)&&v.burrowFeet%5===0&&safeInt(v.climbFeet,0,1000)&&v.climbFeet%5===0&&safeInt(v.flyFeet,0,1000)&&v.flyFeet%5===0&&safeInt(v.swimFeet,0,1000)&&v.swimFeet%5===0&&source(v.sourceRef,'Rules Glossary > Speed');}
function readReports(children,key,roleName,idName,test,valueName,roster,count,extraKeys){var kids=children&&children[key],reports={},n,k,role,data,keys=['test',idName,'present','valid','problem',valueName].concat(extraKeys||[]);if(!Array.isArray(kids)||kids.length!==count)throw new Error('Exactly one '+test+' diagnostic is required per encounter participant.');for(n=0;n<kids.length;n++){k=kids[n];role=k&&k.roleEntityIds&&k.roleEntityIds[roleName];if(!role||!roster[role]||reports[role])throw new Error('A '+test+' diagnostic does not match the encounter roster.');try{data=JSON.parse(k.output&&k.output.data?k.output.data:'{}');}catch(error){throw new Error('A '+test+' diagnostic is unreadable.');}if(!closed(data,keys)||data.test!==test||data[idName]!==role||typeof data.present!=='boolean'||typeof data.valid!=='boolean')throw new Error('A '+test+' diagnostic has an invalid shape.');reports[role]=data;}return reports;}
function readBudgets(children,roster,count){var reports=readReports(children,'budgets','participant','participantId','turn-budget-read','budget',roster,count,['conditionsPresent','conditionsValid','conditionProblem','exhaustionLevel']),ids=Object.keys(reports),n,data;for(n=0;n<ids.length;n++){data=reports[ids[n]];if(typeof data.conditionsPresent!=='boolean'||typeof data.conditionsValid!=='boolean'||(data.conditionProblem!==null&&data.conditionProblem!=='malformed'&&data.conditionProblem!=='invalid')||(data.conditionsValid?(data.conditionProblem!==null||!safeInt(data.exhaustionLevel,0,6)):data.exhaustionLevel!==null))throw new Error('A turn-budget diagnostic has an invalid condition shape.');}return reports;}
if(!e)throw new Error('An encounter role is required.');
if(!closed(i,[]))throw new Error('Starting encounter turns requires exactly an empty object input.');
if(e.components&&e.components[STATE])throw new Error('This encounter already has turn lifecycle state; restarting or correcting it is not authorized.');
var snapshotRaw=e.components&&e.components[ORDER],snapshot;try{snapshot=typeof snapshotRaw==='string'?JSON.parse(snapshotRaw):snapshotRaw;}catch(error){throw new Error('Encounter Initiative order is corrupt.');}
if(!snapshot||!closed(snapshot,['order','sourceRef'])||!source(snapshot.sourceRef,LOC+' > Initiative')||!Array.isArray(snapshot.order)||snapshot.order.length<1||snapshot.order.length>100)throw new Error('Encounter Initiative order is missing or invalid.');
var orderIds={},n,row;for(n=0;n<snapshot.order.length;n++){row=snapshot.order[n];if(!closed(row,['participantId','initiative'])||typeof row.participantId!=='string'||row.participantId.length===0||!safeInt(row.initiative,-MAX,MAX))throw new Error('Encounter Initiative order contains an invalid participant entry.');if(orderIds[row.participantId])throw new Error('Encounter Initiative order repeats participant '+row.participantId+'.');orderIds[row.participantId]=true;}
var contents=e.contains||[],roster={};if(!Array.isArray(contents)||contents.length!==snapshot.order.length)throw new Error('Encounter containment does not match the Initiative order.');for(n=0;n<contents.length;n++){if(!contents[n]||typeof contents[n].id!=='string'||contents[n].id.length===0)throw new Error('Encounter containment contains an invalid participant.');if(roster[contents[n].id])throw new Error('Encounter containment repeats participant '+contents[n].id+'.');roster[contents[n].id]=true;if(!orderIds[contents[n].id])throw new Error('Encounter containment does not match the Initiative order.');}for(n=0;n<snapshot.order.length;n++)if(!roster[snapshot.order[n].participantId])throw new Error('Encounter Initiative order does not match encounter containment.');
var budgets=readBudgets(ctx.children,roster,snapshot.order.length);for(n=0;n<snapshot.order.length;n++){var budget=budgets[snapshot.order[n].participantId];if(!budget.valid||!budget.present||budget.problem!==null||!budget.budget)throw new Error('Every encounter participant requires a valid turn budget before turns can start.');}
var speeds=readReports(ctx.children,'speeds','subject','subjectId','speed-read','speed',roster,snapshot.order.length),active=snapshot.order[0].participantId,speed=speeds[active];if(!speed.valid||!speed.present||speed.problem!==null||!validSpeed(speed.speed))throw new Error('The newly active participant has no valid Speed.');
var activeBudget=budgets[active];if(!activeBudget.conditionsValid)throw new Error('The newly active participant has invalid condition state.');var movementMaximumFeet=speed.speed.walkFeet,movementReductionFeet=5*activeBudget.exhaustionLevel,movementRemainingFeet=Math.max(0,movementMaximumFeet-movementReductionFeet);
var restored={action:true,bonusAction:true,reaction:true,freeInteraction:true,movementRemainingFeet:movementRemainingFeet,sourceRef:activeBudget.budget.sourceRef},state={status:'active',round:1,turnIndex:0,sourceRef:{sourceId:SID,locator:LOC}};
return {narration:e.name+' begins round 1; '+active+' takes the first turn.',data:{test:'encounter-turn-start',encounterId:e.id,status:'active',round:1,turnIndex:0,activeParticipantId:active,restoredParticipantId:active,walkFeet:movementMaximumFeet,movementMaximumFeet:movementMaximumFeet,movementReductionFeet:movementReductionFeet,movementRemainingFeet:movementRemainingFeet,participantCount:snapshot.order.length,source:'SRD 5.2.1 - Playing the Game: Combat > The Order of Combat'},effects:[{type:'component.add',entityId:e.id,definitionId:STATE,data:JSON.stringify(state)},{type:'component.set',entityId:active,definitionId:'dnd2024.turn-budget',data:JSON.stringify(restored)}]};
