var SID='source.dnd2024.srd-5.2.1',BLOC='Playing the Game > Actions; Bonus Actions; Reactions; Interacting with Objects; Combat > Your Turn',SLOC='Rules Glossary > Speed',BUDGET='dnd2024.turn-budget',SPEED='dnd2024.speed',ORDER='dnd2024.encounter-initiative-order',STATE='dnd2024.encounter-turn-state',s=ctx.roles.subject,e=ctx.roles.encounter,i=ctx.input,MAX=9007199254740991;
function closed(v,keys){if(!v||typeof v!=='object'||Array.isArray(v))return false;var a=Object.keys(v);if(a.length!==keys.length)return false;for(var z=0;z<keys.length;z++)if(!Object.prototype.hasOwnProperty.call(v,keys[z]))return false;return true;}
function integer(v,min,max){return typeof v==='number'&&isFinite(v)&&Math.floor(v)===v&&v>=min&&v<=max;}
function source(v,locator){return closed(v,['sourceId','locator'])&&v.sourceId===SID&&v.locator===locator;}
function parse(raw,name){try{return typeof raw==='string'?JSON.parse(raw):raw;}catch(error){throw new Error(name+' is corrupt.');}}
function validBudget(v){return closed(v,['action','bonusAction','reaction','freeInteraction','movementRemainingFeet','sourceRef'])&&typeof v.action==='boolean'&&typeof v.bonusAction==='boolean'&&typeof v.reaction==='boolean'&&typeof v.freeInteraction==='boolean'&&integer(v.movementRemainingFeet,0,1000)&&source(v.sourceRef,BLOC);}
function validSpeed(v){return closed(v,['walkFeet','burrowFeet','climbFeet','flyFeet','swimFeet','sourceRef'])&&integer(v.walkFeet,5,1000)&&v.walkFeet%5===0&&integer(v.burrowFeet,0,1000)&&v.burrowFeet%5===0&&integer(v.climbFeet,0,1000)&&v.climbFeet%5===0&&integer(v.flyFeet,0,1000)&&v.flyFeet%5===0&&integer(v.swimFeet,0,1000)&&v.swimFeet%5===0&&source(v.sourceRef,SLOC);}
if(!s||!e)throw new Error('A subject and encounter role are required.');
if(!i||typeof i!=='object'||Array.isArray(i))throw new Error('Input must be an object.');
var resource=i.resource;
if(resource!=='action'&&resource!=='bonusAction'&&resource!=='reaction'&&resource!=='freeInteraction'&&resource!=='movement')throw new Error('resource must be action, bonusAction, reaction, freeInteraction, or movement.');
if(resource==='movement'){if(!closed(i,['resource','feet'])||!integer(i.feet,5,1000)||i.feet%5!==0)throw new Error('Movement spending requires exactly a positive whole-foot multiple of 5 in feet.');}else if(!closed(i,['resource']))throw new Error('Boolean resource spending requires exactly resource and no feet.');
var budget=parse(s.components&&s.components[BUDGET],'Turn budget');
if(!validBudget(budget))throw new Error('The subject has no valid turn budget.');
if(resource==='movement'){var speed=parse(s.components&&s.components[SPEED],'Speed');if(!validSpeed(speed))throw new Error('The subject has no valid base Speed.');if(budget.movementRemainingFeet>speed.walkFeet)throw new Error('Turn budget remaining movement exceeds the subject\'s walk Speed.');}
var snapshot=parse(e.components&&e.components[ORDER],'Encounter Initiative order');
if(!snapshot||!closed(snapshot,['order','sourceRef'])||!source(snapshot.sourceRef,'Playing the Game > Combat > The Order of Combat > Initiative')||!Array.isArray(snapshot.order)||snapshot.order.length<1||snapshot.order.length>100)throw new Error('Encounter Initiative order is missing or invalid.');
var orderIds={},n,row;for(n=0;n<snapshot.order.length;n++){row=snapshot.order[n];if(!closed(row,['participantId','initiative'])||typeof row.participantId!=='string'||row.participantId.length===0||!integer(row.initiative,-MAX,MAX))throw new Error('Encounter Initiative order contains an invalid participant entry.');if(orderIds[row.participantId])throw new Error('Encounter Initiative order repeats participant '+row.participantId+'.');orderIds[row.participantId]=true;}
var contents=e.contains||[],roster={};if(!Array.isArray(contents)||contents.length!==snapshot.order.length)throw new Error('Encounter containment does not match the Initiative order.');for(n=0;n<contents.length;n++){if(!contents[n]||typeof contents[n].id!=='string'||contents[n].id.length===0)throw new Error('Encounter containment contains an invalid participant.');if(roster[contents[n].id])throw new Error('Encounter containment repeats participant '+contents[n].id+'.');roster[contents[n].id]=true;if(!orderIds[contents[n].id])throw new Error('Encounter containment does not match the Initiative order.');}for(n=0;n<snapshot.order.length;n++)if(!roster[snapshot.order[n].participantId])throw new Error('Encounter Initiative order does not match encounter containment.');
if(!roster[s.id]||!orderIds[s.id])throw new Error('The subject is not a participant in this encounter.');
var turn=parse(e.components&&e.components[STATE],'Encounter turn state');if(!turn||!closed(turn,['status','round','turnIndex','sourceRef'])||!source(turn.sourceRef,'Playing the Game > Combat > The Order of Combat')||turn.status!=='active'||!integer(turn.round,1,MAX)||!integer(turn.turnIndex,0,snapshot.order.length-1))throw new Error('Encounter turn state is missing, inactive, or invalid.');
var active=snapshot.order[turn.turnIndex].participantId;if(resource!=='reaction'&&s.id!==active)throw new Error('Only the active participant may spend '+resource+'.');
var kids=ctx.children&&ctx.children.stateEffects;if(!Array.isArray(kids)||kids.length!==1)throw new Error('Exactly one condition state-effects result is required.');
var stateEffects;try{stateEffects=JSON.parse(kids[0].output&&kids[0].output.data?kids[0].output.data:'{}');}catch(error){throw new Error('Condition state-effects result is unreadable.');}
if(!stateEffects||typeof stateEffects!=='object'||Array.isArray(stateEffects)||stateEffects.test!=='d20-test-state-effects'||stateEffects.subjectId!==s.id||typeof stateEffects.conditionsKnown!=='boolean'||!Array.isArray(stateEffects.prohibitions))throw new Error('Condition state-effects result has an invalid shape.');
var prohibited=null;for(n=0;n<stateEffects.prohibitions.length;n++){var prohibition=stateEffects.prohibitions[n];if(!closed(prohibition,['resource','reason'])||(prohibition.resource!=='action'&&prohibition.resource!=='bonusAction'&&prohibition.resource!=='reaction'&&prohibition.resource!=='movement')||typeof prohibition.reason!=='string'||prohibition.reason.indexOf('condition:')!==0)throw new Error('Condition state-effects prohibition is invalid.');if(prohibition.resource===resource){if(prohibited!==null)throw new Error('Condition state-effects repeats a resource prohibition.');prohibited=prohibition;}}
if(prohibited!==null)throw new Error('The '+resource+' resource is prohibited by '+prohibited.reason+'.');
var before,after,next;if(resource==='movement'){before=budget.movementRemainingFeet;if(i.feet>before)throw new Error('The requested movement exceeds the remaining movement allowance.');after=before-i.feet;next={action:budget.action,bonusAction:budget.bonusAction,reaction:budget.reaction,freeInteraction:budget.freeInteraction,movementRemainingFeet:after,sourceRef:budget.sourceRef};}else{before=budget[resource];if(!before)throw new Error('The '+resource+' resource is already spent.');after=false;next={action:resource==='action'?false:budget.action,bonusAction:resource==='bonusAction'?false:budget.bonusAction,reaction:resource==='reaction'?false:budget.reaction,freeInteraction:resource==='freeInteraction'?false:budget.freeInteraction,movementRemainingFeet:budget.movementRemainingFeet,sourceRef:budget.sourceRef};}
var data={test:'turn-budget-spend',encounterId:e.id,subjectId:s.id,activeParticipantId:active,resource:resource,before:before,after:after};if(resource==='movement'){data.feetSpent=i.feet;data.movementRemainingFeet=after;}
return {narration:s.name+' spends '+(resource==='movement'?i.feet+' feet of movement':resource)+'.',data:data,effects:[{type:'component.set',entityId:s.id,definitionId:BUDGET,data:JSON.stringify(next)}]};
