var SID='source.dnd2024.srd-5.2.1',LOC='Playing the Game > Actions; Bonus Actions; Reactions; Interacting with Objects; Combat > Your Turn',CLOC='Rules Glossary',DEF='dnd2024.turn-budget',CONDITIONS='dnd2024.conditions',ORDER=['blinded','charmed','deafened','frightened','grappled','incapacitated','invisible','paralyzed','petrified','poisoned','prone','restrained','stunned','unconscious','exhaustion'],p=ctx.roles.participant,i=ctx.input;
function closed(v,keys){if(!v||typeof v!=='object'||Array.isArray(v))return false;var a=Object.keys(v);if(a.length!==keys.length)return false;for(var n=0;n<keys.length;n++)if(!Object.prototype.hasOwnProperty.call(v,keys[n]))return false;return true;}
function integer(v,min,max){return typeof v==='number'&&isFinite(v)&&Math.floor(v)===v&&v>=min&&v<=max;}
function source(v){return closed(v,['sourceId','locator'])&&v.sourceId===SID&&v.locator===LOC;}
function valid(v){return closed(v,['action','bonusAction','reaction','freeInteraction','movementRemainingFeet','sourceRef'])&&typeof v.action==='boolean'&&typeof v.bonusAction==='boolean'&&typeof v.reaction==='boolean'&&typeof v.freeInteraction==='boolean'&&integer(v.movementRemainingFeet,0,1000)&&source(v.sourceRef);}
function conditionSource(v){return closed(v,['sourceId','locator'])&&v.sourceId===SID&&v.locator===CLOC;}
function entityId(v){return typeof v==='string'&&v.length>0&&v.length<=200&&v===v.trim();}
function conditionEntry(v){return v&&typeof v==='object'&&!Array.isArray(v)&&typeof v.condition==='string'&&ORDER.indexOf(v.condition)>=0&&(v.condition==='exhaustion'?closed(v,['condition','level'])&&integer(v.level,1,6):(closed(v,['condition'])||closed(v,['condition','sourceEntityId']))&&(!Object.prototype.hasOwnProperty.call(v,'sourceEntityId')||entityId(v.sourceEntityId)));}
function conditionKey(v){return v.condition+'\u0000'+(Object.prototype.hasOwnProperty.call(v,'sourceEntityId')?v.sourceEntityId:'');}
function compareConditions(a,b){var order=ORDER.indexOf(a.condition)-ORDER.indexOf(b.condition);if(order!==0)return order;var aSource=Object.prototype.hasOwnProperty.call(a,'sourceEntityId')?a.sourceEntityId:null,bSource=Object.prototype.hasOwnProperty.call(b,'sourceEntityId')?b.sourceEntityId:null;if(aSource===null)return bSource===null?0:-1;if(bSource===null)return 1;return aSource<bSource?-1:aSource>bSource?1:0;}
function validConditions(v){if(!closed(v,['entries','sourceRef'])||!Array.isArray(v.entries)||v.entries.length>100||!conditionSource(v.sourceRef))return false;var seen={},petrified=false,poisoned=false,n,x;for(n=0;n<v.entries.length;n++){x=v.entries[n];if(!conditionEntry(x)||seen[conditionKey(x)]||(n>0&&compareConditions(v.entries[n-1],x)>=0))return false;seen[conditionKey(x)]=true;petrified=petrified||x.condition==='petrified';poisoned=poisoned||x.condition==='poisoned';}return !(petrified&&poisoned);}
function diagnostic(budgetPresent,budgetValid,budgetProblem,budget,conditionsPresent,conditionsValid,conditionProblem,exhaustionLevel){return {test:'turn-budget-read',participantId:p.id,present:budgetPresent,valid:budgetValid,problem:budgetProblem,budget:budget,conditionsPresent:conditionsPresent,conditionsValid:conditionsValid,conditionProblem:conditionProblem,exhaustionLevel:exhaustionLevel};}
if(!p)throw new Error('A participant role is required.');
if(!closed(i,[]))throw new Error('Reading turn budget diagnostics requires exactly an empty object input.');
var raw=p.components&&p.components[DEF],state,budgetPresent=!!(p.components&&Object.prototype.hasOwnProperty.call(p.components,DEF)),budgetValid=false,budgetProblem=null,budget=null;
if(!budgetPresent)budgetProblem='absent';else try{state=typeof raw==='string'?JSON.parse(raw):raw;if(valid(state)){budgetValid=true;budget=state;}else budgetProblem='invalid';}catch(error){budgetProblem='malformed';}
var conditionRaw=p.components&&p.components[CONDITIONS],conditionsPresent=!!(p.components&&Object.prototype.hasOwnProperty.call(p.components,CONDITIONS)),conditionsValid=true,conditionProblem=null,exhaustionLevel=0,conditionState,n;
if(conditionsPresent)try{conditionState=typeof conditionRaw==='string'?JSON.parse(conditionRaw):conditionRaw;if(!validConditions(conditionState)){conditionsValid=false;conditionProblem='invalid';}else for(n=0;n<conditionState.entries.length;n++)if(conditionState.entries[n].condition==='exhaustion')exhaustionLevel=conditionState.entries[n].level;}catch(error){conditionsValid=false;conditionProblem='malformed';}
var data=diagnostic(budgetPresent,budgetValid,budgetProblem,budget,conditionsPresent,conditionsValid,conditionProblem,conditionsValid?exhaustionLevel:null);
return {narration:p.name+' has '+(budgetValid?'a valid':'an invalid')+' turn budget and '+(conditionsValid?'a valid':'an invalid')+' condition state.',data:data,effects:[]};
