// Deterministic one-step manual faction-front transition. Governed by procedure.game.core.world.faction.
var front = ctx.roles.front, faction = ctx.roles.faction, location = ctx.roles.location, world = ctx.roles.world;
var frontId = 'game.core.world.faction.front', factionId = 'game.core.world.faction', locationId = 'game.core.world.location', rootId = 'game.core.world.root', clockId = 'game.core.world.clock';
var factionScopeKind = 'game.core.world.faction.in-world', frontScopeKind = 'game.core.world.faction.front.in-world', frontFactionKind = 'game.core.world.faction.front.for-faction', frontContestsKind = 'game.core.world.faction.front.contests';

function closed(value, keys) { if (value === null || Array.isArray(value) || typeof value !== 'object') return false; var actual = Object.keys(value).sort(); if (actual.length !== keys.length) return false; for (var i = 0; i < keys.length; i++) if (actual[i] !== keys[i]) return false; return true; }
function parse(raw, name) { if (typeof raw !== 'string') throw new Error(name + ' is corrupt.'); try { return JSON.parse(raw); } catch (error) { throw new Error(name + ' is corrupt.'); } }
function text(value, maximum) { return typeof value === 'string' && value.length >= 1 && value.trim() === value && Array.from(value).length <= maximum; }
function integer(value, minimum, maximum) { return typeof value === 'number' && Number.isSafeInteger(value) && value >= minimum && value <= maximum; }
function empty(raw, name) { return closed(parse(raw, name), []); }
function edge(value) { return closed(value, ['data', 'fromEntityId', 'kind', 'toEntityId']) && typeof value.data === 'string' && typeof value.fromEntityId === 'string' && typeof value.kind === 'string' && typeof value.toEntityId === 'string'; }
function textList(value, minimum, maximum) { if (!Array.isArray(value) || value.length < minimum || value.length > maximum) return false; for (var i = 0; i < value.length; i++) { if (!text(value[i], 500)) return false; for (var j = 0; j < i; j++) if (value[j] === value[i]) return false; } return true; }
function validFaction(value) { return closed(value, ['agenda', 'assets', 'goals', 'methods', 'status', 'summary', 'visibility']) && value.status === 'active' && text(value.summary, 1000) && (value.visibility === 'public' || value.visibility === 'party' || value.visibility === 'gm') && textList(value.goals, 1, 5) && textList(value.methods, 1, 5) && textList(value.assets, 0, 10) && closed(value.agenda, ['state', 'summary']) && (value.agenda.state === 'ready' || value.agenda.state === 'advanced') && text(value.agenda.summary, 1000); }
function validFront(value) { return closed(value, ['phase', 'phaseStartedMinute', 'status', 'summary', 'visibility']) && (value.status === 'active' || value.status === 'resolved' || value.status === 'archived') && text(value.summary, 1000) && (value.visibility === 'public' || value.visibility === 'party' || value.visibility === 'gm') && (value.phase === 'quiet' || value.phase === 'rising' || value.phase === 'pressing') && integer(value.phaseStartedMinute, 0, 1000000000); }
function validLocation(value) { return closed(value, ['kind', 'status', 'summary', 'visibility']) && (value.kind === 'region' || value.kind === 'settlement' || value.kind === 'site' || value.kind === 'interior') && value.status === 'active' && text(value.summary, 1000) && (value.visibility === 'public' || value.visibility === 'party' || value.visibility === 'gm'); }

if (!closed(ctx.input, ['expectedPhase']) || (ctx.input.expectedPhase !== 'quiet' && ctx.input.expectedPhase !== 'rising')) throw new Error('Front advance input requires exactly expectedPhase quiet or rising.');
if (!front || !faction || !location || !world || !front.components || !faction.components || !location.components || !world.components || !front.components[frontId] || !faction.components[factionId] || !location.components[locationId] || !world.components[rootId] || !world.components[clockId]) throw new Error('Front advance requires front, faction, location, and world roles with their required components.');
var ids = [front.id, faction.id, location.id, world.id]; if (ids.some(function (id) { return typeof id !== 'string' || id.length === 0; }) || new Set(ids).size !== 4) throw new Error('Front advance requires four distinct role entities.');
if (!Array.isArray(front.relationships) || !Array.isArray(faction.relationships)) throw new Error('Front or faction relationship projection is missing.');
var current = parse(front.components[frontId], 'Front state'), factionState = parse(faction.components[factionId], 'Faction state'), locationState = parse(location.components[locationId], 'Location state'), rootState = parse(world.components[rootId], 'World root'), clockState = parse(world.components[clockId], 'World clock');
if (!validFront(current) || !validFaction(factionState) || !validLocation(locationState)) throw new Error('Front, faction, or location state is corrupt or inactive.');
if (!closed(rootState, ['status', 'summary', 'visibility']) || rootState.status !== 'active' || !text(rootState.summary, 1000) || (rootState.visibility !== 'public' && rootState.visibility !== 'party' && rootState.visibility !== 'gm')) throw new Error('World root is invalid or inactive.');
if (!closed(clockState, ['calendarId', 'currentMinute', 'revision']) || !text(clockState.calendarId, 100) || !integer(clockState.currentMinute, 0, 1000000000) || !integer(clockState.revision, 0, 2147483647)) throw new Error('World clock is corrupt.');
if (current.status !== 'active' || current.phase === 'pressing') throw new Error('Front is not advanceable.');
if (ctx.input.expectedPhase !== current.phase) throw new Error('Front expected phase is stale.');

var factionScope = 0;
for (var i = 0; i < faction.relationships.length; i++) { var factionLink = faction.relationships[i]; if (!edge(factionLink)) throw new Error('Faction relationship projection is corrupt.'); if (factionLink.fromEntityId === faction.id && factionLink.kind === factionScopeKind) { if (factionLink.toEntityId !== world.id || !empty(factionLink.data, 'Faction scope data')) throw new Error('Faction root scope is corrupt.'); factionScope++; } }
if (factionScope !== 1) throw new Error('Faction must have exactly one matching root scope.');
var scope = 0, owner = 0, contests = 0;
for (var j = 0; j < front.relationships.length; j++) { var frontLink = front.relationships[j]; if (!edge(frontLink) || frontLink.fromEntityId !== front.id || !empty(frontLink.data, 'Front relationship data')) throw new Error('Front relationship projection is corrupt.'); if (frontLink.kind === frontScopeKind && frontLink.toEntityId === world.id) scope++; else if (frontLink.kind === frontFactionKind && frontLink.toEntityId === faction.id) owner++; else if (frontLink.kind === frontContestsKind && frontLink.toEntityId === location.id) contests++; else throw new Error('Front links do not match the claimed world, faction, and location.'); }
if (scope !== 1 || owner !== 1 || contests !== 1 || front.relationships.length !== 3) throw new Error('Front must have exactly one world, faction, and contested-location link.');
var nextPhase = current.phase === 'quiet' ? 'rising' : 'pressing'; var next = { status: current.status, summary: current.summary, visibility: current.visibility, phase: nextPhase, phaseStartedMinute: clockState.currentMinute };
return { narration: faction.name + ' increases pressure at ' + location.name + '.', effects: [{ type: 'component.set', entityId: front.id, definitionId: frontId, data: JSON.stringify(next) }], data: { test: 'faction-front-advance', frontId: front.id, factionId: faction.id, locationId: location.id, worldId: world.id, previousPhase: current.phase, currentPhase: nextPhase, phaseStartedMinute: clockState.currentMinute } };
