var SID='source.dnd2024.srd-5.2.1',LOC='Playing the Game > Movement and Position > Moving around Other Creatures; Making an Attack > Ranged Attacks in Close Combat',DEF='dnd2024.encounter-sides',e=ctx.roles.encounter,i=ctx.input;
function closed(v,k){if(!v||typeof v!=='object'||Array.isArray(v))return false;var a=Object.keys(v).sort();if(a.length!==k.length)return false;for(var n=0;n<k.length;n++)if(a[n]!==k[n])return false;return true;}
function id(v){return typeof v==='string'&&v.length>0&&v.length<=200&&v===v.trim()&&v===v.toLowerCase();}
function side(v){return typeof v==='string'&&v.length>=6&&v.length<=100&&/^side\.[a-z0-9]+(?:[.-][a-z0-9]+)*$/.test(v);}
function source(v){return closed(v,['locator','sourceId'])&&v.sourceId===SID&&v.locator===LOC;}
function roster(){var all=e&&e.contains;if(!Array.isArray(all))return null;var ids=[],seen={};for(var n=0;n<all.length;n++){var x=all[n];if(!x||x.slot!=='participant'||!id(x.id)||seen[x.id])return null;seen[x.id]=true;ids.push(x.id);}return ids.sort();}
function assignments(v,ids){if(!Array.isArray(v)||v.length!==ids.length)return false;var sides={};for(var n=0;n<v.length;n++){var x=v[n];if(!closed(x,['participantId','sideId'])||x.participantId!==ids[n]||!side(x.sideId))return false;sides[x.sideId]=true;}return sides;}
function pairs(v,sides){if(!Array.isArray(v)||v.length>1000)return false;var seen={},previous='';for(var n=0;n<v.length;n++){var x=v[n];if(!closed(x,['firstSideId','secondSideId'])||!side(x.firstSideId)||!side(x.secondSideId)||x.firstSideId>=x.secondSideId||!sides[x.firstSideId]||!sides[x.secondSideId])return false;var key=x.firstSideId+'\u0000'+x.secondSideId;if(seen[key]||(n&&previous>=key))return false;seen[key]=true;previous=key;}return true;}
function state(v,ids){if(!closed(v,['assignments','hostilePairs','sourceRef'])||!source(v.sourceRef))return false;var sides=assignments(v.assignments,ids);return !!sides&&pairs(v.hostilePairs,sides);}
if(!e||!closed(i,['assignments','hostilePairs','mode'])||(i.mode!=='record'&&i.mode!=='correct'))throw new Error('Encounter sides require exactly mode, assignments, and hostilePairs.');var ids=roster();if(!ids)throw new Error('Encounter participant roster is invalid.');var next={assignments:i.assignments,hostilePairs:i.hostilePairs,sourceRef:{sourceId:SID,locator:LOC}};if(!state(next,ids))throw new Error('Encounter sides must exactly and canonically cover the direct participant roster.');var raw=e.components&&e.components[DEF],current=raw?JSON.parse(raw):null;if(i.mode==='record'&&raw)throw new Error('Encounter sides are already recorded.');if(i.mode==='correct'&&(!raw||!state(current,ids)))throw new Error('Encounter sides must already be valid before correction.');return {narration:e.name+' encounter sides are '+(i.mode==='record'?'recorded.':'corrected.'),data:{test:'encounter-sides-write',encounterId:e.id,mode:i.mode,assignments:next.assignments,hostilePairs:next.hostilePairs,sourceRef:next.sourceRef},effects:[{type:i.mode==='record'?'component.add':'component.set',entityId:e.id,definitionId:DEF,data:JSON.stringify(next)}]};
