var ids={pin:'trail-survival.scenario-pin',run:'trail-survival.run',policy:'trail-survival.policy',pending:'trail-survival.pending-choice',outcome:'trail-survival.outcome',scenario:'trail-survival.scenario'};
function closed(v,k){if(v===null||Array.isArray(v)||typeof v!=='object')return false;var a=Object.keys(v).sort(),b=k.slice().sort();if(a.length!==b.length)return false;for(var i=0;i<b.length;i++)if(a[i]!==b[i])return false;return true;}
function parse(v,n){if(typeof v!=='string')throw new Error(n+' is corrupt.');try{return JSON.parse(v);}catch(e){throw new Error(n+' is corrupt.');}}
function integer(v,min,max){return typeof v==='number'&&Number.isSafeInteger(v)&&v>=min&&v<=max;}
function text(v,max){return typeof v==='string'&&v.length>0&&v.trim()===v&&Array.from(v).length<=max;}
var role=ctx.roles.run;if(!role||!role.components||!role.components[ids.pin]||!role.components[ids.run]||!role.components[ids.policy])throw new Error('Policy selection requires a complete run root.');
if(role.components[ids.pending])throw new Error('Policy selection is blocked by a pending choice.');if(role.components[ids.outcome])throw new Error('Policy selection is blocked on a terminal run.');
if(!closed(ctx.input,['paceId','rationId'])||!text(ctx.input.paceId,100)||!text(ctx.input.rationId,100))throw new Error('Policy input requires exactly paceId and rationId.');
var pin=parse(role.components[ids.pin],'Scenario pin'),run=parse(role.components[ids.run],'Run');if(!closed(run,['partyId','phase','randomSeed','seedCursor','turn'])||run.phase!=='travel'||!integer(run.turn,0,2147483646)||!integer(run.randomSeed,1,4294967295)||!integer(run.seedCursor,0,2147483646))throw new Error('Policy selection requires an active bounded travel run.');
var expected=((run.randomSeed>>>0)^Math.imul(run.seedCursor+1,2654435761))>>>0;if(ctx.seed!==expected)throw new Error('Policy action seed is stale or invalid.');
var reference=ctx.references[pin.scenarioId];if(!reference||!reference.components||!reference.components[ids.scenario])throw new Error('Pinned scenario is unavailable.');var scenario=parse(reference.components[ids.scenario],'Scenario');
if(scenario.scenarioId!==pin.scenarioId||scenario.scenarioVersion!==pin.scenarioVersion||scenario.scenarioContentHash!==pin.scenarioContentHash||scenario.rulesProfileId!==pin.rulesProfileId)throw new Error('Pinned scenario parity failed.');
var pace=false,ration=false;for(var i=0;i<scenario.paces.length;i++)if(scenario.paces[i].paceId===ctx.input.paceId)pace=true;for(var j=0;j<scenario.rations.length;j++)if(scenario.rations[j].rationId===ctx.input.rationId)ration=true;if(!pace||!ration)throw new Error('Policy is not authored by the pinned scenario.');
var nextRun={phase:run.phase,turn:run.turn+1,partyId:run.partyId,randomSeed:run.randomSeed,seedCursor:run.seedCursor+1};
return {narration:'Travel policy updated.',effects:[{type:'component.set',entityId:role.id,definitionId:ids.policy,data:JSON.stringify({paceId:ctx.input.paceId,rationId:ctx.input.rationId})},{type:'component.set',entityId:role.id,definitionId:ids.run,data:JSON.stringify(nextRun)}],events:[],data:{command:'policy.set',paceId:ctx.input.paceId,rationId:ctx.input.rationId,turn:nextRun.turn}};
