var scope=ctx.roles&&ctx.roles.scope,ROOT='game.core.world.root',LOCATION='game.core.world.location',ANCHOR='game.core.world.map.anchor',PAGE=100,MAX=200;
function object(value){return value!==null&&!Array.isArray(value)&&typeof value==='object';}
function text(value,max){return typeof value==='string'&&value.length>0&&value.length<=max&&value===value.trim();}
function parse(raw,label){try{var value=JSON.parse(raw);if(!object(value))throw 0;return value;}catch(error){throw new Error(label+' is malformed.');}}
function record(raw,label,world){var value=parse(raw,label),keys=Object.keys(value).sort().join(',');if(world){if(keys!=='status,summary,visibility')throw new Error(label+' is malformed.');}else if(keys!=='kind,status,summary,visibility')throw new Error(label+' is malformed.');if(!['draft','active','archived'].includes(value.status)||!text(value.summary,1000)||!['public','party','gm'].includes(value.visibility)||!world&&!['region','settlement','site','interior'].includes(value.kind))throw new Error(label+' is malformed.');return value;}
function anchor(raw){if(raw===undefined)return null;var value=parse(raw,'Map anchor');if(Object.keys(value).sort().join(',')!=='x,y'||!Number.isInteger(value.x)||value.x<0||value.x>1000||!Number.isInteger(value.y)||value.y<0||value.y>1000)throw new Error('Map anchor is malformed.');return{x:value.x,y:value.y};}
function visible(value,perspective){return perspective==='dm'||value.visibility!=='gm';}
if(!scope||!object(ctx.input)||Object.keys(ctx.input).sort().join(',')!=='expectedSourceRevision,offset'||![0,100].includes(ctx.input.offset)||!(ctx.input.expectedSourceRevision===null||typeof ctx.input.expectedSourceRevision==='string'&&/^[0-9A-F]{64}$/.test(ctx.input.expectedSourceRevision)))throw new Error('World location scope page requires one exact scope and a supported continuation.');
var perspective=ctx.audience&&ctx.audience.perspective;if(perspective!=='player'&&perspective!=='dm')throw new Error('World location scope page requires an authorized audience.');
var rootRaw=scope.components&&scope.components[ROOT],locationRaw=scope.components&&scope.components[LOCATION];
if(Boolean(rootRaw)===Boolean(locationRaw)||!text(scope.id,200)||!text(scope.name,400))throw new Error('World location scope page requires exactly one World root or location.');
var owner=record(rootRaw||locationRaw,rootRaw?'World root':'World location',Boolean(rootRaw));
if(owner.status==='archived'||!visible(owner,perspective))return{narration:'The requested world scope is unavailable to this audience.',effects:[],events:[],notifications:[],data:{version:1,state:'forbidden',scope:null,locations:[],totalCount:0,complete:true,nextCursor:null}};
var locations=[],seen={},contents=scope.contains||[];if(!Array.isArray(contents)||contents.length>MAX)throw new Error('World location scope exceeds its declared bound.');
for(var i=0;i<contents.length;i++){var child=contents[i],raw=child.components&&child.components[LOCATION];if(raw===undefined)continue;if(!object(child)||!text(child.id,200)||!text(child.name,400)||seen[child.id]||child.deeperContentsOmitted!==undefined&&typeof child.deeperContentsOmitted!=='boolean')throw new Error('World location containment is malformed.');seen[child.id]=true;var item=record(raw,'World location',false);if(item.status==='archived'||!visible(item,perspective))continue;var projected={id:child.id,name:child.name,parentId:scope.id,slot:typeof child.slot==='string'&&child.slot.length<=200?child.slot:'',kind:item.kind,status:item.status,summary:item.summary,visibility:item.visibility,mapAnchor:anchor(child.components&&child.components[ANCHOR])};if(child.deeperContentsOmitted!==true)projected.childScopeKnownEmpty=true;locations.push(projected);}
locations.sort(function(left,right){return left.name.localeCompare(right.name)||left.id.localeCompare(right.id);});
var totalCount=locations.length,start=ctx.input.offset,end=Math.min(start+PAGE,totalCount),page=locations.slice(start,end),next=end<totalCount?String(end):null;
return{narration:'Projected '+page.length+' of '+totalCount+' visible locations in '+scope.name+'.',effects:[],events:[],notifications:[],data:{version:1,state:'ready',scope:{id:scope.id,name:scope.name,parentId:text(scope.containerId,200)?scope.containerId:null,slot:typeof scope.containerSlot==='string'&&scope.containerSlot.length<=200?scope.containerSlot:'',kind:rootRaw?'world':owner.kind,status:owner.status,summary:owner.summary,visibility:owner.visibility,mapAnchor:anchor(scope.components&&scope.components[ANCHOR])},locations:page,totalCount:totalCount,complete:next===null,nextCursor:next}};
