var world=ctx.roles&&ctx.roles.world,ROOT='game.core.world.root',LOCATION='game.core.world.location',MOTIVE='game.core.world.motive',CREATURE='dnd2024.creature.classification',ITEM='dnd2024.core.definition-link',GROUND='game.core.world.conveyance',AIR='game.core.world.aerial-conveyance',PORTAL='game.core.world.teleport-gate',PAGE=50,MAX=2000;
function object(value){return value!==null&&!Array.isArray(value)&&typeof value==='object';}
function text(value,max){return typeof value==='string'&&value.length>0&&value.length<=max&&value===value.trim();}
function parse(raw,label){try{var value=JSON.parse(raw);if(!object(value))throw 0;return value;}catch(error){throw new Error(label+' is malformed.');}}
function closed(value,keys){return Object.keys(value).sort().join(',')===keys.slice().sort().join(',');}
function reference(value){if(!object(value)||!text(value.entityId,200))return false;var keys=Object.keys(value).sort().join(',');return keys==='entityId'||keys==='entityId,expectedArchetype'&&text(value.expectedArchetype,200);}
function rootRecord(raw){var value=parse(raw,'World root');if(!closed(value,['status','summary','visibility'])||!['draft','active','archived'].includes(value.status)||!text(value.summary,1000)||!['public','party','gm'].includes(value.visibility))throw new Error('World root is malformed.');return value;}
function locationRecord(raw){var value=parse(raw,'World location');if(!closed(value,['kind','status','summary','visibility'])||!['region','settlement','site','interior'].includes(value.kind)||!['draft','active','archived'].includes(value.status)||!text(value.summary,1000)||!['public','party','gm'].includes(value.visibility))throw new Error('World location is malformed.');return value;}
function motiveRecord(raw){if(raw===undefined)return null;var value=parse(raw,'World motive');if(!closed(value,['status','summary','visibility'])||!['draft','active','archived'].includes(value.status)||!text(value.summary,1000)||!['public','party','gm'].includes(value.visibility))throw new Error('World motive is malformed.');return value;}
function creatureRecord(raw){if(raw===undefined)return false;var value=parse(raw,'Creature classification');if((!closed(value,['creatureTypeRef','descriptiveTagRefs'])&&!closed(value,['creatureTypeRef','descriptiveTagRefs','alignmentRef']))||!reference(value.creatureTypeRef)||!Array.isArray(value.descriptiveTagRefs)||value.descriptiveTagRefs.length>32||!value.descriptiveTagRefs.every(reference)||(value.alignmentRef!==undefined&&!reference(value.alignmentRef)))throw new Error('Creature classification is malformed.');return true;}
function durableHolding(node){var components=node.components||{},value;if(components[ITEM]!==undefined){value=parse(components[ITEM],'Item definition link');if((!closed(value,['definition'])&&!closed(value,['definition','definitionRevision']))||!reference(value.definition)||(value.definitionRevision!==undefined&&(!Number.isInteger(value.definitionRevision)||value.definitionRevision<1)))throw new Error('Item definition link is malformed.');return'Item';}if(components[GROUND]!==undefined||components[AIR]!==undefined){var type=components[GROUND]!==undefined?GROUND:AIR,label=type===GROUND?'Conveyance':'Aerial conveyance',mode=type===GROUND?'ground':'air';value=parse(components[type],label);if(!closed(value,['status','summary','visibility','travelMode','speedUnitsPerMinute'])||!['active','archived'].includes(value.status)||!text(value.summary,1000)||!['public','party','gm'].includes(value.visibility)||value.travelMode!==mode||!Number.isInteger(value.speedUnitsPerMinute)||value.speedUnitsPerMinute<1||value.speedUnitsPerMinute>10000)throw new Error(label+' is malformed.');return value.status==='archived'?null:label;}if(components[PORTAL]!==undefined){value=parse(components[PORTAL],'Teleport gate');if(!closed(value,['kind','status','summary','visibility'])||value.kind!=='fixed-portal'||!['active','disabled','archived'].includes(value.status)||!text(value.summary,1000)||!['public','party','gm'].includes(value.visibility))throw new Error('Teleport gate is malformed.');return value.status==='archived'?null:'Teleport gate';}return null;}
if(!world||!object(ctx.input)||!closed(ctx.input,['offset','expectedSourceRevision'])||!Number.isInteger(ctx.input.offset)||ctx.input.offset<0||ctx.input.offset>1950||ctx.input.offset%PAGE!==0||!(ctx.input.expectedSourceRevision===null||typeof ctx.input.expectedSourceRevision==='string'&&/^[0-9A-F]{64}$/.test(ctx.input.expectedSourceRevision))||!text(world.id,200)||!text(world.name,400))throw new Error('World people page requires one exact World and valid continuation input.');
var owner=rootRecord(world.components&&world.components[ROOT]),forbidden=!ctx.audience||ctx.audience.perspective!=='dm'||owner.status==='archived';
if(forbidden)return{narration:'The World people and holdings directory is unavailable to this audience.',effects:[],events:[],notifications:[],data:{version:1,state:'forbidden',world:null,locations:[],people:[],holdings:[],totalCount:0,complete:true,nextCursor:null,limits:{contentsDepth:16,recordCount:MAX,pageSize:PAGE,hierarchyComplete:true}}};
var locations=[],people=[],holdings=[],seen={},locationById={},hierarchyComplete=true;
function visit(nodes,parentLocationId,parentIsLocation,path){if(!Array.isArray(nodes))throw new Error('World containment is malformed.');for(var i=0;i<nodes.length;i++){var node=nodes[i];if(!object(node)||!text(node.id,200)||!text(node.name,400)||seen[node.id]||node.deeperContentsOmitted!==undefined&&typeof node.deeperContentsOmitted!=='boolean')throw new Error('World containment is malformed or cyclic.');seen[node.id]=true;if(node.deeperContentsOmitted===true)hierarchyComplete=false;var components=node.components||{},rawLocation=components[LOCATION],locationId=parentLocationId,isLocation=false,nextPath=path;if(rawLocation!==undefined){var location=locationRecord(rawLocation);if(location.status==='archived')continue;var projected={id:node.id,name:node.name,parentId:parentLocationId,kind:location.kind};locations.push(projected);locationById[node.id]=projected;locationId=node.id;isLocation=true;nextPath=path.concat([node.id]);}else if(parentIsLocation){var motive=motiveRecord(components[MOTIVE]),creature=creatureRecord(components[CREATURE]);if(motive&&motive.status==='archived'){}else if(motive||creature){people.push({id:node.id,name:node.name,locationId:parentLocationId,kind:creature?'Creature':'NPC',motive:motive});}else{var kind=durableHolding(node);if(kind)holdings.push({id:node.id,name:node.name,locationId:parentLocationId,kind:kind});}}visit(node.contains===undefined?[]:node.contains,locationId,isLocation,nextPath);}}
visit(world.contains||[],world.id,false,[]);var records=people.map(function(value){return{category:'person',value:value};}).concat(holdings.map(function(value){return{category:'holding',value:value};}));
function order(left,right){return left.value.name.localeCompare(right.value.name)||left.value.id.localeCompare(right.value.id)||left.category.localeCompare(right.category);}records.sort(order);if(records.length>MAX)throw new Error('World people directory exceeds its declared bound.');if(ctx.input.offset>0&&ctx.input.offset>=records.length)throw new Error('World people continuation is outside the current directory.');
var end=Math.min(ctx.input.offset+PAGE,records.length),page=records.slice(ctx.input.offset,end),pagePeople=[],pageHoldings=[],needed={};for(var p=0;p<page.length;p++){var entry=page[p];if(entry.category==='person')pagePeople.push(entry.value);else pageHoldings.push(entry.value);var location=locationById[entry.value.locationId];while(location){needed[location.id]=true;location=location.parentId===world.id?null:locationById[location.parentId];}}
var pageLocations=locations.filter(function(value){return needed[value.id]===true;});pageLocations.sort(function(left,right){return left.name.localeCompare(right.name)||left.id.localeCompare(right.id);});var next=end<records.length?String(end):null;
return{narration:'Projected '+page.length+' of '+records.length+' people and holdings in '+world.name+'.',effects:[],events:[],notifications:[],data:{version:1,state:'ready',world:{id:world.id,name:world.name},locations:pageLocations,people:pagePeople,holdings:pageHoldings,totalCount:records.length,complete:next===null,nextCursor:next,limits:{contentsDepth:16,recordCount:MAX,pageSize:PAGE,hierarchyComplete:hierarchyComplete}}};
