[CmdletBinding()]
param([string]$RepositoryRoot=(Resolve-Path(Join-Path $PSScriptRoot '../../../../..')).Path,[string]$ManifestPath=(Join-Path $PSScriptRoot '../fixtures/slice-10b3b-weapon-item-link-transform.json'))
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
function J($v){$v|ConvertTo-Json -Depth 30 -Compress};function N($v){@($v.PSObject.Properties.Name|Sort-Object)}
function A($v,[string[]]$e,[string]$s){$a=N $v;$w=@($e|Sort-Object);if(($a-join',')-cne($w-join',')){throw "$s shape drift: $($a-join', ')"}}
function P([string]$r,[string]$p){$root=[IO.Path]::GetFullPath($r).TrimEnd([IO.Path]::DirectorySeparatorChar);$full=[IO.Path]::GetFullPath((Join-Path $root $p));if(-not$full.StartsWith($root+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw "Path escape: $p"};$full}
$root=[IO.Path]::GetFullPath($RepositoryRoot);$m=Get-Content -Raw ([IO.Path]::GetFullPath($ManifestPath))|ConvertFrom-Json -Depth 30
A $m @('format','cohort','sourceRevision','officialSource','license','entries') 'Manifest';if($m.cohort-cne'slice-10b3b-weapon-item-links'){throw 'Unexpected cohort.'}
if($m.officialSource.sourceId-cne'source.dnd2024.srd-5.2.1'-or$m.officialSource.locator-cne'Equipment > Weapons'){throw 'Source binding drift.'};if($m.license.classification-cne'CC-BY-4.0'-or[string]::IsNullOrWhiteSpace($m.license.attribution)-or[string]::IsNullOrWhiteSpace($m.license.changes)){throw 'Attribution required.'}
$ids=@('item.dnd2024.dagger.v1','item.dnd2024.flail.v1','item.dnd2024.greatsword.v1','item.dnd2024.javelin.v1');if(@($m.entries).Count-ne4-or(@($m.entries.id|Sort-Object)-join',')-cne(($ids|Sort-Object)-join',')){throw 'Incomplete link cohort.'}
$seen=@{};$results=@();foreach($e in @($m.entries)){A $e @('id','profileId','sourcePath','sourceSha256','targetPath') $e.id;if($seen[$e.id]){throw "Duplicate: $($e.id)"};$seen[$e.id]=1;$sp=P $root $e.sourcePath;$tp=P $root $e.targetPath;if((Get-FileHash $sp -Algorithm SHA256).Hash.ToUpperInvariant()-cne$e.sourceSha256){throw "Hash drift: $($e.id)"};$s=Get-Content -Raw $sp|ConvertFrom-Json -Depth 30;$t=Get-Content -Raw $tp|ConvertFrom-Json -Depth 30;A $s @('id','name','components') $e.id;A $s.components @('dnd2024.item-definition') "$($e.id) components";$d=$s.components.'dnd2024.item-definition';if($s.id-cne$e.id-or$d.kind-cne'weapon'-or$d.weaponProfileId-cne$e.profileId-or$d.sourceRef.locator-cne'Equipment > Weapons'){throw "Meaning drift: $($e.id)"};if((J $s)-cne(J $t)){throw "Target drift: $($e.id)"};$profile=P $root "catalog/applications/dnd2024/content/entities/weapons/$($e.profileId).json";if(-not(Test-Path $profile -PathType Leaf)){throw "Missing target profile: $($e.profileId)"};$results+=[ordered]@{id=$e.id;profileId=$e.profileId;targetSha256=(Get-FileHash $tp -Algorithm SHA256).Hash.ToUpperInvariant()}}
[ordered]@{format='dnd2024-static-content-transform-report/v1';cohort=$m.cohort;status='verified';candidateCount=$results.Count;candidates=$results}|ConvertTo-Json -Depth 10
