[CmdletBinding()]
param([string]$RepositoryRoot=(Resolve-Path(Join-Path $PSScriptRoot '../../../../..')).Path,[string]$ManifestPath=(Join-Path $PSScriptRoot '../fixtures/slice-10f-fighter-progression-transform.json'))
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
function J($v){$v|ConvertTo-Json -Depth 30 -Compress};function N($v){@($v.PSObject.Properties.Name|Sort-Object)}
function A($v,[string[]]$e,[string]$s){$a=N $v;$w=@($e|Sort-Object);if(($a-join',')-cne($w-join',')){throw "$s shape drift: $($a-join', ')"}}
function P([string]$r,[string]$p){$root=[IO.Path]::GetFullPath($r).TrimEnd([IO.Path]::DirectorySeparatorChar);$full=[IO.Path]::GetFullPath((Join-Path $root $p));if(-not$full.StartsWith($root+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw "Path escape: $p"};$full}
$root=[IO.Path]::GetFullPath($RepositoryRoot);$m=Get-Content -Raw ([IO.Path]::GetFullPath($ManifestPath))|ConvertFrom-Json -Depth 30
A $m @('format','cohort','sourceRevision','officialSource','license','entries') 'Manifest';if($m.cohort-cne'slice-10f-fighter-progression'){throw 'Unexpected cohort.'}
$locator='Classes > Fighter, PDF pages 47–48';if($m.officialSource.sourceId-cne'source.dnd2024.srd-5.2.1'-or$m.officialSource.locator-cne$locator){throw 'Source binding drift.'};if($m.license.classification-cne'CC-BY-4.0'-or[string]::IsNullOrWhiteSpace($m.license.attribution)-or[string]::IsNullOrWhiteSpace($m.license.changes)){throw 'Attribution required.'}
$ids=@('content.dnd2024.class.fighter.v1','content.dnd2024.feature.fighter.action-surge.v1','content.dnd2024.feature.fighter.fighting-style.v1','content.dnd2024.feature.fighter.second-wind.v1','content.dnd2024.feature.fighter.tactical-mind.v1','content.dnd2024.feature.fighter.weapon-mastery.v1');if(@($m.entries).Count-ne6-or(@($m.entries.id|Sort-Object)-join',')-cne(($ids|Sort-Object)-join',')){throw 'Incomplete Fighter cohort.'}
$seen=@{};$targets=@{};$results=@();foreach($e in @($m.entries)){A $e @('id','sourcePath','sourceSha256','targetPath') $e.id;if($seen[$e.id]){throw "Duplicate: $($e.id)"};$seen[$e.id]=1;$sp=P $root $e.sourcePath;$tp=P $root $e.targetPath;if((Get-FileHash $sp -Algorithm SHA256).Hash.ToUpperInvariant()-cne$e.sourceSha256){throw "Hash drift: $($e.id)"};$s=Get-Content -Raw $sp|ConvertFrom-Json -Depth 30;$t=Get-Content -Raw $tp|ConvertFrom-Json -Depth 30;if((J $s)-cne(J $t)){throw "Target drift: $($e.id)"};$definition=$t.components.'dnd2024.character.content-definition';if($t.id-cne$e.id-or$definition.status-cne'active'-or$definition.sourceRef.sourceId-cne'source.dnd2024.srd-5.2.1'-or$definition.sourceRef.locator-cne$locator){throw "Meaning drift: $($e.id)"};$targets[$e.id]=$t;$results+=[ordered]@{id=$e.id;targetSha256=(Get-FileHash $tp -Algorithm SHA256).Hash.ToUpperInvariant()}}
$class=$targets['content.dnd2024.class.fighter.v1'];$progression=$class.components.'dnd2024.class-progression';if(@($class.components.PSObject.Properties).Count-ne2-or$progression.hitDieSides-ne10-or$progression.fixedHitPointGainBeforeConstitution-ne6-or@($progression.levels).Count-ne2-or$progression.sourceRef.locator-cne$locator){throw 'Fighter progression drift.'}
$level1=@('content.dnd2024.feature.fighter.fighting-style.v1','content.dnd2024.feature.fighter.second-wind.v1','content.dnd2024.feature.fighter.weapon-mastery.v1');$level2=@('content.dnd2024.feature.fighter.action-surge.v1','content.dnd2024.feature.fighter.tactical-mind.v1');if((@($progression.levels[0].featureDefinitionIds)-join',')-cne($level1-join',')-or(@($progression.levels[1].featureDefinitionIds)-join',')-cne($level2-join',')){throw 'Feature entitlement drift.'};foreach($id in @($level1+$level2)){if(-not$targets.ContainsKey($id)-or$targets[$id].components.'dnd2024.character.content-definition'.kind-cne'feature'){throw "Unclosed feature reference: $id"}}
[ordered]@{format='dnd2024-static-content-transform-report/v1';cohort=$m.cohort;status='verified';candidateCount=$results.Count;candidates=$results}|ConvertTo-Json -Depth 10
