var DEF='dnd2024.creature.defenses',SID='source.dnd2024.srd-5.2.1',LOC='Playing the Game > Damage and Healing > Resistance and Vulnerability; Immunity (PDF p. 17)',ORDER=['acid','bludgeoning','cold','fire','force','lightning','necrotic','piercing','poison','psychic','radiant','slashing','thunder'],RESPONSE={resistance:'dnd2024.vocabulary.damage-response.resistance',immunity:'dnd2024.vocabulary.damage-response.immunity',vulnerability:'dnd2024.vocabulary.damage-response.vulnerability'},s=ctx.roles.subject,i=ctx.input;
function closed(v,keys){if(!v||typeof v!=='object'||Array.isArray(v))return false;var actual=Object.keys(v).sort(),expected=keys.slice().sort(),n;if(actual.length!==expected.length)return false;for(n=0;n<expected.length;n++)if(actual[n]!==expected[n])return false;return true;}
function canonical(v){if(!Array.isArray(v)||v.length>ORDER.length)return null;var seen={},result=[],n,type;for(n=0;n<v.length;n++){type=v[n];if(ORDER.indexOf(type)<0||seen[type])return null;seen[type]=true;result.push(type);}result.sort(function(a,b){return ORDER.indexOf(a)-ORDER.indexOf(b);});return result;}
function ordered(v){var normalized=canonical(v),n;if(!normalized||normalized.length!==v.length)return false;for(n=0;n<v.length;n++)if(v[n]!==normalized[n])return false;return true;}
function source(v){return v&&v.entityId===SID;}
function legacy(v){var result={resistances:[],immunities:[],vulnerabilities:[]};if(!v||!Array.isArray(v.damageResponses))return result;for(var n=0;n<v.damageResponses.length;n++){var entry=v.damageResponses[n],damageType=entry.damageTypeRef.entityId.replace('dnd2024.vocabulary.damage-type.','');if(entry.responseRef.entityId===RESPONSE.resistance)result.resistances.push(damageType);else if(entry.responseRef.entityId===RESPONSE.immunity)result.immunities.push(damageType);else if(entry.responseRef.entityId===RESPONSE.vulnerability)result.vulnerabilities.push(damageType);}return result;}
function valid(v){if(!v||typeof v!=='object'||Array.isArray(v)||!Array.isArray(v.damageResponses))return false;var keys=['damageResponses'];if(Object.prototype.hasOwnProperty.call(v,'armorClassSource'))keys.push('armorClassSource');if(!closed(v,keys))return false;if(v.armorClassSource!==undefined&&(!v.armorClassSource||typeof v.armorClassSource.entityId!=='string'))return false;var previous='',seen={};for(var n=0;n<v.damageResponses.length;n++){var entry=v.damageResponses[n],entryKeys=['damageTypeRef','responseRef','sourceRef'];if(entry&&Object.prototype.hasOwnProperty.call(entry,'qualifyingRuleRef'))entryKeys.push('qualifyingRuleRef');if(!closed(entry,entryKeys)||!entry.damageTypeRef||typeof entry.damageTypeRef.entityId!=='string'||!entry.responseRef||typeof entry.responseRef.entityId!=='string'||!entry.sourceRef||!source(entry.sourceRef)||entry.qualifyingRuleRef!==undefined&&(!entry.qualifyingRuleRef||typeof entry.qualifyingRuleRef.entityId!=='string'))return false;var key=entry.damageTypeRef.entityId+'\n'+entry.responseRef.entityId;if(seen[key]||key<previous)return false;seen[key]=true;previous=key;}return true;}
function parse(raw){try{return typeof raw==='string'?JSON.parse(raw):raw;}catch(error){throw new Error('The existing creature-defenses component is malformed.');}}
if(!s)throw new Error('A subject role is required.');
if(!closed(i,['mode','resistances','immunities','vulnerabilities'])||(i.mode!=='record'&&i.mode!=='correct'))throw new Error('Input must contain exactly record/correct mode and complete resistance, immunity, and vulnerability lists.');
var resistances=canonical(i.resistances),immunities=canonical(i.immunities),vulnerabilities=canonical(i.vulnerabilities);if(!resistances||!immunities||!vulnerabilities)throw new Error('Each mitigation list must contain only unique canonical D&D 2024 damage types.');
var present=!!(s.components&&Object.prototype.hasOwnProperty.call(s.components,DEF)),previous=null;if(present){previous=parse(s.components[DEF]);if(!valid(previous))throw new Error('The existing creature-defenses component is invalid and cannot be corrected.');}
if(i.mode==='record'&&present)throw new Error('Creature defenses are already recorded. Use correct mode.');if(i.mode==='correct'&&!present)throw new Error('Creature defenses are absent. Use record mode.');
var next={damageResponses:[]};if(previous&&previous.armorClassSource)next.armorClassSource=previous.armorClassSource;function add(types,response){for(var n=0;n<types.length;n++)next.damageResponses.push({damageTypeRef:{entityId:'dnd2024.vocabulary.damage-type.'+types[n]},responseRef:{entityId:RESPONSE[response]},sourceRef:{entityId:SID}});}add(resistances,'resistance');add(immunities,'immunity');add(vulnerabilities,'vulnerability');next.damageResponses.sort(function(a,b){var ak=a.damageTypeRef.entityId+'\n'+a.responseRef.entityId,bk=b.damageTypeRef.entityId+'\n'+b.responseRef.entityId;return ak<bk?-1:(ak>bk?1:0);});
return {narration:s.name+' damage mitigation is '+(i.mode==='record'?'recorded.':'corrected.'),data:{mode:i.mode,resistances:resistances,immunities:immunities,vulnerabilities:vulnerabilities,previous:previous?legacy(previous):null,sourceRef:{sourceId:SID,locator:LOC}},effects:[{type:i.mode==='record'?'component.add':'component.set',entityId:s.id,definitionId:DEF,data:JSON.stringify(next)}],events:[],notifications:[]};
