var t=ctx.roles.turn,i=ctx.input,TURN='dnd2024.encounter.turn',BUDGET='dnd2024.combat.turn-budget',MAX=9007199254740991;
function closed(v,k){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length!==k.length)return false;for(var n=0;n<k.length;n++)if(!Object.prototype.hasOwnProperty.call(v,k[n]))return false;return true;}
function id(v){return typeof v==='string'&&v.length>0&&v.length<=200&&v===v.trim();}
function integer(v,min,max){return typeof v==='number'&&isFinite(v)&&Math.floor(v)===v&&v>=min&&v<=max;}
function ref(v){return closed(v,['entityId'])&&id(v.entityId);}
function distance(v){return closed(v,['dimension','value','unit'])&&v.dimension==='distance'&&closed(v.value,['numerator','denominator'])&&integer(v.value.numerator,0,MAX)&&integer(v.value.denominator,1,MAX)&&closed(v.unit,['entityId'])&&v.unit.entityId==='dnd2024.vocabulary.distance-unit.meter';}
function validTurn(v){return closed(v,['encounter','round','participant','ordinal','status'])&&ref(v.encounter)&&ref(v.round)&&ref(v.participant)&&integer(v.ordinal,0,99)&&(['pending','active','complete','skipped'].indexOf(v.status)>=0);}
function validBudget(v){if(!closed(v,['turn','remaining','movementSpent','interactionsUsed'])||!ref(v.turn)||v.turn.entityId!==t.id||!closed(v.remaining,['actions','bonusActions','reactions'])||!integer(v.remaining.actions,0,100)||!integer(v.remaining.bonusActions,0,100)||!integer(v.remaining.reactions,0,100)||!Array.isArray(v.movementSpent)||v.movementSpent.length>100||!integer(v.interactionsUsed,0,100))return false;for(var n=0;n<v.movementSpent.length;n++){var x=v.movementSpent[n];if(!closed(x,['mode','distance'])||!ref(x.mode)||!distance(x.distance))return false;}return true;}
if(!t||!closed(i,[]))throw new Error('Reading turn-budget diagnostics requires a turn and exactly empty input.');var turnRaw=t.components&&t.components[TURN],budgetRaw=t.components&&t.components[BUDGET],turnPresent=Object.prototype.hasOwnProperty.call(t.components||{},TURN),budgetPresent=Object.prototype.hasOwnProperty.call(t.components||{},BUDGET),turn=null,budget=null,turnValid=false,budgetValid=false,turnProblem=turnPresent?null:'absent',budgetProblem=budgetPresent?null:'absent';if(turnPresent)try{turn=typeof turnRaw==='string'?JSON.parse(turnRaw):turnRaw;if(validTurn(turn))turnValid=true;else turnProblem='invalid';}catch(error){turnProblem='malformed';}if(budgetPresent)try{budget=typeof budgetRaw==='string'?JSON.parse(budgetRaw):budgetRaw;if(validBudget(budget))budgetValid=true;else budgetProblem='invalid';}catch(error){budgetProblem='malformed';}return {narration:t.name+' has '+(budgetValid?'a valid':'an invalid')+' counted turn budget.',data:{test:'turn-budget-read',turnId:t.id,turnPresent:turnPresent,turnValid:turnValid,turnProblem:turnProblem,turn:turnValid?turn:null,present:budgetPresent,valid:budgetValid,problem:budgetProblem,budget:budgetValid?budget:null},effects:[],events:[],notifications:[]};
