var SID='source.dnd2024.srd-5.2.1',LOC='Rules Glossary > Speed',DEF='dnd2024.creature.movement',MODES=['walk','burrow','climb','fly','swim'],s=ctx.roles.subject,i=ctx.input;
function closed(v,keys){if(!v||typeof v!=='object'||Array.isArray(v))return false;var a=Object.keys(v);if(a.length!==keys.length)return false;for(var n=0;n<keys.length;n++)if(!Object.prototype.hasOwnProperty.call(v,keys[n]))return false;return true;}
function rational(v){return closed(v,['numerator','denominator'])&&Number.isSafeInteger(v.numerator)&&v.numerator>=0&&Number.isSafeInteger(v.denominator)&&v.denominator>0;}
function validDistance(v){return closed(v,['dimension','value','unit'])&&v.dimension==='distance'&&rational(v.value)&&closed(v.unit,['entityId'])&&v.unit.entityId==='dnd2024.vocabulary.distance-unit.meter';}
function valid(v){if(!closed(v,['speeds'])||!v.speeds||typeof v.speeds!=='object')return false;for(var n=0;n<MODES.length;n++){var id='dnd2024.vocabulary.movement-mode.'+MODES[n],entry=v.speeds[id];if(!entry||!closed(entry,['distance','enabled','sourceRefs'])||!validDistance(entry.distance)||typeof entry.enabled!=='boolean'||!Array.isArray(entry.sourceRefs)||entry.sourceRefs.length<1) return false;for(var sourceIndex=0;sourceIndex<entry.sourceRefs.length;sourceIndex++)if(!closed(entry.sourceRefs[sourceIndex],['entityId'])||entry.sourceRefs[sourceIndex].entityId!==SID)return false;}var walk=v.speeds['dnd2024.vocabulary.movement-mode.walk'];return walk.enabled===true&&walk.distance.value.numerator*1250%(walk.distance.value.denominator*381)===0&&walk.distance.value.numerator*1250/(walk.distance.value.denominator*381)>=5&&walk.distance.value.numerator*1250/(walk.distance.value.denominator*381)%5===0;}
if(!s)throw new Error('A subject role is required.');
if(!closed(i,[]))throw new Error('Reading creature Speed diagnostics requires exactly an empty object input.');
var raw=s.components&&s.components[DEF],state;
if(!raw)return {narration:s.name+' has no Speed.',data:{test:'speed-read',subjectId:s.id,present:false,valid:false,problem:'absent',speed:null},effects:[],events:[],notifications:[]};
try{state=typeof raw==='string'?JSON.parse(raw):raw;}catch(error){return {narration:s.name+' has malformed Speed.',data:{test:'speed-read',subjectId:s.id,present:true,valid:false,problem:'malformed',speed:null},effects:[],events:[],notifications:[]};}
if(!valid(state))return {narration:s.name+' has invalid Speed.',data:{test:'speed-read',subjectId:s.id,present:true,valid:false,problem:'invalid',speed:null},effects:[],events:[],notifications:[]};
var legacySpeed={walkFeet:0,burrowFeet:0,climbFeet:0,flyFeet:0,swimFeet:0,sourceRef:{sourceId:SID,locator:LOC}};for(var modeIndex=0;modeIndex<MODES.length;modeIndex++){var mode=MODES[modeIndex],entry=state.speeds['dnd2024.vocabulary.movement-mode.'+mode],numerator=entry.distance.value.numerator,denominator=entry.distance.value.denominator,feet=numerator*1250/(denominator*381);if(!Number.isSafeInteger(feet))return {narration:s.name+' has invalid Speed.',data:{test:'speed-read',subjectId:s.id,present:true,valid:false,problem:'invalid',speed:null},effects:[],events:[],notifications:[]};legacySpeed[mode+'Feet']=feet;}
return {narration:s.name+' has valid Speed.',data:{test:'speed-read',subjectId:s.id,present:true,valid:true,problem:null,speed:legacySpeed},effects:[],events:[],notifications:[]};
