var ids={pin:'trail-survival.scenario-pin',run:'trail-survival.run',clock:'trail-survival.clock',route:'trail-survival.route-progress',policy:'trail-survival.policy',pending:'trail-survival.pending-choice',outcome:'trail-survival.outcome',scenario:'trail-survival.scenario',party:'trail-survival.party',resources:'trail-survival.resources',member:'trail-survival.member',conveyance:'trail-survival.conveyance'};
function closed(v,k){if(v===null||Array.isArray(v)||typeof v!=='object')return false;var a=Object.keys(v).sort(),b=k.slice().sort();if(a.length!==b.length)return false;for(var i=0;i<b.length;i++)if(a[i]!==b[i])return false;return true;}
function parse(v,n){if(typeof v!=='string')throw new Error(n+' is corrupt.');try{return JSON.parse(v);}catch(e){throw new Error(n+' is corrupt.');}}
function integer(v,min,max){return typeof v==='number'&&Number.isSafeInteger(v)&&v>=min&&v<=max;}
function text(v,max){return typeof v==='string'&&v.length>0&&v.trim()===v&&Array.from(v).length<=max;}
function nodeWith(nodes,id){for(var i=0;i<(nodes||[]).length;i++)if(nodes[i].components&&nodes[i].components[id])return nodes[i];return null;}
var role=ctx.roles.run;if(!role||!role.components||!role.components[ids.pin]||!role.components[ids.run]||!role.components[ids.clock]||!role.components[ids.route]||!role.components[ids.policy])throw new Error('Travel requires a complete run root.');if(role.components[ids.pending])throw new Error('Travel is blocked by a pending choice.');if(role.components[ids.outcome])throw new Error('Travel is blocked on a terminal run.');if(!closed(ctx.input,['legId'])||!(ctx.input.legId===null||text(ctx.input.legId,100)))throw new Error('Travel input requires exactly a legId string or null.');
var pin=parse(role.components[ids.pin],'Scenario pin'),run=parse(role.components[ids.run],'Run'),clock=parse(role.components[ids.clock],'Clock'),route=parse(role.components[ids.route],'Route progress'),policy=parse(role.components[ids.policy],'Policy');if(!closed(run,['partyId','phase','randomSeed','seedCursor','turn'])||run.phase!=='travel'||!integer(run.turn,0,2147483646)||!integer(run.randomSeed,1,4294967295)||!integer(run.seedCursor,0,2147483646)||!closed(clock,['elapsedMinutes'])||!integer(clock.elapsedMinutes,0,1000000000))throw new Error('Travel requires an active bounded run.');var expected=((run.randomSeed>>>0)^Math.imul(run.seedCursor+1,2654435761))>>>0;if(ctx.seed!==expected)throw new Error('Travel action seed is stale or invalid.');
var reference=ctx.references[pin.scenarioId];if(!reference||!reference.components||!reference.components[ids.scenario])throw new Error('Pinned scenario is unavailable.');var scenario=parse(reference.components[ids.scenario],'Scenario');if(scenario.scenarioId!==pin.scenarioId||scenario.scenarioVersion!==pin.scenarioVersion||scenario.scenarioContentHash!==pin.scenarioContentHash||scenario.rulesProfileId!==pin.rulesProfileId||route.routeId!==scenario.routeId)throw new Error('Pinned scenario parity failed.');
var pace=null,ration=null;for(var p=0;p<scenario.paces.length;p++)if(scenario.paces[p].paceId===policy.paceId)pace=scenario.paces[p];for(var q=0;q<scenario.rations.length;q++)if(scenario.rations[q].rationId===policy.rationId)ration=scenario.rations[q];if(!pace||!ration)throw new Error('Canonical policy is unavailable in the scenario.');if(clock.elapsedMinutes>1000000000-pace.minutesPerTurn)throw new Error('Travel time exceeds the supported bound.');
var leg=null;if(route.activeLegId===null){if(ctx.input.legId===null)throw new Error('Travel must select an outgoing leg at a landmark.');for(var l=0;l<scenario.routeLegs.length;l++)if(scenario.routeLegs[l].legId===ctx.input.legId&&scenario.routeLegs[l].fromLandmarkId===route.currentLandmarkId)leg=scenario.routeLegs[l];if(!leg)throw new Error('Selected leg is not an authored outgoing leg.');}else{if(ctx.input.legId!==null)throw new Error('Travel must continue the canonical active leg with null legId.');for(var a=0;a<scenario.routeLegs.length;a++)if(scenario.routeLegs[a].legId===route.activeLegId)leg=scenario.routeLegs[a];if(!leg||leg.fromLandmarkId!==route.currentLandmarkId||route.distanceIntoLeg<0||route.distanceIntoLeg>=leg.distance)throw new Error('Canonical active leg is invalid.');}
var partyNode=nodeWith(role.contains,ids.party),conveyanceNode=partyNode&&nodeWith(partyNode.contains,ids.conveyance);if(!partyNode||!partyNode.components[ids.resources]||!conveyanceNode)throw new Error('Travel party state is unavailable.');var resources=parse(partyNode.components[ids.resources],'Resources'),conveyance=parse(conveyanceNode.components[ids.conveyance],'Conveyance');if(conveyance.status!=='operational'||conveyance.condition<1)throw new Error('Travel requires an operational conveyance.');var memberNodes=[],living=[];for(var n=0;n<(partyNode.contains||[]).length;n++)if(partyNode.contains[n].components&&partyNode.contains[n].components[ids.member]){var mv=parse(partyNode.contains[n].components[ids.member],'Member');memberNodes.push({node:partyNode.contains[n],value:mv});if(mv.status!=='dead'&&mv.status!=='departed')living.push({node:partyNode.contains[n],value:mv});}if(living.length<1)throw new Error('Travel requires at least one living member.');
var foodCost=ration.foodPerMember*living.length;if(!Number.isSafeInteger(foodCost)||foodCost>1000000000)throw new Error('Travel food cost exceeds the supported bound.');var nextEntries=resources.entries.map(function(v){return {resourceId:v.resourceId,quantity:v.quantity};}),food=null;for(var e=0;e<nextEntries.length;e++)if(nextEntries[e].resourceId===scenario.foodResourceId)food=nextEntries[e];if(!food||food.quantity<foodCost)throw new Error('Travel food is insufficient.');food.quantity-=foodCost;
var effects=[{type:'component.set',entityId:partyNode.id,definitionId:ids.resources,data:JSON.stringify({entries:nextEntries})}],alive=0;for(var m=0;m<living.length;m++){var member=living[m].value,nextHealth=Math.max(0,Math.min(scenario.memberMaxHealth,member.healthPoints+ration.healthDelta)),nextStatus=nextHealth===0?'dead':(member.status==='incapacitated'?'incapacitated':'active'),nextMember={name:member.name,roleId:member.roleId,status:nextStatus,healthPoints:nextHealth,conditionIds:member.conditionIds};if(nextHealth>0)alive++;effects.push({type:'component.set',entityId:living[m].node.id,definitionId:ids.member,data:JSON.stringify(nextMember)});}
var nextCondition=Math.max(0,conveyance.condition-pace.conveyanceWear),nextConveyance={kindId:conveyance.kindId,status:nextCondition===0?'lost':'operational',condition:nextCondition,maximumCondition:conveyance.maximumCondition,cargoCapacity:conveyance.cargoCapacity};effects.push({type:'component.set',entityId:conveyanceNode.id,definitionId:ids.conveyance,data:JSON.stringify(nextConveyance)});
var moved=Math.min(pace.distancePerTurn,leg.distance-route.distanceIntoLeg),distance=route.distanceIntoLeg+moved,arrived=distance===leg.distance,visited=route.visitedLandmarkIds.slice(),nextRoute;if(arrived){if(visited.indexOf(leg.toLandmarkId)<0)visited.push(leg.toLandmarkId);nextRoute={routeId:route.routeId,currentLandmarkId:leg.toLandmarkId,activeLegId:null,distanceIntoLeg:0,visitedLandmarkIds:visited};}else nextRoute={routeId:route.routeId,currentLandmarkId:route.currentLandmarkId,activeLegId:leg.legId,distanceIntoLeg:distance,visitedLandmarkIds:visited};
var turn=run.turn+1,terminal=null;if(alive===0)terminal={kind:'defeat',causeId:scenario.outcomes.partyDefeatCauseId,reachedTurn:turn};else if(nextCondition===0)terminal={kind:'defeat',causeId:scenario.outcomes.conveyanceDefeatCauseId,reachedTurn:turn};else if(arrived&&leg.toLandmarkId===scenario.finalLandmarkId)terminal={kind:'victory',causeId:scenario.outcomes.victoryCauseId,reachedTurn:turn};
var pending=null;if(!terminal&&scenario.events.length>0&&ctx.randomInt(1,10000)<=pace.eventChancePer10000){var totalWeight=0;for(var w=0;w<scenario.events.length;w++){totalWeight+=scenario.events[w].weight;if(!Number.isSafeInteger(totalWeight)||totalWeight>1000000000)throw new Error('Scenario event weights exceed the supported bound.');}var draw=ctx.randomInt(1,totalWeight),running=0,selected=null;for(var d=0;d<scenario.events.length;d++){running+=scenario.events[d].weight;if(selected===null&&draw<=running)selected=scenario.events[d];}pending={eventId:selected.eventId,choiceIds:selected.choices.map(function(v){return v.choiceId;}),openedTurn:turn};}
var nextClock={elapsedMinutes:clock.elapsedMinutes+pace.minutesPerTurn},nextRun={phase:terminal?'finished':'travel',turn:turn,partyId:run.partyId,randomSeed:run.randomSeed,seedCursor:run.seedCursor+1};effects.push({type:'component.set',entityId:role.id,definitionId:ids.clock,data:JSON.stringify(nextClock)});effects.push({type:'component.set',entityId:role.id,definitionId:ids.route,data:JSON.stringify(nextRoute)});effects.push({type:'component.set',entityId:role.id,definitionId:ids.run,data:JSON.stringify(nextRun)});if(pending)effects.push({type:'component.add',entityId:role.id,definitionId:ids.pending,data:JSON.stringify(pending)});if(terminal)effects.push({type:'component.add',entityId:role.id,definitionId:ids.outcome,data:JSON.stringify(terminal)});return {narration:terminal?(terminal.kind==='victory'?'The party reaches its destination.':'The journey ends in defeat.'):(pending?'Travel opens an event choice.':(arrived?'The party reaches a landmark.':'The party continues along the trail.')),effects:effects,events:[],data:{command:'travel',legId:leg.legId,moved:moved,arrived:arrived,currentLandmarkId:nextRoute.currentLandmarkId,pendingEventId:pending?pending.eventId:null,outcome:terminal?terminal.kind:null,turn:turn}};
