// <auto-generated />
using System;
using DantesRoleplay.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DantesRoleplay.DataAccess.Migrations
{
    [DbContext(typeof(DantesRoleplayDbContext))]
    [Migration("20260821133903_StoryPlanRuns")]
    partial class StoryPlanRuns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("DantesRoleplay.Events.EventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Id");

                    b.HasIndex("EventId", "Ordinal")
                        .IsUnique();

                    b.ToTable("event_entity", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.Events.EventExecution", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EffectCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElapsedMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("LimitHit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MechanicId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MechanicVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Narration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SubscriptionVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("EventId", "Ordinal")
                        .IsUnique();

                    b.ToTable("event_execution", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.Events.EventRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CausationId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProducerExecutionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RootOperationId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RootOperationId");

                    b.HasIndex("CorrelationId", "Sequence");

                    b.HasIndex("TypeId", "Timestamp");

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.Events.EventType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Scope");

                    b.HasIndex("Status");

                    b.ToTable("event_type", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.Events.EventTypeVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventTypeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadSchema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId", "Version")
                        .IsUnique();

                    b.ToTable("event_type_version", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.Events.Subscription", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Scope");

                    b.HasIndex("Status");

                    b.ToTable("subscription", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.Events.SubscriptionVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventMechanicId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventTypeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FixedRoleEntityIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxExecutionsPerChain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadEqualsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackedEntityIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventMechanicId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("Mode", "Order");

                    b.HasIndex("SubscriptionId", "Version")
                        .IsUnique();

                    b.ToTable("subscription_version", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.Mechanics.Mechanic", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Scope");

                    b.HasIndex("Status");

                    b.ToTable("mechanic", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.Mechanics.MechanicVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Matches")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MechanicId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MechanicId", "Version")
                        .IsUnique();

                    b.ToTable("mechanic_version", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.Notifications.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootOperationId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId", "Ordinal");

                    b.HasIndex("State", "CreatedAt");

                    b.HasIndex("Topic", "CreatedAt");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.Notifications.NotificationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Id");

                    b.HasIndex("NotificationId", "Ordinal")
                        .IsUnique();

                    b.ToTable("notification_entity", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.Operations.Operation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConsumedReadEvidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuardEvidenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MechanicId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MechanicVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProceduresCited")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProceduresRead")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Subject");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Tool", "Timestamp");

                    b.ToTable("operation", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.Procedures.ProcedureContract", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Status");

                    b.ToTable("procedure_contract", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.Procedures.ProcedureContractVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Constraints")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Governs")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContractId", "Version")
                        .IsUnique();

                    b.ToTable("procedure_contract_version", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.Snapshots.SnapshotPackage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BoundaryFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ContentDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentEncoding")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DigestAlgorithm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProducerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProducerVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootOperationId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeContractId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScopeContractVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("snapshot_package", null, t =>
                        {
                            t.HasCheckConstraint("CK_snapshot_package_availability", "\"Availability\" = 'available'");

                            t.HasCheckConstraint("CK_snapshot_package_boundary_fingerprint", "length(\"BoundaryFingerprint\") = 64 AND \"BoundaryFingerprint\" NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_snapshot_package_byte_count", "\"ByteCount\" BETWEEN 1 AND 1048576 AND \"ByteCount\" = length(\"Content\")");

                            t.HasCheckConstraint("CK_snapshot_package_content_digest", "length(\"ContentDigest\") = 64 AND \"ContentDigest\" NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_snapshot_package_digest_algorithm", "\"DigestAlgorithm\" = 'sha256'");

                            t.HasCheckConstraint("CK_snapshot_package_encoding", "\"ContentEncoding\" = 'dantes-canonical-json-v1'");

                            t.HasCheckConstraint("CK_snapshot_package_id", "length(\"Id\") = 41 AND substr(\"Id\", 1, 9) = 'snapshot.' AND substr(\"Id\", 10) NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_snapshot_package_producer_version", "\"ProducerVersion\" > 0");

                            t.HasCheckConstraint("CK_snapshot_package_root_operation", "length(\"RootOperationId\") = 32 AND \"RootOperationId\" NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_snapshot_package_scope_version", "\"ScopeContractVersion\" > 0");
                        });
                });

            modelBuilder.Entity("DantesRoleplay.Story.StoryPlanRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(43)
                        .HasColumnType("TEXT");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedStepCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HandoffJson")
                        .HasMaxLength(32000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaseUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("NextStepIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyRevision")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StopCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StopMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestToken")
                        .IsUnique();

                    b.HasIndex("Status", "LeaseUntilUtc", "UpdatedAtUtc");

                    b.ToTable("story_plan_run", null, t =>
                        {
                            t.HasCheckConstraint("CK_story_plan_run_id", "length(\"Id\") = 43 AND substr(\"Id\", 1, 11) = 'story-plan.' AND substr(\"Id\", 12) NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_story_plan_run_revision", "\"Revision\" > 0");

                            t.HasCheckConstraint("CK_story_plan_run_status", "\"Status\" IN ('pending', 'running', 'completed', 'blocked', 'failed', 'cancelled')");

                            t.HasCheckConstraint("CK_story_plan_run_step_counts", "\"NextStepIndex\" >= 0 AND \"CompletedStepCount\" >= 0");
                        });
                });

            modelBuilder.Entity("DantesRoleplay.Story.StoryPlanStepRun", b =>
                {
                    b.Property<string>("StoryPlanId")
                        .HasMaxLength(43)
                        .HasColumnType("TEXT");

                    b.Property<int>("StepIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionOperationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MechanicId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MechanicVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcedureEvidenceJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasMaxLength(32000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleEntityIdsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("StoryPlanId", "StepIndex");

                    b.ToTable("story_plan_step_run", null, t =>
                        {
                            t.HasCheckConstraint("CK_story_plan_step_run_index", "\"StepIndex\" BETWEEN 0 AND 5");

                            t.HasCheckConstraint("CK_story_plan_step_run_kind", "\"Kind\" IN ('campaign-context', 'knowledge', 'action')");

                            t.HasCheckConstraint("CK_story_plan_step_run_status", "\"Status\" IN ('pending', 'running', 'completed', 'blocked', 'failed', 'skipped')");
                        });
                });

            modelBuilder.Entity("DantesRoleplay.SystemFeedback.SystemFeedbackDisposition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(53)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(41)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId", "Revision")
                        .IsUnique();

                    b.HasIndex("ToState", "CreatedAt", "Id");

                    b.ToTable("system_feedback_disposition", null, t =>
                        {
                            t.HasCheckConstraint("CK_system_feedback_disposition_changed", "\"FromState\" <> \"ToState\"");

                            t.HasCheckConstraint("CK_system_feedback_disposition_from", "\"FromState\" IN ('Open', 'Acknowledged', 'Resolved', 'Dismissed')");

                            t.HasCheckConstraint("CK_system_feedback_disposition_id", "length(\"Id\") = 53 AND substr(\"Id\", 1, 21) = 'feedback-disposition.' AND substr(\"Id\", 22) NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_system_feedback_disposition_revision", "\"Revision\" > 0");

                            t.HasCheckConstraint("CK_system_feedback_disposition_to", "\"ToState\" IN ('Open', 'Acknowledged', 'Resolved', 'Dismissed')");
                        });
                });

            modelBuilder.Entity("DantesRoleplay.SystemFeedback.SystemFeedbackOperationReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(41)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("ReportId", "OperationId")
                        .IsUnique();

                    b.HasIndex("ReportId", "Ordinal")
                        .IsUnique();

                    b.ToTable("system_feedback_operation", null, t =>
                        {
                            t.HasCheckConstraint("CK_system_feedback_operation_ordinal", "\"Ordinal\" BETWEEN 0 AND 7");
                        });
                });

            modelBuilder.Entity("DantesRoleplay.SystemFeedback.SystemFeedbackProcedureReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcedureId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcedureVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(41)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcedureId", "ProcedureVersion");

                    b.HasIndex("ReportId", "Ordinal")
                        .IsUnique();

                    b.HasIndex("ReportId", "ProcedureId")
                        .IsUnique();

                    b.ToTable("system_feedback_procedure", null, t =>
                        {
                            t.HasCheckConstraint("CK_system_feedback_procedure_ordinal", "\"Ordinal\" BETWEEN 0 AND 7");
                        });
                });

            modelBuilder.Entity("DantesRoleplay.SystemFeedback.SystemFeedbackReport", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(41)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Expected")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoldState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("None");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observed")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestToken")
                        .IsRequired()
                        .HasMaxLength(49)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionRevision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionOperationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TriageRevision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("RequestToken")
                        .IsUnique();

                    b.HasIndex("Category", "CreatedAt", "Id");

                    b.HasIndex("Impact", "CreatedAt", "Id");

                    b.HasIndex("State", "CreatedAt", "Id");

                    b.HasIndex("HoldState", "State", "CreatedAt", "Id");

                    b.HasIndex("ArchivedAt", "State", "Category", "CreatedAt", "Id");

                    b.ToTable("system_feedback_report", null, t =>
                        {
                            t.HasCheckConstraint("CK_system_feedback_report_category", "\"Category\" IN ('Defect', 'Friction', 'Documentation', 'Suggestion', 'Positive')");

                            t.HasCheckConstraint("CK_system_feedback_report_fingerprint", "length(\"PayloadFingerprint\") = 64 AND \"PayloadFingerprint\" NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_system_feedback_report_hold_state", "\"HoldState\" IN ('None', 'Held')");

                            t.HasCheckConstraint("CK_system_feedback_report_id", "length(\"Id\") = 41 AND substr(\"Id\", 1, 9) = 'feedback.' AND substr(\"Id\", 10) NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_system_feedback_report_impact", "\"Impact\" IN ('Blocked', 'Degraded', 'Minor', 'None')");

                            t.HasCheckConstraint("CK_system_feedback_report_operation", "length(\"SubmissionOperationId\") = 32 AND \"SubmissionOperationId\" NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_system_feedback_report_retention_revision", "\"RetentionRevision\" >= 0");

                            t.HasCheckConstraint("CK_system_feedback_report_state", "\"State\" IN ('Open', 'Acknowledged', 'Resolved', 'Dismissed')");

                            t.HasCheckConstraint("CK_system_feedback_report_token", "length(\"RequestToken\") = 49 AND substr(\"RequestToken\", 1, 17) = 'feedback-request.' AND substr(\"RequestToken\", 18) NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_system_feedback_report_triage_revision", "\"TriageRevision\" >= 0");
                        });
                });

            modelBuilder.Entity("DantesRoleplay.SystemFeedback.SystemFeedbackRetentionAction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(51)
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveAsOf")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FromArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromHoldState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(41)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ToArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToHoldState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId", "Revision")
                        .IsUnique();

                    b.HasIndex("Action", "CreatedAt", "Id");

                    b.ToTable("system_feedback_retention_action", null, t =>
                        {
                            t.HasCheckConstraint("CK_system_feedback_retention_action_action", "\"Action\" IN ('Archive', 'Restore', 'PlaceHold', 'ReleaseHold')");

                            t.HasCheckConstraint("CK_system_feedback_retention_action_changed", "(\"FromArchived\" <> \"ToArchived\") <> (\"FromHoldState\" <> \"ToHoldState\")");

                            t.HasCheckConstraint("CK_system_feedback_retention_action_effective_as_of", "(\"Action\" = 'Archive' AND \"EffectiveAsOf\" IS NOT NULL) OR (\"Action\" <> 'Archive' AND \"EffectiveAsOf\" IS NULL)");

                            t.HasCheckConstraint("CK_system_feedback_retention_action_from_hold", "\"FromHoldState\" IN ('None', 'Held')");

                            t.HasCheckConstraint("CK_system_feedback_retention_action_id", "length(\"Id\") = 51 AND substr(\"Id\", 1, 19) = 'feedback-retention.' AND substr(\"Id\", 20) NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_system_feedback_retention_action_reference", "(\"Action\" IN ('PlaceHold', 'ReleaseHold') AND \"Reference\" IS NOT NULL AND length(\"Reference\") BETWEEN 1 AND 100) OR (\"Action\" IN ('Archive', 'Restore') AND \"Reference\" IS NULL)");

                            t.HasCheckConstraint("CK_system_feedback_retention_action_revision", "\"Revision\" > 0");

                            t.HasCheckConstraint("CK_system_feedback_retention_action_to_hold", "\"ToHoldState\" IN ('None', 'Held')");
                        });
                });

            modelBuilder.Entity("DantesRoleplay.SystemFeedback.SystemFeedbackStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(41)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId", "Ordinal")
                        .IsUnique();

                    b.ToTable("system_feedback_step", null, t =>
                        {
                            t.HasCheckConstraint("CK_system_feedback_step_ordinal", "\"Ordinal\" BETWEEN 0 AND 7");
                        });
                });

            modelBuilder.Entity("DantesRoleplay.World.Component", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId");

                    b.HasIndex("EntityId", "DefinitionId")
                        .IsUnique();

                    b.ToTable("component", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.World.ComponentDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("component_definition", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.World.Containment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainedId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainedId")
                        .IsUnique();

                    b.HasIndex("ContainerId");

                    b.ToTable("containment", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.World.Entity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("Name");

                    b.ToTable("entity", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.World.Relationship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromEntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToEntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ToEntityId");

                    b.HasIndex("FromEntityId", "ToEntityId", "Kind")
                        .IsUnique();

                    b.ToTable("relationship", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.Events.EventEntity", b =>
                {
                    b.HasOne("DantesRoleplay.Events.EventRecord", "Event")
                        .WithMany("Entities")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DantesRoleplay.Events.EventExecution", b =>
                {
                    b.HasOne("DantesRoleplay.Events.EventRecord", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DantesRoleplay.Events.EventTypeVersion", b =>
                {
                    b.HasOne("DantesRoleplay.Events.EventType", "EventType")
                        .WithMany("Versions")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("DantesRoleplay.Events.SubscriptionVersion", b =>
                {
                    b.HasOne("DantesRoleplay.Events.Subscription", "Subscription")
                        .WithMany("Versions")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("DantesRoleplay.Mechanics.MechanicVersion", b =>
                {
                    b.HasOne("DantesRoleplay.Mechanics.Mechanic", "Mechanic")
                        .WithMany("Versions")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mechanic");
                });

            modelBuilder.Entity("DantesRoleplay.Notifications.NotificationEntity", b =>
                {
                    b.HasOne("DantesRoleplay.Notifications.Notification", "Notification")
                        .WithMany("Entities")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("DantesRoleplay.Procedures.ProcedureContractVersion", b =>
                {
                    b.HasOne("DantesRoleplay.Procedures.ProcedureContract", "Contract")
                        .WithMany("Versions")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("DantesRoleplay.Story.StoryPlanStepRun", b =>
                {
                    b.HasOne("DantesRoleplay.Story.StoryPlanRun", "StoryPlan")
                        .WithMany("Steps")
                        .HasForeignKey("StoryPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StoryPlan");
                });

            modelBuilder.Entity("DantesRoleplay.SystemFeedback.SystemFeedbackDisposition", b =>
                {
                    b.HasOne("DantesRoleplay.SystemFeedback.SystemFeedbackReport", "Report")
                        .WithMany("Dispositions")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("DantesRoleplay.SystemFeedback.SystemFeedbackOperationReference", b =>
                {
                    b.HasOne("DantesRoleplay.SystemFeedback.SystemFeedbackReport", "Report")
                        .WithMany("OperationReferences")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("DantesRoleplay.SystemFeedback.SystemFeedbackProcedureReference", b =>
                {
                    b.HasOne("DantesRoleplay.SystemFeedback.SystemFeedbackReport", "Report")
                        .WithMany("ProcedureReferences")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("DantesRoleplay.SystemFeedback.SystemFeedbackRetentionAction", b =>
                {
                    b.HasOne("DantesRoleplay.SystemFeedback.SystemFeedbackReport", "Report")
                        .WithMany("RetentionActions")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("DantesRoleplay.SystemFeedback.SystemFeedbackStep", b =>
                {
                    b.HasOne("DantesRoleplay.SystemFeedback.SystemFeedbackReport", "Report")
                        .WithMany("Steps")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("DantesRoleplay.World.Component", b =>
                {
                    b.HasOne("DantesRoleplay.World.ComponentDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DantesRoleplay.World.Entity", "Entity")
                        .WithMany("Components")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("DantesRoleplay.World.Containment", b =>
                {
                    b.HasOne("DantesRoleplay.World.Entity", "Contained")
                        .WithMany()
                        .HasForeignKey("ContainedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DantesRoleplay.World.Entity", "Container")
                        .WithMany()
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contained");

                    b.Navigation("Container");
                });

            modelBuilder.Entity("DantesRoleplay.World.Relationship", b =>
                {
                    b.HasOne("DantesRoleplay.World.Entity", "FromEntity")
                        .WithMany()
                        .HasForeignKey("FromEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DantesRoleplay.World.Entity", "ToEntity")
                        .WithMany()
                        .HasForeignKey("ToEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromEntity");

                    b.Navigation("ToEntity");
                });

            modelBuilder.Entity("DantesRoleplay.Events.EventRecord", b =>
                {
                    b.Navigation("Entities");
                });

            modelBuilder.Entity("DantesRoleplay.Events.EventType", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("DantesRoleplay.Events.Subscription", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("DantesRoleplay.Mechanics.Mechanic", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("DantesRoleplay.Notifications.Notification", b =>
                {
                    b.Navigation("Entities");
                });

            modelBuilder.Entity("DantesRoleplay.Procedures.ProcedureContract", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("DantesRoleplay.Story.StoryPlanRun", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("DantesRoleplay.SystemFeedback.SystemFeedbackReport", b =>
                {
                    b.Navigation("Dispositions");

                    b.Navigation("OperationReferences");

                    b.Navigation("ProcedureReferences");

                    b.Navigation("RetentionActions");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("DantesRoleplay.World.Entity", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
