var SID='source.dnd2024.srd-5.2.1',LOC='Playing the Game > Damage and Healing',CLOC='Rules Glossary',MITIGATION='dnd2024.damage-mitigation',CONDITIONS='dnd2024.conditions',TYPES=['acid','bludgeoning','cold','fire','force','lightning','necrotic','piercing','poison','psychic','radiant','slashing','thunder'],CONDITION_ORDER=['blinded','charmed','deafened','frightened','grappled','incapacitated','invisible','paralyzed','petrified','poisoned','prone','restrained','stunned','unconscious','exhaustion'],d=ctx.roles.defender,i=ctx.input;
function closed(v,keys){if(!v||typeof v!=='object'||Array.isArray(v))return false;var a=Object.keys(v),n;if(a.length!==keys.length)return false;for(n=0;n<keys.length;n++)if(!Object.prototype.hasOwnProperty.call(v,keys[n]))return false;return true;}
function source(v,locator){return closed(v,['sourceId','locator'])&&v.sourceId===SID&&v.locator===locator;}
function orderedTypes(v){if(!Array.isArray(v)||v.length>TYPES.length)return false;var previous=-1,n,index;for(n=0;n<v.length;n++){index=TYPES.indexOf(v[n]);if(index<=previous)return false;previous=index;}return true;}
function validMitigation(v){return closed(v,['resistances','immunities','vulnerabilities','sourceRef'])&&orderedTypes(v.resistances)&&orderedTypes(v.immunities)&&orderedTypes(v.vulnerabilities)&&source(v.sourceRef,LOC);}
function id(v){return typeof v==='string'&&v.length>0&&v.length<=200&&v===v.trim();}
function entry(v){if(!v||typeof v!=='object'||Array.isArray(v)||typeof v.condition!=='string')return false;if(v.condition==='exhaustion')return closed(v,['condition','level'])&&typeof v.level==='number'&&isFinite(v.level)&&Math.floor(v.level)===v.level&&v.level>=1&&v.level<=6;return (closed(v,['condition'])||closed(v,['condition','sourceEntityId']))&&CONDITION_ORDER.indexOf(v.condition)>=0&&(!Object.prototype.hasOwnProperty.call(v,'sourceEntityId')||id(v.sourceEntityId));}
function conditionKey(v){return v.condition+'\u0000'+(Object.prototype.hasOwnProperty.call(v,'sourceEntityId')?v.sourceEntityId:'');}
function compare(a,b){var order=CONDITION_ORDER.indexOf(a.condition)-CONDITION_ORDER.indexOf(b.condition);if(order!==0)return order;var as=Object.prototype.hasOwnProperty.call(a,'sourceEntityId')?a.sourceEntityId:null,bs=Object.prototype.hasOwnProperty.call(b,'sourceEntityId')?b.sourceEntityId:null;if(as===null)return bs===null?0:-1;if(bs===null)return 1;return as<bs?-1:as>bs?1:0;}
function validConditions(v){if(!closed(v,['entries','sourceRef'])||!Array.isArray(v.entries)||v.entries.length>100||!source(v.sourceRef,CLOC))return false;var seen={},petrified=false,poisoned=false,n,x;for(n=0;n<v.entries.length;n++){x=v.entries[n];if(!entry(x)||seen[conditionKey(x)]||(n>0&&compare(v.entries[n-1],x)>=0))return false;seen[conditionKey(x)]=true;petrified=petrified||x.condition==='petrified';poisoned=poisoned||x.condition==='poisoned';}return !(petrified&&poisoned);}
function parse(raw,label){try{return typeof raw==='string'?JSON.parse(raw):raw;}catch(error){throw new Error('The stored '+label+' state is malformed.');}}
if(!d)throw new Error('A defender role is required.');
if(!closed(i,[]))throw new Error('Reading damage mitigation requires exactly an empty object input.');
var mitigationRaw=d.components&&d.components[MITIGATION],mitigationKnown=!!(d.components&&Object.prototype.hasOwnProperty.call(d.components,MITIGATION)),mitigation={resistances:[],immunities:[],vulnerabilities:[]};
if(mitigationKnown){mitigation=parse(mitigationRaw,'damage-mitigation');if(!validMitigation(mitigation))throw new Error('The stored damage-mitigation state is invalid.');}
var conditionRaw=d.components&&d.components[CONDITIONS],conditionsKnown=!!(d.components&&Object.prototype.hasOwnProperty.call(d.components,CONDITIONS)),entries=[];
if(conditionsKnown){var conditions=parse(conditionRaw,'condition');if(!validConditions(conditions))throw new Error('The stored condition state is invalid.');entries=conditions.entries;}
var petrified=false,n;for(n=0;n<entries.length;n++)if(entries[n].condition==='petrified')petrified=true;
return {narration:d.name+' has '+(mitigationKnown?'known':'unknown')+' stored damage mitigation.',data:{test:'damage-mitigation-profile',defenderId:d.id,mitigationKnown:mitigationKnown,conditionsKnown:conditionsKnown,immunities:mitigation.immunities,resistances:mitigation.resistances,vulnerabilities:mitigation.vulnerabilities,petrified:petrified,sourceRef:{sourceId:SID,locator:LOC}},effects:[]};
