[CmdletBinding()]
param(
    [ValidateSet('4A', '4B', '4C')][string]$Stage = '4C',
    [string]$NpxCommand = 'npx'
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$repo = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..\..\..')).Path
$conformance = Join-Path $repo 'ruleset/dnd2024/adoption/conformance'
$contracts = Join-Path $conformance 'contracts'
$fixtures = Join-Path $conformance 'fixtures'
$converter = Join-Path $PSScriptRoot 'Convert-ConformanceVectors.ps1'
$runner = Join-Path $PSScriptRoot 'Invoke-Conformance.ps1'
$temporary = Join-Path ([IO.Path]::GetTempPath()) ('dantesroleplay-conformance-' + [guid]::NewGuid().ToString('N'))
[IO.Directory]::CreateDirectory($temporary) | Out-Null

function Invoke-Ajv { param([string[]]$Arguments) $output=@(& $NpxCommand --yes ajv-cli@5.0.0 @Arguments 2>&1|ForEach-Object{"$_"});return [pscustomobject]@{exitCode=$LASTEXITCODE;output=$output} }
function Require-AjvSuccess { param([string[]]$Arguments,[string]$Message) $result=Invoke-Ajv $Arguments;if($result.exitCode -ne 0){throw "${Message}: $($result.output -join [Environment]::NewLine)"} }
function Set-JsonPointer { param($Root,[string]$Pointer,$Value) $segments=@($Pointer.TrimStart('/').Split('/')|ForEach-Object{$_.Replace('~1','/').Replace('~0','~')});$cursor=$Root;for($i=0;$i -lt $segments.Count-1;$i++){$segment=$segments[$i];if($cursor -is [System.Array]){$cursor=$cursor[[int]$segment]}else{$property=$cursor.PSObject.Properties[$segment];if($null -eq $property){throw "Pointer does not resolve: $Pointer"};$cursor=$property.Value}};$last=$segments[-1];if($cursor -is [System.Array]){$cursor[[int]$last]=$Value}else{$property=$cursor.PSObject.Properties[$last];if($null -eq $property){$cursor|Add-Member -NotePropertyName $last -NotePropertyValue $Value}else{$property.Value=$Value}} }
function Invoke-ExpectedFailure { param([scriptblock]$Action,[string]$Name) $failed=$false;try{& $Action}catch{$failed=$true};if(-not $failed){throw "Expected failure did not occur: $Name"} }
function Run-Converter { param([string]$SourcePath,[string]$Prefix) $scenario=Join-Path $temporary "$Prefix.scenario.json";$observation=Join-Path $temporary "$Prefix.observation.json";& $converter -InputPath $SourcePath -ScenarioOutputPath $scenario -ObservationOutputPath $observation|Out-Null;return [pscustomobject]@{scenario=$scenario;observation=$observation} }
function Run-Runner { param([string[]]$Arguments) & pwsh -NoProfile -File $runner @Arguments 2>$null | Out-Null; return $LASTEXITCODE }

try {
    $scenarioSchema=Join-Path $contracts 'conformance-scenario.schema.json'
    Require-AjvSuccess @('compile','--spec=draft2020','--strict=false','-s',$scenarioSchema) 'Scenario schema compilation failed'
    $scenarioFixture=Join-Path $fixtures 'neutral-scenarios.valid.json'
    Require-AjvSuccess @('validate','--spec=draft2020','--strict=false','-s',$scenarioSchema,'-d',$scenarioFixture) 'Scenario positive validation failed'
    $invalid=Get-Content -Raw (Join-Path $fixtures 'neutral-scenarios.invalid-cases.json')|ConvertFrom-Json -Depth 100
    foreach($case in $invalid.cases){$document=Get-Content -Raw $scenarioFixture|ConvertFrom-Json -Depth 100;foreach($mutation in $case.mutations){Set-JsonPointer $document $mutation.pointer $mutation.value};$path=Join-Path $temporary ('invalid-' + [guid]::NewGuid().ToString('N') + '.json');[IO.File]::WriteAllText($path,($document|ConvertTo-Json -Depth 100),[Text.UTF8Encoding]::new($false));$result=Invoke-Ajv @('validate','--spec=draft2020','--strict=false','-s',$scenarioSchema,'-d',$path);if($result.exitCode -eq 0){throw "Scenario negative validation unexpectedly succeeded: $($case.name)"}}
    $negativeCount=@($invalid.cases).Count
    if($Stage -eq '4A'){[ordered]@{format='application-adoption-conformance-tooling-test/v1';stage='4A';schemaCompilations=1;positiveDocuments=1;negativeDocuments=$negativeCount}|ConvertTo-Json;return}

    $sourceSchema=Join-Path $contracts 'source-vector.schema.json';$observationSchema=Join-Path $contracts 'conformance-observation.schema.json'
    Require-AjvSuccess @('compile','--spec=draft2020','--strict=false','-s',$sourceSchema,'-r',$scenarioSchema) 'Source-vector schema compilation failed'
    Require-AjvSuccess @('compile','--spec=draft2020','--strict=false','-s',$observationSchema,'-r',$scenarioSchema) 'Observation schema compilation failed'
    $converted=@{};foreach($fixtureName in @('archive-ability-check.source-vectors.json','donor-ability-check.source-vectors.json','adapted-ability-check.source-vectors.json')){$fixturePath=Join-Path $fixtures $fixtureName;Require-AjvSuccess @('validate','--spec=draft2020','--strict=false','-s',$sourceSchema,'-r',$scenarioSchema,'-d',$fixturePath) "Source-vector validation failed for $fixtureName";$prefix=[IO.Path]::GetFileNameWithoutExtension($fixtureName);$first=Run-Converter $fixturePath ($prefix+'-first');$second=Run-Converter $fixturePath ($prefix+'-second');if((Get-FileHash $first.scenario -Algorithm SHA256).Hash -cne (Get-FileHash $second.scenario -Algorithm SHA256).Hash -or (Get-FileHash $first.observation -Algorithm SHA256).Hash -cne (Get-FileHash $second.observation -Algorithm SHA256).Hash){throw "Conversion was not deterministic: $fixtureName"};Require-AjvSuccess @('validate','--spec=draft2020','--strict=false','-s',$scenarioSchema,'-d',$first.scenario) "Converted scenario validation failed for $fixtureName";Require-AjvSuccess @('validate','--spec=draft2020','--strict=false','-s',$observationSchema,'-r',$scenarioSchema,'-d',$first.observation) "Converted observation validation failed for $fixtureName";$converted[$fixtureName]=$first}
    $donor=Get-Content -Raw $converted['donor-ability-check.source-vectors.json'].observation|ConvertFrom-Json -Depth 100;if($donor.source.revision -ne 'ead852b19b9e45f54f43e193caf4f10aad91a91b' -or $donor.source.path -ne 'src/derive/ability-check.ts'){throw 'Donor provenance was not retained.'}
    $badSource=Join-Path $temporary 'missing-pointer.source-vectors.json';$badText=(Get-Content -Raw (Join-Path $fixtures 'archive-ability-check.source-vectors.json')).Replace('/data/total','/data/missing');[IO.File]::WriteAllText($badSource,$badText,[Text.UTF8Encoding]::new($false));Invoke-ExpectedFailure { Run-Converter $badSource 'bad'|Out-Null } 'unresolved result pointer'
    if($Stage -eq '4B'){[ordered]@{format='application-adoption-conformance-tooling-test/v1';stage='4B';schemaCompilations=3;convertedSources=$converted.Count;negativeDocuments=$negativeCount;deterministicConversions=$converted.Count;provenance='retained'}|ConvertTo-Json;return}

    $differenceSchema=Join-Path $contracts 'intentional-difference.schema.json';Require-AjvSuccess @('compile','--spec=draft2020','--strict=false','-s',$differenceSchema,'-r',$scenarioSchema) 'Difference schema compilation failed';$differenceFixture=Join-Path $fixtures 'declared-difference.example.json';Require-AjvSuccess @('validate','--spec=draft2020','--strict=false','-s',$differenceSchema,'-r',$scenarioSchema,'-d',$differenceFixture) 'Difference fixture validation failed'
    $archive=$converted['archive-ability-check.source-vectors.json'];$adapted=$converted['adapted-ability-check.source-vectors.json'];$report1=Join-Path $temporary 'passed-1.report.json';$report2=Join-Path $temporary 'passed-2.report.json';if((Run-Runner @('-ScenarioPath',$archive.scenario,'-ReferenceObservationPath',$archive.observation,'-CandidateObservationPath',$adapted.observation,'-ReportPath',$report1)) -ne 0){throw 'Equal conformance comparison failed.'};if((Run-Runner @('-ScenarioPath',$archive.scenario,'-ReferenceObservationPath',$archive.observation,'-CandidateObservationPath',$adapted.observation,'-ReportPath',$report2)) -ne 0){throw 'Repeated equal comparison failed.'};if((Get-FileHash $report1 -Algorithm SHA256).Hash -cne (Get-FileHash $report2 -Algorithm SHA256).Hash){throw 'Conformance report was not deterministic.'};if((Run-Runner @('-ScenarioPath',$archive.scenario,'-ReferenceObservationPath',$archive.observation,'-CandidateObservationPath',$adapted.observation,'-IntentionalDifferencePath',$differenceFixture,'-ReportPath',(Join-Path $temporary 'stale-declaration.report.json'))) -eq 0){throw 'A declaration without an observed mismatch was accepted.'}
    $changed=Join-Path $temporary 'changed.observation.json';$changedText=(Get-Content -Raw $adapted.observation).Replace('"total": 15','"total": 16');[IO.File]::WriteAllText($changed,$changedText,[Text.UTF8Encoding]::new($false));$blockedReport=Join-Path $temporary 'blocked.report.json';if((Run-Runner @('-ScenarioPath',$archive.scenario,'-ReferenceObservationPath',$archive.observation,'-CandidateObservationPath',$changed,'-ReportPath',$blockedReport)) -eq 0){throw 'Unexpected difference did not block.'};$blocked=Get-Content -Raw $blockedReport|ConvertFrom-Json -Depth 100;if($blocked.status -ne 'blocked' -or @($blocked.comparisons|Where-Object status -eq 'blocked').Count -ne 1){throw 'Unexpected-difference report was incomplete.'}
    $declaredReport=Join-Path $temporary 'declared.report.json';if((Run-Runner @('-ScenarioPath',$archive.scenario,'-ReferenceObservationPath',$archive.observation,'-CandidateObservationPath',$changed,'-IntentionalDifferencePath',$differenceFixture,'-ReportPath',$declaredReport)) -eq 0){throw 'Declared intentional difference was incorrectly accepted.'};$declared=Get-Content -Raw $declaredReport|ConvertFrom-Json -Depth 100;if(@($declared.comparisons|Where-Object status -eq 'requires-confirmation').Count -ne 1){throw 'Declared intentional difference did not require confirmation.'}
    [ordered]@{format='application-adoption-conformance-tooling-test/v1';stage='4C';schemaCompilations=4;convertedSources=$converted.Count;negativeDocuments=$negativeCount;deterministicConversions=$converted.Count;deterministicReports=1;equalComparison='passed';unexpectedDifference='blocked';declaredDifference='requires-confirmation'}|ConvertTo-Json
}
finally { if(Test-Path -LiteralPath $temporary){Remove-Item -LiteralPath $temporary -Recurse -Force} }
