var s=ctx.roles.subject,w=ctx.roles.weapon,t=ctx.roles.target,i=ctx.input,SID='source.dnd2024.srd-5.2.1',HLOC='Playing the Game > Damage and Healing > Hit Points',TLOC='Playing the Game > Damage and Healing > Temporary Hit Points (PDF p. 18)',MLOC='Playing the Game > Damage and Healing > Resistance and Vulnerability; Immunity (PDF p. 17)',PLOC='Rules Glossary > Petrified > Resist Damage (PDF p. 186)',EP='dnd2024.rest-episode',LINK='rest.world',SHORTLOC='Rules Glossary > Short Rest, PDF page 187',LONGLOC='Rules Glossary > Long Rest, PDF page 185',TYPES=['acid','bludgeoning','cold','fire','force','lightning','necrotic','piercing','poison','psychic','radiant','slashing','thunder'],MAX=9007199254740991,RESTMAX=1000000000;
function closed(v,k){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length!==k.length)return false;for(var x=0;x<k.length;x++)if(!Object.prototype.hasOwnProperty.call(v,k[x]))return false;return true;}
function parse(raw,label){try{return typeof raw==='string'?JSON.parse(raw):raw;}catch(error){throw new Error(label+' is corrupt.');}}
function safe(v,min){return typeof v==='number'&&isFinite(v)&&Math.floor(v)===v&&v>=min&&v<=MAX;}
function restInteger(v,min,max){return typeof v==='number'&&Number.isSafeInteger(v)&&v>=min&&v<=max;}
function text(v,max){return typeof v==='string'&&v.length>0&&v===v.trim()&&Array.from(v).length<=max;}
function source(v,loc){return closed(v,['sourceId','locator'])&&v.sourceId===SID&&v.locator===loc;}
function entitySource(v){return closed(v,['entityId'])&&v.entityId===SID;}
function validHp(v){if(!v||typeof v!=='object'||Array.isArray(v))return false;var keys=Object.keys(v).sort(),expected=Object.prototype.hasOwnProperty.call(v,'maximumReduction')?['current','maximum','maximumReduction']:['current','maximum'];return JSON.stringify(keys)===JSON.stringify(expected)&&safe(v.current,0)&&safe(v.maximum,1)&&v.current<=v.maximum&&(!Object.prototype.hasOwnProperty.call(v,'maximumReduction')||safe(v.maximumReduction,0));}
function ordered(v){if(!Array.isArray(v)||v.length>TYPES.length)return false;var previous=-1,n,index;for(n=0;n<v.length;n++){index=TYPES.indexOf(v[n]);if(index<=previous)return false;previous=index;}return true;}
function has(v,x){return v.indexOf(x)>=0;}
function validEpisode(v){if(!v||v.policyEntityId!=='content.dnd2024.rest-policy.standard.v1'||!text(v.worldId,200)||!restInteger(v.startedAtMinute,0,RESTMAX)||!restInteger(v.observedAtMinute,v.startedAtMinute,RESTMAX)||!restInteger(v.observedClockRevision,0,2147483647)||(v.status!=='active'&&v.status!=='ready'))return false;var elapsed=v.observedAtMinute-v.startedAtMinute;if(v.kind==='short'){if(!closed(v,['policyEntityId','kind','worldId','startedAtMinute','observedAtMinute','observedClockRevision','requiredMinutes','lightActivityMinutes','status','sourceRef'])||v.requiredMinutes!==60||!restInteger(v.lightActivityMinutes,0,RESTMAX)||v.lightActivityMinutes!==elapsed||!source(v.sourceRef,SHORTLOC))return false;return (v.status==='ready')===(v.lightActivityMinutes>=v.requiredMinutes);}if(v.kind==='long'){if(!closed(v,['policyEntityId','kind','worldId','startedAtMinute','observedAtMinute','observedClockRevision','requiredMinutes','sleepMinutes','lightActivityMinutes','interruptionCount','status','sourceRef'])||!restInteger(v.sleepMinutes,0,RESTMAX)||!restInteger(v.lightActivityMinutes,0,120)||!restInteger(v.interruptionCount,0,16666658)||v.requiredMinutes!==480+60*v.interruptionCount||v.requiredMinutes>RESTMAX||v.sleepMinutes+v.lightActivityMinutes!==elapsed||!source(v.sourceRef,LONGLOC))return false;var ready=elapsed>=v.requiredMinutes&&v.sleepMinutes>=360&&v.lightActivityMinutes<=120;return (v.status==='ready')===ready;}return false;}
function edge(v){return closed(v,['data','fromEntityId','kind','toEntityId'])&&typeof v.data==='string'&&typeof v.fromEntityId==='string'&&typeof v.kind==='string'&&typeof v.toEntityId==='string';}
if(!s||!w||!t||!closed(i,['ability','critical'])||(i.ability!=='str'&&i.ability!=='dex')||typeof i.critical!=='boolean'||!Array.isArray(t.relationships))throw new Error('Weapon damage application requires exact roles, target relationships, and ability/critical input.');
var hp=parse(t.components&&t.components['dnd2024.creature.hit-points'],'Target Hit Points');if(!validHp(hp))throw new Error('Target Hit Points are invalid.');
var damageChildren=ctx.children&&ctx.children.damage,mitigationChildren=ctx.children&&ctx.children.mitigation;if(!Array.isArray(damageChildren)||damageChildren.length!==1||!Array.isArray(mitigationChildren)||mitigationChildren.length!==1)throw new Error('Weapon damage application requires exactly one damage and one mitigation child.');
var damageEntry=damageChildren[0],child=parse(damageEntry.output&&damageEntry.output.data,'Damage child');if(!damageEntry.roleEntityIds||damageEntry.roleEntityIds.subject!==s.id||damageEntry.roleEntityIds.weapon!==w.id||!closed(child,['test','subjectId','weaponId','ability','critical','type','rolls','subtotal','modifier','damage'])||child.test!=='weapon-damage'||child.subjectId!==s.id||child.weaponId!==w.id||child.ability!==i.ability||child.critical!==i.critical||TYPES.indexOf(child.type)<0||!safe(child.damage,0))throw new Error('Damage child is invalid for this action.');
var mitigationEntry=mitigationChildren[0],profile=parse(mitigationEntry.output&&mitigationEntry.output.data,'Mitigation child');if(!mitigationEntry.roleEntityIds||mitigationEntry.roleEntityIds.defender!==t.id||!closed(profile,['test','defenderId','mitigationKnown','conditionsKnown','immunities','resistances','vulnerabilities','petrified','sourceRef','petrifiedSourceRef'])||profile.test!=='damage-mitigation-profile'||profile.defenderId!==t.id||typeof profile.mitigationKnown!=='boolean'||typeof profile.conditionsKnown!=='boolean'||typeof profile.petrified!=='boolean'||!ordered(profile.immunities)||!ordered(profile.resistances)||!ordered(profile.vulnerabilities)||!source(profile.sourceRef,MLOC)||!source(profile.petrifiedSourceRef,PLOC)||(!profile.mitigationKnown&&(profile.immunities.length||profile.resistances.length||profile.vulnerabilities.length))||(!profile.conditionsKnown&&profile.petrified))throw new Error('Mitigation child is invalid for this target.');
var raw=child.damage,immune=has(profile.immunities,child.type),reasons=[];if(has(profile.resistances,child.type))reasons.push('damage-mitigation:'+child.type);if(profile.petrified)reasons.push('condition:petrified');var resistanceApplied=!immune&&reasons.length>0,vulnerabilityApplied=!immune&&has(profile.vulnerabilities,child.type),finalDamage=immune?0:raw;if(resistanceApplied)finalDamage=Math.floor(finalDamage/2);if(vulnerabilityApplied){if(finalDamage>Math.floor(MAX/2))throw new Error('Vulnerability would exceed the safe damage limit.');finalDamage*=2;}
var temporaryRaw=t.components&&t.components['dnd2024.creature.temporary-hit-points'],temporary=null;if(temporaryRaw){temporary=parse(temporaryRaw,'Target Temporary Hit Points');if(!closed(temporary,['amount','sourceRef'])||!safe(temporary.amount,1)||!entitySource(temporary.sourceRef))throw new Error('Target Temporary Hit Points are invalid.');}
var restRaw=t.components&&t.components[EP],episode=restRaw?parse(restRaw,'Target Rest Episode'):null,restLinks=[];for(var r=0;r<t.relationships.length;r++){var relationship=t.relationships[r];if(!edge(relationship))throw new Error('Target relationship projection is corrupt.');if(relationship.kind===LINK){if(relationship.toEntityId!==t.id||relationship.data!=='{}')throw new Error('Target rest-world membership is corrupt.');restLinks.push(relationship);}}
if(episode){if(!validEpisode(episode))throw new Error('Target Rest Episode is invalid.');if(restLinks.length!==1||restLinks[0].fromEntityId!==episode.worldId)throw new Error('Target Rest Episode requires exactly one matching world membership.');}else if(restLinks.length)throw new Error('Target has rest-world membership without a Rest Episode.');
var temporaryBefore=temporary?temporary.amount:0,temporaryAbsorbed=Math.min(temporaryBefore,finalDamage),temporaryAfter=temporaryBefore-temporaryAbsorbed,hitPointDamage=finalDamage-temporaryAbsorbed,after={current:Math.max(0,hp.current-hitPointDamage),maximum:hp.maximum},overkill=Math.max(0,hitPointDamage-hp.current),effects=[],restInterruption=null;if(Object.prototype.hasOwnProperty.call(hp,'maximumReduction'))after.maximumReduction=hp.maximumReduction;
if(temporaryAbsorbed>0){if(temporaryAfter>0)effects.push({type:'component.set',entityId:t.id,definitionId:'dnd2024.creature.temporary-hit-points',data:JSON.stringify({amount:temporaryAfter,sourceRef:temporary.sourceRef})});else effects.push({type:'component.remove',entityId:t.id,definitionId:'dnd2024.creature.temporary-hit-points'});}
if(hitPointDamage>0)effects.push({type:'component.set',entityId:t.id,definitionId:'dnd2024.creature.hit-points',data:JSON.stringify(after)});
if(finalDamage>0&&episode&&episode.status==='active'){if(episode.kind==='short'){effects.push({type:'component.remove',entityId:t.id,definitionId:EP});effects.push({type:'relationship.remove',entityId:episode.worldId,toEntityId:t.id,kind:LINK});restInterruption={outcome:'short-stopped',interruptionCount:null,requiredMinutes:null,benefitsGranted:false};}else{if(episode.requiredMinutes>RESTMAX-60||episode.interruptionCount>=16666658)throw new Error('Long Rest damage interruption exceeds the supported duration bounds.');var next={policyEntityId:episode.policyEntityId,kind:'long',worldId:episode.worldId,startedAtMinute:episode.startedAtMinute,observedAtMinute:episode.observedAtMinute,observedClockRevision:episode.observedClockRevision,requiredMinutes:episode.requiredMinutes+60,sleepMinutes:episode.sleepMinutes,lightActivityMinutes:episode.lightActivityMinutes,interruptionCount:episode.interruptionCount+1,status:'active',sourceRef:episode.sourceRef};effects.push({type:'component.set',entityId:t.id,definitionId:EP,data:JSON.stringify(next)});restInterruption={outcome:'long-resumed',interruptionCount:next.interruptionCount,requiredMinutes:next.requiredMinutes,benefitsGranted:false};}}
return {narration:t.name+' takes '+finalDamage+' weapon damage.',data:{test:'weapon-damage-apply',rawDamage:raw,damage:finalDamage,type:child.type,immune:immune,resistanceApplied:resistanceApplied,resistanceReasons:reasons,vulnerabilityApplied:vulnerabilityApplied,temporaryBefore:temporaryBefore,temporaryAfter:temporaryAfter,temporaryAbsorbed:temporaryAbsorbed,hitPointDamage:hitPointDamage,beforeCurrent:hp.current,afterCurrent:after.current,maximum:hp.maximum,overkill:overkill,mitigationChildMechanicId:'mechanic.dnd2024.damage.resolve',restInterruption:restInterruption},effects:effects,events:[],notifications:[]};
