var content=ctx.roles.content,source=ctx.roles.source;
var kinds=['species','background','class','feature','choice-set'];
if(ctx.input===null||Array.isArray(ctx.input)||typeof ctx.input!=='object')throw new Error('Input must be an object.');
var keys=Object.keys(ctx.input).sort(),expected=['contentKey','contentVersion','kind','locator','status'];if(keys.length!==expected.length)throw new Error('Input must contain exactly contentKey, contentVersion, kind, locator, and status.');for(var i=0;i<expected.length;i++)if(keys[i]!==expected[i])throw new Error('Input must contain exactly contentKey, contentVersion, kind, locator, and status.');
if(content.components['dnd2024.character.content-definition'])throw new Error('This entity already has an immutable character content definition.');
if(source.id!=='source.dnd2024.srd-5.2.1'||!source.components['dnd2024.source'])throw new Error('The source role must be the registered D&D SRD 5.2.1 source.');
if(kinds.indexOf(ctx.input.kind)<0)throw new Error('kind must be one of species, background, class, feature, or choice-set.');
if(typeof ctx.input.contentKey!=='string'||!/^[a-z][a-z0-9-]{0,79}$/.test(ctx.input.contentKey))throw new Error('contentKey must be a lower-case canonical key of at most 80 characters.');
if(!Number.isSafeInteger(ctx.input.contentVersion)||ctx.input.contentVersion<1||ctx.input.contentVersion>2147483647)throw new Error('contentVersion must be a positive supported integer.');
if(['active','archived'].indexOf(ctx.input.status)<0)throw new Error('status must be active or archived.');
if(typeof ctx.input.locator!=='string'||ctx.input.locator.trim()!==ctx.input.locator||ctx.input.locator.length<4||ctx.input.locator.length>200||!/^.{1,198}PDF page(?:s)? [0-9]+(?:[–-][0-9]+)?$/.test(ctx.input.locator))throw new Error('locator must be a trimmed SRD heading ending with a PDF page reference.');
var data={kind:ctx.input.kind,contentKey:ctx.input.contentKey,contentVersion:ctx.input.contentVersion,status:ctx.input.status,sourceRef:{sourceId:source.id,locator:ctx.input.locator}};
return {narration:content.name+' is recorded as immutable '+ctx.input.kind+' content '+ctx.input.contentKey+' v'+ctx.input.contentVersion+'.',effects:[{type:'component.add',entityId:content.id,definitionId:'dnd2024.character.content-definition',data:JSON.stringify(data)}],data:{contentId:content.id,kind:data.kind,contentKey:data.contentKey,contentVersion:data.contentVersion,status:data.status,sourceRef:data.sourceRef}};
