var abilities={str:"Strength",dex:"Dexterity",con:"Constitution",int:"Intelligence",wis:"Wisdom",cha:"Charisma"},defaults={acrobatics:"dex","animal-handling":"wis",arcana:"int",athletics:"str",deception:"cha",history:"int",insight:"wis",intimidation:"cha",investigation:"int",medicine:"wis",nature:"int",perception:"wis",performance:"cha",persuasion:"cha",religion:"int","sleight-of-hand":"dex",stealth:"dex",survival:"wis"};
function closed(value,keys){if(value===null||Array.isArray(value)||typeof value!=="object")return false;var actual=Object.keys(value).sort(),expected=keys.slice().sort();if(actual.length!==expected.length)return false;for(var index=0;index<expected.length;index++)if(actual[index]!==expected[index])return false;return true;}
function integer(value,min,max){return typeof value==="number"&&isFinite(value)&&Math.floor(value)===value&&value>=min&&value<=max;}
var subject=ctx.roles.subject,input=ctx.input,scoreKeys=["str","dex","con","int","wis","cha"],inputKeys=input&&typeof input==="object"&&!Array.isArray(input)?Object.keys(input).sort():[];
if(!subject||!subject.components||typeof subject.components["dnd2024.abilities"]!=="string")throw new Error("A raw ability check requires subject ability scores.");
if(inputKeys.length<2||inputKeys.length>4||inputKeys.indexOf("ability")<0||inputKeys.indexOf("dc")<0)throw new Error("Ability-check input must contain ability, dc, and optional skill and rollCircumstances only.");
for(var inputIndex=0;inputIndex<inputKeys.length;inputIndex++)if(inputKeys[inputIndex]!=="ability"&&inputKeys[inputIndex]!=="dc"&&inputKeys[inputIndex]!=="skill"&&inputKeys[inputIndex]!=="rollCircumstances")throw new Error("Ability-check input must contain ability, dc, and optional skill and rollCircumstances only.");
if(typeof input.ability!=="string"||typeof abilities[input.ability]!=="string")throw new Error("ability must be one exact lowercase D&D ability id.");
if(!integer(input.dc,0,2147483637))throw new Error("dc must be an integer from 0 through 2147483637.");
var state;try{state=JSON.parse(subject.components["dnd2024.abilities"]);}catch(error){throw new Error("Subject ability scores are corrupt.");}
if(!closed(state,scoreKeys))throw new Error("Subject ability scores must contain exactly six scores.");
for(var keyIndex=0;keyIndex<scoreKeys.length;keyIndex++)if(!integer(state[scoreKeys[keyIndex]],1,30))throw new Error("Subject ability scores are invalid.");
var skill=input.hasOwnProperty("skill")?input.skill:null,proficient=null,bonus=null,defaultAbility=null,level=null;
if(skill!==null){if(typeof skill!=="string"||typeof defaults[skill]!=="string")throw new Error("skill must be one exact D&D skill id.");defaultAbility=defaults[skill];if(typeof subject.components["dnd2024.character-level"]!=="string"||typeof subject.components["dnd2024.skill-proficiencies"]!=="string")throw new Error("Named skill checks require known character level and skill proficiency state.");var levelState,skills;try{levelState=JSON.parse(subject.components["dnd2024.character-level"]);skills=JSON.parse(subject.components["dnd2024.skill-proficiencies"]);}catch(error){throw new Error("Named skill-check proficiency state is corrupt.");}if(!closed(levelState,["level","sourceRef"])||!integer(levelState.level,1,20)||!closed(levelState.sourceRef,["locator","sourceId"])||levelState.sourceRef.sourceId!=="source.dnd2024.srd-5.2.1"||levelState.sourceRef.locator!=="Character Creation > Level Advancement > Character Advancement")throw new Error("Character level state is invalid.");if(!closed(skills,["skills","sourceRef"])||!Array.isArray(skills.skills)||!closed(skills.sourceRef,["locator","sourceId"])||skills.sourceRef.sourceId!=="source.dnd2024.srd-5.2.1"||skills.sourceRef.locator!=="Playing the Game > Proficiency > Skill Proficiencies and Skills")throw new Error("Skill-proficiency state is invalid.");var listed={};for(var listIndex=0;listIndex<skills.skills.length;listIndex++){var listedSkill=skills.skills[listIndex];if(typeof defaults[listedSkill]!=="string"||listed[listedSkill])throw new Error("Skill-proficiency state is invalid.");listed[listedSkill]=true;}level=levelState.level;bonus=2+Math.floor((level-1)/4);proficient=listed[skill]===true;}
var circumstances=input.hasOwnProperty("rollCircumstances")?input.rollCircumstances:[];
if(!Array.isArray(circumstances))throw new Error("rollCircumstances must be an array when supplied.");
if(input.hasOwnProperty("rollCircumstances")&&circumstances.length===0)throw new Error("rollCircumstances must be nonempty when supplied.");
var hasAdvantage=false,hasDisadvantage=false,circumstancePairs={},acceptedCircumstances=[];
for(var circumstanceIndex=0;circumstanceIndex<circumstances.length;circumstanceIndex++){var circumstance=circumstances[circumstanceIndex];if(!closed(circumstance,["kind","source"])||(circumstance.kind!=="advantage"&&circumstance.kind!=="disadvantage")||typeof circumstance.source!=="string"||circumstance.source.length===0||circumstance.source!==circumstance.source.trim()||circumstance.source.indexOf("condition:")===0)throw new Error("Each roll circumstance must be an explicit advantage or disadvantage source.");var pair=circumstance.kind+"\n"+circumstance.source;if(circumstancePairs[pair])throw new Error("rollCircumstances must not repeat the same kind and source.");circumstancePairs[pair]=true;acceptedCircumstances.push({kind:circumstance.kind,source:circumstance.source});if(circumstance.kind==="advantage")hasAdvantage=true;else hasDisadvantage=true;}
var rollMode=hasAdvantage&&hasDisadvantage?"normal":hasAdvantage?"advantage":hasDisadvantage?"disadvantage":"normal",rolls=[ctx.randomInt(1,20)];
if(rollMode!=="normal")rolls.push(ctx.randomInt(1,20));
var roll=rolls.length===1?rolls[0]:rollMode==="advantage"?Math.max(rolls[0],rolls[1]):Math.min(rolls[0],rolls[1]);
var score=state[input.ability],modifier=Math.floor((score-10)/2),total=roll+modifier+(proficient?bonus:0),succeeded=total>=input.dc,label=abilities[input.ability]+(skill===null?"":" ("+skill+")"),modifiers=[{source:input.ability+" "+score,value:modifier}];if(proficient)modifiers.push({source:"proficiency (level "+level+"; "+skill+")",value:bonus});
return {narration:subject.name+" makes a "+label+" check: "+roll+" + modifiers = "+total+" vs DC "+input.dc+" ("+(succeeded?"success":"failure")+").",data:{test:"ability-check",ability:input.ability,skill:skill,defaultAbility:defaultAbility,proficient:proficient,dc:input.dc,die:"1d20",rollMode:rollMode,rolls:rolls,roll:roll,rollCircumstances:acceptedCircumstances,modifier:modifier,modifiers:modifiers,total:total,succeeded:succeeded,source:"SRD 5.2.1 - Playing the Game > D20 Tests > Ability Checks"},effects:[],events:[],notifications:[]};
