var ordered=['str','dex','con','int','wis','cha'],EP='dnd2024.rest-episode',LINK='rest.world',SID='source.dnd2024.srd-5.2.1',SHORTLOC='Rules Glossary > Short Rest, PDF page 187',LONGLOC='Rules Glossary > Long Rest, PDF page 185',RESTMAX=1000000000;
function closed(value,keys){if(value===null||Array.isArray(value)||typeof value!=='object')return false;var actual=Object.keys(value).sort(),expected=keys.slice().sort();if(actual.length!==expected.length)return false;for(var index=0;index<expected.length;index++)if(actual[index]!==expected[index])return false;return true;}
function integer(value,min,max){return typeof value==='number'&&isFinite(value)&&Math.floor(value)===value&&value>=min&&value<=max;}
function text(value,max){return typeof value==='string'&&value.length>0&&value===value.trim()&&Array.from(value).length<=max;}
function parse(raw,label){if(typeof raw!=='string')throw new Error(label+' is corrupt.');try{return JSON.parse(raw);}catch(error){throw new Error(label+' is corrupt.');}}
function source(value,locator){return closed(value,['sourceId','locator'])&&value.sourceId===SID&&value.locator===locator;}
function validEpisode(value){if(!value||value.policyEntityId!=='content.dnd2024.rest-policy.standard.v1'||!text(value.worldId,200)||!integer(value.startedAtMinute,0,RESTMAX)||!integer(value.observedAtMinute,value.startedAtMinute,RESTMAX)||!integer(value.observedClockRevision,0,2147483647)||(value.status!=='active'&&value.status!=='ready'))return false;var elapsed=value.observedAtMinute-value.startedAtMinute;if(value.kind==='short'){if(!closed(value,['policyEntityId','kind','worldId','startedAtMinute','observedAtMinute','observedClockRevision','requiredMinutes','lightActivityMinutes','status','sourceRef'])||value.requiredMinutes!==60||!integer(value.lightActivityMinutes,0,RESTMAX)||value.lightActivityMinutes!==elapsed||!source(value.sourceRef,SHORTLOC))return false;return (value.status==='ready')===(value.lightActivityMinutes>=value.requiredMinutes);}if(value.kind==='long'){if(!closed(value,['policyEntityId','kind','worldId','startedAtMinute','observedAtMinute','observedClockRevision','requiredMinutes','sleepMinutes','lightActivityMinutes','interruptionCount','status','sourceRef'])||!integer(value.sleepMinutes,0,RESTMAX)||!integer(value.lightActivityMinutes,0,120)||!integer(value.interruptionCount,0,16666658)||value.requiredMinutes!==480+60*value.interruptionCount||value.requiredMinutes>RESTMAX||value.sleepMinutes+value.lightActivityMinutes!==elapsed||!source(value.sourceRef,LONGLOC))return false;var ready=elapsed>=value.requiredMinutes&&value.sleepMinutes>=360&&value.lightActivityMinutes<=120;return (value.status==='ready')===ready;}return false;}
function edge(value){return closed(value,['data','fromEntityId','kind','toEntityId'])&&typeof value.data==='string'&&typeof value.fromEntityId==='string'&&typeof value.kind==='string'&&typeof value.toEntityId==='string';}
var subject=ctx.roles.subject,input=ctx.input,keys=input&&typeof input==='object'&&!Array.isArray(input)?Object.keys(input).sort():[];
if(!subject||!subject.components||typeof subject.components['dnd2024.abilities']!=='string'||!Array.isArray(subject.relationships))throw new Error('Initiative requires subject ability scores and relationships.');
if(keys.length>1||(keys.length===1&&keys[0]!=='rollCircumstances'))throw new Error('Initiative input must contain only optional rollCircumstances.');
var state;try{state=JSON.parse(subject.components['dnd2024.abilities']);}catch(error){throw new Error('Subject ability scores are corrupt.');}if(!closed(state,ordered))throw new Error('Subject ability scores are invalid.');for(var abilityIndex=0;abilityIndex<ordered.length;abilityIndex++)if(!integer(state[ordered[abilityIndex]],1,30))throw new Error('Subject ability scores are invalid.');
var episodeRaw=subject.components[EP],episode=episodeRaw?parse(episodeRaw,'Subject Rest Episode'):null,restLinks=[];for(var relationshipIndex=0;relationshipIndex<subject.relationships.length;relationshipIndex++){var relationship=subject.relationships[relationshipIndex];if(!edge(relationship))throw new Error('Subject relationship projection is corrupt.');if(relationship.kind===LINK){if(relationship.toEntityId!==subject.id||relationship.data!=='{}')throw new Error('Subject rest-world membership is corrupt.');restLinks.push(relationship);}}
if(episode){if(!validEpisode(episode))throw new Error('Subject Rest Episode is invalid.');if(restLinks.length!==1||restLinks[0].fromEntityId!==episode.worldId)throw new Error('Subject Rest Episode requires exactly one matching world membership.');}else if(restLinks.length)throw new Error('Subject has rest-world membership without a Rest Episode.');
var circumstances=keys.length===1?input.rollCircumstances:[];if(!Array.isArray(circumstances))throw new Error('rollCircumstances must be an array when supplied.');if(keys.length===1&&circumstances.length===0)throw new Error('rollCircumstances must be nonempty when supplied.');var hasAdvantage=false,hasDisadvantage=false,pairs={},accepted=[];for(var circumstanceIndex=0;circumstanceIndex<circumstances.length;circumstanceIndex++){var circumstance=circumstances[circumstanceIndex];if(!closed(circumstance,['kind','source'])||(circumstance.kind!=='advantage'&&circumstance.kind!=='disadvantage')||typeof circumstance.source!=='string'||circumstance.source.length===0||circumstance.source!==circumstance.source.trim()||circumstance.source.indexOf('condition:')===0)throw new Error('Each roll circumstance must be an explicit advantage or disadvantage source.');var pair=circumstance.kind+'\n'+circumstance.source;if(pairs[pair])throw new Error('rollCircumstances must not repeat the same kind and source.');pairs[pair]=true;accepted.push({kind:circumstance.kind,source:circumstance.source});if(circumstance.kind==='advantage')hasAdvantage=true;else hasDisadvantage=true;}
var rollMode=hasAdvantage&&hasDisadvantage?'normal':hasAdvantage?'advantage':hasDisadvantage?'disadvantage':'normal',rolls=[ctx.randomInt(1,20)];if(rollMode!=='normal')rolls.push(ctx.randomInt(1,20));var roll=rolls.length===1?rolls[0]:rollMode==='advantage'?Math.max(rolls[0],rolls[1]):Math.min(rolls[0],rolls[1]),modifier=Math.floor((state.dex-10)/2),initiative=roll+modifier,restInterruption=null;
if(episode&&episode.status==='active'){if(episode.kind==='short')restInterruption={outcome:'short-stopped',worldId:episode.worldId,benefitsGranted:false};else{if(episode.requiredMinutes>RESTMAX-60||episode.interruptionCount>=16666658)throw new Error('Long Rest Initiative interruption exceeds the supported duration bounds.');var next={policyEntityId:episode.policyEntityId,kind:'long',worldId:episode.worldId,startedAtMinute:episode.startedAtMinute,observedAtMinute:episode.observedAtMinute,observedClockRevision:episode.observedClockRevision,requiredMinutes:episode.requiredMinutes+60,sleepMinutes:episode.sleepMinutes,lightActivityMinutes:episode.lightActivityMinutes,interruptionCount:episode.interruptionCount+1,status:'active',sourceRef:episode.sourceRef};restInterruption={outcome:'long-resumed',worldId:episode.worldId,episode:next,benefitsGranted:false};}}
return {narration:subject.name+' rolls Initiative: '+roll+' + '+modifier+' = '+initiative+'.',data:{test:'initiative',subjectId:subject.id,ability:'dex',die:'1d20',rollMode:rollMode,rolls:rolls,roll:roll,rollCircumstances:accepted,modifiers:[{source:'dex '+state.dex,value:modifier}],initiative:initiative,source:'SRD 5.2.1 - Playing the Game > Combat > The Order of Combat > Initiative',restInterruption:restInterruption},effects:[],events:[],notifications:[]};
