var SID='source.dnd2024.srd-5.2.1',LOC='Playing the Game > Combat > The Order of Combat',ORDER='dnd2024.encounter-initiative-order',STATE='dnd2024.encounter-turn-state',e=ctx.roles.encounter,i=ctx.input,MAX=9007199254740991;
function closed(v,k){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length!==k.length)return false;for(var x=0;x<k.length;x++)if(!Object.prototype.hasOwnProperty.call(v,k[x]))return false;return true;}
function integer(v,min,max){return typeof v==='number'&&isFinite(v)&&Math.floor(v)===v&&v>=min&&v<=max;}
function source(v,loc){return closed(v,['sourceId','locator'])&&v.sourceId===SID&&v.locator===loc;}
function parse(raw,name){try{return JSON.parse(raw);}catch(error){throw new Error(name+' is corrupt.');}}
function speed(v){return closed(v,['walkFeet','burrowFeet','climbFeet','flyFeet','swimFeet','sourceRef'])&&integer(v.walkFeet,5,1000)&&v.walkFeet%5===0&&source(v.sourceRef,'Rules Glossary > Speed');}
function reports(key,roleName,idName,test,valueName,roster,count,extras){var kids=ctx.children&&ctx.children[key],out={},n,k,role,data,keys=['test',idName,'present','valid','problem',valueName].concat(extras||[]);if(!Array.isArray(kids)||kids.length!==count)throw new Error('Exactly one '+test+' diagnostic is required per participant.');for(n=0;n<kids.length;n++){k=kids[n];role=k&&k.roleEntityIds&&k.roleEntityIds[roleName];if(!role||!roster[role]||out[role])throw new Error(test+' diagnostics do not match the roster.');try{data=JSON.parse(k.output&&k.output.data?k.output.data:'{}');}catch(error){throw new Error(test+' diagnostics are unreadable.');}if(!closed(data,keys)||data.test!==test||data[idName]!==role||typeof data.present!=='boolean'||typeof data.valid!=='boolean')throw new Error(test+' diagnostic shape is invalid.');out[role]=data;}return out;}
if(!e||!closed(i,[]))throw new Error('Advancing an encounter turn requires exactly an empty object input.');var snapshot=parse(e.components&&e.components[ORDER],'Encounter Initiative order');if(!closed(snapshot,['order','sourceRef'])||!Array.isArray(snapshot.order)||snapshot.order.length<1||snapshot.order.length>100||!source(snapshot.sourceRef,LOC+' > Initiative'))throw new Error('Encounter Initiative order is invalid.');
var ids={},roster={},contents=e.contains||[],n,row;if(contents.length!==snapshot.order.length)throw new Error('Encounter containment does not match Initiative.');for(n=0;n<snapshot.order.length;n++){row=snapshot.order[n];if(!closed(row,['participantId','initiative'])||typeof row.participantId!=='string'||!row.participantId||!integer(row.initiative,-MAX,MAX)||ids[row.participantId])throw new Error('Encounter Initiative order is invalid.');ids[row.participantId]=true;}for(n=0;n<contents.length;n++){if(!contents[n]||!ids[contents[n].id]||roster[contents[n].id])throw new Error('Encounter containment does not match Initiative.');roster[contents[n].id]=true;}
var current=parse(e.components&&e.components[STATE],'Encounter turn state');if(!closed(current,['status','round','turnIndex','sourceRef'])||current.status!=='active'||!integer(current.round,1,MAX)||!integer(current.turnIndex,0,snapshot.order.length-1)||!source(current.sourceRef,LOC))throw new Error('Encounter turn state is inactive or invalid.');var index=current.turnIndex+1,round=current.round,wrap=index>=snapshot.order.length;if(wrap){if(round===MAX)throw new Error('Encounter round exceeds the safe boundary.');index=0;round++;}
var budgets=reports('budgets','participant','participantId','turn-budget-read','budget',roster,snapshot.order.length,['conditionsPresent','conditionsValid','conditionProblem','exhaustionLevel']),speeds=reports('speeds','subject','subjectId','speed-read','speed',roster,snapshot.order.length),active=snapshot.order[index].participantId,budget=budgets[active],speedReport=speeds[active];if(!budget||!budget.present||!budget.valid||budget.problem!==null||!budget.budget||!budget.conditionsValid||!integer(budget.exhaustionLevel,0,6))throw new Error('The active participant has invalid budget or Condition state.');if(!speedReport||!speedReport.present||!speedReport.valid||speedReport.problem!==null||!speed(speedReport.speed))throw new Error('The active participant has no valid Speed.');
var maximum=speedReport.speed.walkFeet,reduction=5*budget.exhaustionLevel,remaining=Math.max(0,maximum-reduction),restored={action:true,bonusAction:true,reaction:true,freeInteraction:true,movementRemainingFeet:remaining,sourceRef:budget.budget.sourceRef},next={status:'active',round:round,turnIndex:index,sourceRef:current.sourceRef};
return {narration:e.name+' advances its turn.',data:{test:'encounter-turn-advance',encounterId:e.id,previousParticipantId:snapshot.order[current.turnIndex].participantId,activeParticipantId:active,restoredParticipantId:active,walkFeet:maximum,movementReductionFeet:reduction,movementRemainingFeet:remaining,previousRound:current.round,round:round,previousTurnIndex:current.turnIndex,turnIndex:index,startedNewRound:wrap,participantCount:snapshot.order.length},effects:[{type:'component.set',entityId:e.id,definitionId:STATE,data:JSON.stringify(next)},{type:'component.set',entityId:active,definitionId:'dnd2024.turn-budget',data:JSON.stringify(restored)}],events:[],notifications:[]};
