var ordered=["str","dex","con","int","wis","cha"];
function closed(value,keys){if(value===null||Array.isArray(value)||typeof value!=="object")return false;var actual=Object.keys(value).sort(),expected=keys.slice().sort();if(actual.length!==expected.length)return false;for(var index=0;index<expected.length;index++)if(actual[index]!==expected[index])return false;return true;}
function integer(value,min,max){return typeof value==="number"&&isFinite(value)&&Math.floor(value)===value&&value>=min&&value<=max;}
var subject=ctx.roles.subject,input=ctx.input,keys=input&&typeof input==="object"&&!Array.isArray(input)?Object.keys(input).sort():[];
if(!subject||!subject.components||typeof subject.components["dnd2024.abilities"]!=="string")throw new Error("Initiative requires subject ability scores.");
if(keys.length>1||(keys.length===1&&keys[0]!=="rollCircumstances"))throw new Error("Initiative input must contain only optional rollCircumstances.");
var state;try{state=JSON.parse(subject.components["dnd2024.abilities"]);}catch(error){throw new Error("Subject ability scores are corrupt.");}if(!closed(state,ordered))throw new Error("Subject ability scores are invalid.");for(var abilityIndex=0;abilityIndex<ordered.length;abilityIndex++)if(!integer(state[ordered[abilityIndex]],1,30))throw new Error("Subject ability scores are invalid.");
var circumstances=keys.length===1?input.rollCircumstances:[];if(!Array.isArray(circumstances))throw new Error("rollCircumstances must be an array when supplied.");if(keys.length===1&&circumstances.length===0)throw new Error("rollCircumstances must be nonempty when supplied.");var hasAdvantage=false,hasDisadvantage=false,pairs={},accepted=[];for(var circumstanceIndex=0;circumstanceIndex<circumstances.length;circumstanceIndex++){var circumstance=circumstances[circumstanceIndex];if(!closed(circumstance,["kind","source"])||(circumstance.kind!=="advantage"&&circumstance.kind!=="disadvantage")||typeof circumstance.source!=="string"||circumstance.source.length===0||circumstance.source!==circumstance.source.trim()||circumstance.source.indexOf("condition:")===0)throw new Error("Each roll circumstance must be an explicit advantage or disadvantage source.");var pair=circumstance.kind+"\n"+circumstance.source;if(pairs[pair])throw new Error("rollCircumstances must not repeat the same kind and source.");pairs[pair]=true;accepted.push({kind:circumstance.kind,source:circumstance.source});if(circumstance.kind==="advantage")hasAdvantage=true;else hasDisadvantage=true;}
var rollMode=hasAdvantage&&hasDisadvantage?"normal":hasAdvantage?"advantage":hasDisadvantage?"disadvantage":"normal",rolls=[ctx.randomInt(1,20)];if(rollMode!=="normal")rolls.push(ctx.randomInt(1,20));var roll=rolls.length===1?rolls[0]:rollMode==="advantage"?Math.max(rolls[0],rolls[1]):Math.min(rolls[0],rolls[1]),modifier=Math.floor((state.dex-10)/2),initiative=roll+modifier;
return {narration:subject.name+" rolls Initiative: "+roll+" + "+modifier+" = "+initiative+".",data:{test:"initiative",ability:"dex",die:"1d20",rollMode:rollMode,rolls:rolls,roll:roll,rollCircumstances:accepted,modifiers:[{source:"dex "+state.dex,value:modifier}],initiative:initiative,source:"SRD 5.2.1 - Playing the Game > Combat > The Order of Combat > Initiative"},effects:[],events:[],notifications:[]};
