var creature=ctx.roles.creature,world=ctx.roles.world,policy=ctx.roles.policy;
var EP='dnd2024.rest-episode',HP='dnd2024.hit-points',ROOT='game.core.world.root',CLOCK='game.core.world.clock',POL='dnd2024.rest-policy',PID='content.dnd2024.rest-policy.standard.v1',LINK='dnd2024.rest.world',SID='source.dnd2024.srd-5.2.1';
function closed(v,k){if(!v||typeof v!=='object'||Array.isArray(v))return false;var a=Object.keys(v).sort();if(a.length!==k.length)return false;for(var i=0;i<k.length;i++)if(a[i]!==k[i])return false;return true;}
function parse(v,n){if(typeof v!=='string')throw new Error(n+' is corrupt.');try{return JSON.parse(v);}catch(e){throw new Error(n+' is corrupt.');}}
function text(v,n){return typeof v==='string'&&v.length>0&&v===v.trim()&&Array.from(v).length<=n;}
function integer(v,a,b){return typeof v==='number'&&Number.isSafeInteger(v)&&v>=a&&v<=b;}
function source(v,l){return closed(v,['locator','sourceId'])&&v.sourceId===SID&&v.locator===l;}
function validClock(v){return closed(v,['calendarId','currentMinute','revision'])&&text(v.calendarId,100)&&integer(v.currentMinute,0,1000000000)&&integer(v.revision,0,2147483647);}
function validHp(v){return closed(v,['current','maximum','sourceRef'])&&integer(v.current,0,9007199254740991)&&integer(v.maximum,1,9007199254740991)&&v.current<=v.maximum&&source(v.sourceRef,'Playing the Game > Damage and Healing > Hit Points');}
function validPolicy(v){return closed(v,['longRest','policyKey','policyVersion','shortRest','sourceRef'])&&v.policyKey==='standard'&&v.policyVersion===1&&source(v.sourceRef,'Rules Glossary > Short Rest and Long Rest, PDF pages 184 and 186')&&closed(v.shortRest,['benefits','interruptions','minimumHitPoints','minimumMinutes','permittedActivity'])&&v.shortRest.minimumMinutes===60&&v.shortRest.minimumHitPoints===1&&v.shortRest.permittedActivity==='light'&&JSON.stringify(v.shortRest.interruptions)===JSON.stringify(['initiative','non-cantrip-spell','damage'])&&JSON.stringify(v.shortRest.benefits)===JSON.stringify(['spend-hit-die','source-specific-recharge'])&&closed(v.longRest,['additionalMinutesPerInterruption','benefits','interruptions','maximumLightActivityMinutes','minimumHitPoints','minimumMinutes','minimumSleepMinutes','partialShortRestMinutes','permittedActivity','restartWaitMinutes'])&&v.longRest.minimumMinutes===480&&v.longRest.minimumSleepMinutes===360&&v.longRest.maximumLightActivityMinutes===120&&v.longRest.minimumHitPoints===1&&v.longRest.restartWaitMinutes===960&&v.longRest.partialShortRestMinutes===60&&v.longRest.additionalMinutesPerInterruption===60&&v.longRest.permittedActivity==='light'&&JSON.stringify(v.longRest.interruptions)===JSON.stringify(['initiative','non-cantrip-spell','damage','walking-or-physical-exertion'])&&JSON.stringify(v.longRest.benefits)===JSON.stringify(['restore-hit-points','restore-hit-point-dice','restore-hit-point-maximum','restore-ability-scores','reduce-exhaustion','expire-temporary-hit-points','source-specific-recharge']);}
function edge(v){return closed(v,['data','fromEntityId','kind','toEntityId'])&&typeof v.data==='string'&&typeof v.fromEntityId==='string'&&typeof v.kind==='string'&&typeof v.toEntityId==='string';}
if(!closed(ctx.input,['kind'])||(ctx.input.kind!=='short'&&ctx.input.kind!=='long'))throw new Error('Rest input requires exactly {"kind":"short"|"long"}. Do not supply time, interruption, recovery, policy data, or effects.');
if(!creature||!world||!policy||!creature.components||!world.components||!policy.components||!Array.isArray(world.relationships))throw new Error('Rest begin requires creature, world, and policy projections.');
if(!text(creature.id,200)||!text(world.id,200)||policy.id!==PID||creature.id===world.id||creature.id===policy.id||world.id===policy.id)throw new Error('Rest roles must identify distinct creature, world, and canonical policy entities.');
if(creature.components[EP])throw new Error('The creature already has a rest episode.');
var root=parse(world.components[ROOT],'World root'),clock=parse(world.components[CLOCK],'World clock'),hp=parse(creature.components[HP],'Hit Points'),p=parse(policy.components[POL],'Rest policy');
if(!closed(root,['status','summary','visibility'])||root.status!=='active'||!text(root.summary,1000)||(root.visibility!=='public'&&root.visibility!=='party'&&root.visibility!=='gm'))throw new Error('World root is invalid or inactive.');
if(!validClock(clock)||!validHp(hp)||!validPolicy(p))throw new Error('Rest requires valid root-clock, Hit Point, and immutable policy state.');
if(hp.current<1)throw new Error('A rest requires at least 1 current Hit Point.');
for(var i=0;i<world.relationships.length;i++){var link=world.relationships[i];if(!edge(link))throw new Error('World relationship projection is corrupt.');if(link.kind===LINK&&link.fromEntityId===world.id&&link.toEntityId===creature.id){if(link.data!=='{}')throw new Error('Existing rest-world membership is corrupt.');throw new Error('The creature already belongs to a rest episode in this world.');}}
var short=ctx.input.kind==='short',required=short?p.shortRest.minimumMinutes:p.longRest.minimumMinutes,locator=short?'Rules Glossary > Short Rest, PDF page 186':'Rules Glossary > Long Rest, PDF page 184';
var episode={policyEntityId:PID,kind:ctx.input.kind,worldId:world.id,startedAtMinute:clock.currentMinute,requiredMinutes:required,status:'active',sourceRef:{sourceId:SID,locator:locator}};
return {narration:creature.name+' begins a '+(short?'Short':'Long')+' Rest.',effects:[{type:'component.add',entityId:creature.id,definitionId:EP,data:JSON.stringify(episode)},{type:'relationship.create',entityId:world.id,toEntityId:creature.id,kind:LINK,data:'{}'}],data:{test:'rest-begin',creatureId:creature.id,worldId:world.id,policyEntityId:PID,kind:episode.kind,startedAtMinute:episode.startedAtMinute,requiredMinutes:episode.requiredMinutes}};
