var SID='source.dnd2024.srd-5.2.1',CONTENT='dnd2024.character.content-definition',PROGRESSION='dnd2024.class-progression',c=ctx.roles['class'],i=ctx.input;
function closed(v,keys){if(!v||typeof v!=='object'||Array.isArray(v))return false;var a=Object.keys(v);if(a.length!==keys.length)return false;for(var n=0;n<keys.length;n++)if(!Object.prototype.hasOwnProperty.call(v,keys[n]))return false;return true;}
function id(v,prefix){return typeof v==='string'&&new RegExp('^'+prefix+'[a-z0-9.-]+\\.v[1-9][0-9]*$').test(v);}
function ref(v){return closed(v,['sourceId','locator'])&&v.sourceId===SID&&typeof v.locator==='string'&&/^.{1,198}PDF page(?:s)? [0-9]+(?:[–-][0-9]+)?$/.test(v.locator);}
function content(v){return closed(v,['kind','contentKey','contentVersion','status','sourceRef'])&&v.kind==='class'&&typeof v.contentKey==='string'&&/^[a-z][a-z0-9-]{0,79}$/.test(v.contentKey)&&typeof v.contentVersion==='number'&&isFinite(v.contentVersion)&&Math.floor(v.contentVersion)===v.contentVersion&&v.contentVersion>=1&&v.contentVersion<=2147483647&&v.status==='active'&&ref(v.sourceRef);}
function ordered(a,prefix){if(!Array.isArray(a)||a.length>32)return false;for(var n=0;n<a.length;n++){if(!id(a[n],prefix)||(n&&a[n-1]>=a[n]))return false;}return true;}
function pair(d,f){return d===6&&f===4||d===8&&f===5||d===10&&f===6||d===12&&f===7;}
function progression(v){if(!closed(v,['hitDieSides','fixedHitPointGainBeforeConstitution','levels','sourceRef'])||!pair(v.hitDieSides,v.fixedHitPointGainBeforeConstitution)||!ref(v.sourceRef)||!Array.isArray(v.levels)||v.levels.length<1||v.levels.length>20)return false;for(var n=0;n<v.levels.length;n++){var x=v.levels[n];if(!closed(x,['classLevel','featureDefinitionIds','choiceSetDefinitionIds'])||typeof x.classLevel!=='number'||!isFinite(x.classLevel)||Math.floor(x.classLevel)!==x.classLevel||x.classLevel<1||x.classLevel>20||(n&&v.levels[n-1].classLevel>=x.classLevel)||!ordered(x.featureDefinitionIds,'content\\.dnd2024\\.feature\\.')||!ordered(x.choiceSetDefinitionIds,'content\\.dnd2024\\.choice-set\\.'))return false;}return true;}
function state(raw,valid){if(!raw)return {present:false,valid:false,problem:'absent',value:null};var value;try{value=typeof raw==='string'?JSON.parse(raw):raw;}catch(error){return {present:true,valid:false,problem:'malformed',value:null};}return valid(value)?{present:true,valid:true,problem:null,value:value}:{present:true,valid:false,problem:'invalid',value:null};}
function data(status,problem,cs,ps,level,entry){var features=entry?entry.featureDefinitionIds.map(function(definitionId){return {definitionId:definitionId,behaviorStatus:'unimplemented'};}):[];return {test:'class-progression-read',classId:c.id,content:{present:cs.present,valid:cs.valid,problem:cs.problem},progression:{present:ps.present,valid:ps.valid,problem:ps.problem},requestedClassLevel:level,status:status,problem:problem,hitDieSides:ps.value?ps.value.hitDieSides:null,fixedHitPointGainBeforeConstitution:ps.value?ps.value.fixedHitPointGainBeforeConstitution:null,featureEntitlements:features,choiceSetDefinitionIds:entry?entry.choiceSetDefinitionIds:[]};}
if(!c)throw new Error('A class role is required.');
if(!closed(i,['classLevel']))throw new Error('Reading class progression requires exactly classLevel. Do not supply class id, total level, Hit Points, Constitution, feature ids, campaign, authorization, or effects.');
if(typeof i.classLevel!=='number'||!isFinite(i.classLevel)||Math.floor(i.classLevel)!==i.classLevel||i.classLevel<1||i.classLevel>20)throw new Error('classLevel must be an integer from 1 through 20.');
var cs=state(c.components&&c.components[CONTENT],content),ps=state(c.components&&c.components[PROGRESSION],progression);
if(!cs.valid||!ps.valid)return {narration:c.name+' has unknown class progression.',data:data('unknown',!cs.valid?'invalid-class-content':'invalid-progression',cs,ps,i.classLevel,null),effects:[]};
if(cs.value.sourceRef.sourceId!==ps.value.sourceRef.sourceId||cs.value.sourceRef.locator!==ps.value.sourceRef.locator)return {narration:c.name+' has mismatched class progression provenance.',data:data('unknown','source-mismatch',cs,ps,i.classLevel,null),effects:[]};
var entry=null;for(var n=0;n<ps.value.levels.length;n++)if(ps.value.levels[n].classLevel===i.classLevel){entry=ps.value.levels[n];break;}
if(!entry)return {narration:c.name+' has no declaration for class level '+i.classLevel+'.',data:data('unsupported-level','unsupported-level',cs,ps,i.classLevel,null),effects:[]};
return {narration:c.name+' has a declared class level '+i.classLevel+' progression.',data:data('supported',null,cs,ps,i.classLevel,entry),effects:[]};
