// <auto-generated />
using System;
using DantesRoleplay.Web.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DantesRoleplay.Web.Storage.Migrations
{
    [DbContext(typeof(WebContentDbContext))]
    [Migration("20260907023758_DurableWebAssetContent")]
    partial class DurableWebAssetContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("DantesRoleplay.Web.Pages.WebPage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveRevision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("web_page", null, t =>
                        {
                            t.HasCheckConstraint("CK_web_page_active_revision", "\"ActiveRevision\" > 0");
                        });
                });

            modelBuilder.Entity("DantesRoleplay.Web.Pages.WebPageAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("TEXT");

                    b.Property<long>("PageRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("PageRevisionId", "Path")
                        .IsUnique();

                    b.ToTable("web_page_asset", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.Web.Pages.WebPageAssetContent", b =>
                {
                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("ContentHash");

                    b.ToTable("web_page_asset_content", null, t =>
                        {
                            t.HasCheckConstraint("CK_web_page_asset_content_hash", "length(\"ContentHash\") = 64 AND \"ContentHash\" NOT GLOB '*[^0-9A-F]*'");
                        });
                });

            modelBuilder.Entity("DantesRoleplay.Web.Pages.WebPageMigrationReportRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("web_page_migration_report", (string)null);
                });

            modelBuilder.Entity("DantesRoleplay.Web.Pages.WebPageRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Html")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PageId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PageId", "Revision")
                        .IsUnique();

                    b.ToTable("web_page_revision", null, t =>
                        {
                            t.HasCheckConstraint("CK_web_page_revision_revision", "\"Revision\" > 0");
                        });
                });

            modelBuilder.Entity("DantesRoleplay.Web.Pages.WebPageAsset", b =>
                {
                    b.HasOne("DantesRoleplay.Web.Pages.WebPageAssetContent", "Payload")
                        .WithMany("Assets")
                        .HasForeignKey("ContentHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DantesRoleplay.Web.Pages.WebPageRevision", "PageRevision")
                        .WithMany("Assets")
                        .HasForeignKey("PageRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PageRevision");

                    b.Navigation("Payload");
                });

            modelBuilder.Entity("DantesRoleplay.Web.Pages.WebPageRevision", b =>
                {
                    b.HasOne("DantesRoleplay.Web.Pages.WebPage", "Page")
                        .WithMany("Revisions")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("DantesRoleplay.Web.Pages.WebPage", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("DantesRoleplay.Web.Pages.WebPageAssetContent", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("DantesRoleplay.Web.Pages.WebPageRevision", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
