var abilities={str:"Strength",dex:"Dexterity",con:"Constitution",int:"Intelligence",wis:"Wisdom",cha:"Charisma"},abilityRefs={str:"dnd2024.vocabulary.ability.strength",dex:"dnd2024.vocabulary.ability.dexterity",con:"dnd2024.vocabulary.ability.constitution",int:"dnd2024.vocabulary.ability.intelligence",wis:"dnd2024.vocabulary.ability.wisdom",cha:"dnd2024.vocabulary.ability.charisma"},defaults={acrobatics:"dex","animal-handling":"wis",arcana:"int",athletics:"str",deception:"cha",history:"int",insight:"wis",intimidation:"cha",investigation:"int",medicine:"wis",nature:"int",perception:"wis",performance:"cha",persuasion:"cha",religion:"int","sleight-of-hand":"dex",stealth:"dex",survival:"wis"};
function closed(value,keys){if(value===null||Array.isArray(value)||typeof value!=="object")return false;var actual=Object.keys(value).sort(),expected=keys.slice().sort();if(actual.length!==expected.length)return false;for(var index=0;index<expected.length;index++)if(actual[index]!==expected[index])return false;return true;}
function integer(value,min,max){return typeof value==="number"&&isFinite(value)&&Math.floor(value)===value&&value>=min&&value<=max;}
function derivedLevel(subject){var children=ctx.children&&ctx.children.level;if(!Array.isArray(children)||children.length!==1||!children[0].roleEntityIds||children[0].roleEntityIds.subject!==subject.id)throw new Error("Exactly one matching character-level result is required.");var value;try{value=JSON.parse(children[0].output&&children[0].output.data?children[0].output.data:"{}");}catch(error){throw new Error("Character-level result is unreadable.");}if(!closed(value,["membershipCount","present","problem","proficiencyBonus","subjectId","test","totalLevel","valid"])||value.test!=="character-level-read"||value.subjectId!==subject.id)return null;return value;}
var subject=ctx.roles.subject,input=ctx.input,scoreKeys=["str","dex","con","int","wis","cha"],inputKeys=input&&typeof input==="object"&&!Array.isArray(input)?Object.keys(input).sort():[];
if(!subject||!subject.components||typeof subject.components["dnd2024.creature.ability-scores"]!=="string")throw new Error("A raw ability check requires subject ability scores.");
if(inputKeys.length<2||inputKeys.length>4||inputKeys.indexOf("ability")<0||inputKeys.indexOf("dc")<0)throw new Error("Ability-check input must contain ability, dc, and optional skill and rollCircumstances only.");
for(var inputIndex=0;inputIndex<inputKeys.length;inputIndex++)if(inputKeys[inputIndex]!=="ability"&&inputKeys[inputIndex]!=="dc"&&inputKeys[inputIndex]!=="skill"&&inputKeys[inputIndex]!=="rollCircumstances")throw new Error("Ability-check input must contain ability, dc, and optional skill and rollCircumstances only.");
if(typeof input.ability!=="string"||typeof abilities[input.ability]!=="string")throw new Error("ability must be one exact lowercase D&D ability id.");
if(!integer(input.dc,0,2147483637))throw new Error("dc must be an integer from 0 through 2147483637.");
var state;try{state=JSON.parse(subject.components["dnd2024.creature.ability-scores"]);}catch(error){throw new Error("Subject ability scores are corrupt.");}
if(!state||!closed(state,["scores"])||!closed(state.scores,scoreKeys.map(function(key){return abilityRefs[key];})))throw new Error("Subject ability scores must contain exactly six vocabulary-keyed scores.");
for(var keyIndex=0;keyIndex<scoreKeys.length;keyIndex++)if(!integer(state.scores[abilityRefs[scoreKeys[keyIndex]]],1,30))throw new Error("Subject ability scores are invalid.");
var skill=input.hasOwnProperty("skill")?input.skill:null,proficient=null,bonus=null,defaultAbility=null,level=null;
if(skill!==null){if(typeof skill!=="string"||typeof defaults[skill]!=="string")throw new Error("skill must be one exact D&D skill id.");defaultAbility=defaults[skill];if(typeof subject.components["dnd2024.creature.proficiencies"]!=="string")throw new Error("Named skill checks require known character level and skill proficiency state.");var levelState=derivedLevel(subject),proficiencies;try{proficiencies=JSON.parse(subject.components["dnd2024.creature.proficiencies"]);}catch(error){throw new Error("Named skill-check proficiency state is corrupt.");}if(!levelState||!levelState.present||!levelState.valid||!integer(levelState.totalLevel,1,20)||!integer(levelState.proficiencyBonus,2,6))throw new Error("Character level state is invalid.");if(!closed(proficiencies,["entries","recordedFamilies"])||!proficiencies.entries||typeof proficiencies.entries!=="object"||Array.isArray(proficiencies.entries)||!Array.isArray(proficiencies.recordedFamilies)||proficiencies.recordedFamilies.indexOf("skill")<0)throw new Error("Skill-proficiency state is invalid.");var skillEntry=proficiencies.entries["dnd2024.vocabulary.skill."+skill],rank=skillEntry&&skillEntry.rankRef&&skillEntry.rankRef.entityId;if(rank&&rank!=="dnd2024.vocabulary.proficiency-rank.proficiency"&&rank!=="dnd2024.vocabulary.proficiency-rank.expertise")throw new Error("Skill-proficiency state is invalid.");level=levelState.totalLevel;bonus=levelState.proficiencyBonus*(rank==="dnd2024.vocabulary.proficiency-rank.expertise"?2:1);proficient=!!skillEntry;}
var circumstances=input.hasOwnProperty("rollCircumstances")?input.rollCircumstances:[];
if(!Array.isArray(circumstances))throw new Error("rollCircumstances must be an array when supplied.");
if(input.hasOwnProperty("rollCircumstances")&&circumstances.length===0)throw new Error("rollCircumstances must be nonempty when supplied.");
var hasAdvantage=false,hasDisadvantage=false,circumstancePairs={},acceptedCircumstances=[];
for(var circumstanceIndex=0;circumstanceIndex<circumstances.length;circumstanceIndex++){var circumstance=circumstances[circumstanceIndex];if(!closed(circumstance,["kind","source"])||(circumstance.kind!=="advantage"&&circumstance.kind!=="disadvantage")||typeof circumstance.source!=="string"||circumstance.source.length===0||circumstance.source!==circumstance.source.trim()||circumstance.source.indexOf("condition:")===0)throw new Error("Each roll circumstance must be an explicit advantage or disadvantage source.");var pair=circumstance.kind+"\n"+circumstance.source;if(circumstancePairs[pair])throw new Error("rollCircumstances must not repeat the same kind and source.");circumstancePairs[pair]=true;acceptedCircumstances.push({kind:circumstance.kind,source:circumstance.source});if(circumstance.kind==="advantage")hasAdvantage=true;else hasDisadvantage=true;}
var rollMode=hasAdvantage&&hasDisadvantage?"normal":hasAdvantage?"advantage":hasDisadvantage?"disadvantage":"normal",rolls=[ctx.randomInt(1,20)];
if(rollMode!=="normal")rolls.push(ctx.randomInt(1,20));
var roll=rolls.length===1?rolls[0]:rollMode==="advantage"?Math.max(rolls[0],rolls[1]):Math.min(rolls[0],rolls[1]);
var score=state.scores[abilityRefs[input.ability]],modifier=Math.floor((score-10)/2),total=roll+modifier+(proficient?bonus:0),succeeded=total>=input.dc,label=abilities[input.ability]+(skill===null?"":" ("+skill+")"),modifiers=[{source:input.ability+" "+score,value:modifier}];if(proficient)modifiers.push({source:"proficiency (level "+level+"; "+skill+")",value:bonus});
return {narration:subject.name+" makes a "+label+" check: "+roll+" + modifiers = "+total+" vs DC "+input.dc+" ("+(succeeded?"success":"failure")+").",data:{test:"ability-check",ability:input.ability,skill:skill,defaultAbility:defaultAbility,proficient:proficient,dc:input.dc,die:"1d20",rollMode:rollMode,rolls:rolls,roll:roll,rollCircumstances:acceptedCircumstances,modifier:modifier,modifiers:modifiers,total:total,succeeded:succeeded,source:"SRD 5.2.1 - Playing the Game > D20 Tests > Ability Checks"},effects:[],events:[],notifications:[]};
