// D&D 2024 diagnostic Unarmed Strike Damage resolution with no persisted result or HP change.
// Governed by procedure.mechanic.dnd2024.unarmed-strike.damage.
var input=ctx.input,subject=ctx.roles.subject,target=ctx.roles.target,SID='source.dnd2024.srd-5.2.1',LEVEL_LOC='Character Creation > Character Advancement',AC_LOC='Playing the Game > D20 Tests > Attack Rolls > Armor Class',ORDER=['str','dex','con','int','wis','cha'],KEYS=['cha','con','dex','int','str','wis'];
function closed(v,keys){if(v===null||Array.isArray(v)||typeof v!=='object')return false;var a=Object.keys(v).sort();if(a.length!==keys.length)return false;for(var n=0;n<keys.length;n++)if(a[n]!==keys[n])return false;return true;}
function source(v,locator){return closed(v,['locator','sourceId'])&&v.sourceId===SID&&v.locator===locator;}
function parse(raw,name){try{return JSON.parse(raw);}catch(error){throw new Error(name+' is corrupt. Use its governed recording path or migration.');}}
function scores(v){if(!closed(v,KEYS))return false;for(var n=0;n<ORDER.length;n++){var score=v[ORDER[n]];if(typeof score!=='number'||!isFinite(score)||Math.floor(score)!==score||score<1||score>30)return false;}return true;}
function circumstances(v){if(!Array.isArray(v))throw new Error('rollCircumstances must be an array when present.');var out=[],seen={},adv=false,dis=false;for(var n=0;n<v.length;n++){var item=v[n];if(!closed(item,['kind','source'])||(item.kind!=='advantage'&&item.kind!=='disadvantage')||typeof item.source!=='string'||item.source.length===0||item.source.trim()!==item.source)throw new Error('Each roll circumstance must contain only advantage|disadvantage kind and a nonempty trimmed source.');if(item.source.indexOf('condition:')===0)throw new Error('rollCircumstances source prefix condition: is reserved for derived condition state.');var key=item.kind+'\u0000'+item.source;if(seen[key])throw new Error('rollCircumstances must not repeat an exact kind and source pair.');seen[key]=true;out.push({kind:item.kind,source:item.source});if(item.kind==='advantage')adv=true;else dis=true;}return {items:out,advantage:adv,disadvantage:dis};}
function readEffects(child,expectedId,branch){var report;try{report=JSON.parse(child.output&&child.output.data?child.output.data:'{}');}catch(error){throw new Error('Condition state-effects result is unreadable.');}if(!report||typeof report!=='object'||Array.isArray(report)||report.test!=='d20-test-state-effects'||report.subjectId!==expectedId||typeof report.conditionsKnown!=='boolean'||!report.byTest||typeof report.byTest!=='object'||Array.isArray(report.byTest)||!Array.isArray(report.byTest[branch])||!Array.isArray(report.derivedModifiers))throw new Error('Condition state-effects result has an invalid shape.');var derived=report.byTest[branch],modifiers=report.derivedModifiers;for(var n=0;n<derived.length;n++){var item=derived[n];if(!closed(item,['kind','source'])||(item.kind!=='advantage'&&item.kind!=='disadvantage')||typeof item.source!=='string'||item.source.indexOf('condition:')!==0)throw new Error('Condition-derived attack circumstance is invalid.');}for(var m=0;m<modifiers.length;m++){var modifier=modifiers[m],level=modifier&&typeof modifier.value==='number'?-modifier.value/2:0;if(!closed(modifier,['source','value'])||!isFinite(modifier.value)||Math.floor(modifier.value)!==modifier.value||level<1||level>6||Math.floor(level)!==level||modifier.source!=='condition:exhaustion (level '+level+')')throw new Error('Condition-derived attack modifier is invalid.');}return {known:report.conditionsKnown,circumstances:derived,modifiers:modifiers};}
if(!input||typeof input!=='object'||Array.isArray(input)||!closed(input,Object.keys(input).length===0?[]:['rollCircumstances']))throw new Error('Input must be exactly empty or contain only rollCircumstances. Do not supply AC, Proficiency Bonus, Strength, dice, outcomes, damage, position, hands, weapon/profile, Hit Points, or effects.');
var caller=Object.prototype.hasOwnProperty.call(input,'rollCircumstances')?circumstances(input.rollCircumstances):{items:[],advantage:false,disadvantage:false};
if(!subject||!target||!subject.components||!target.components||!subject.components['dnd2024.abilities']||!subject.components['dnd2024.character-level'])throw new Error('Unarmed Strike requires subject abilities and level plus a target.');
var abilityState=parse(subject.components['dnd2024.abilities'],'Subject ability state');if(!scores(abilityState))throw new Error('Subject ability state is invalid.');
var levelState=parse(subject.components['dnd2024.character-level'],'Subject character-level state');if(!closed(levelState,['level','sourceRef'])||typeof levelState.level!=='number'||!isFinite(levelState.level)||Math.floor(levelState.level)!==levelState.level||levelState.level<1||levelState.level>20||!source(levelState.sourceRef,LEVEL_LOC))throw new Error('Subject character-level state is invalid.');
var armorChildren=ctx.children&&ctx.children.targetArmorClass;if(!Array.isArray(armorChildren)||armorChildren.length!==1)throw new Error('Exactly one derived target Armor Class result is required.');var armorReport=parse(armorChildren[0]&&armorChildren[0].output&&armorChildren[0].output.data?armorChildren[0].output.data:null,'Derived target Armor Class result');if(!closed(armorReport,['armorClass','base','shield','sourceRef','subjectId','test'])||armorReport.test!=='armor-class-read'||armorReport.subjectId!==target.id||typeof armorReport.armorClass!=='number'||!isFinite(armorReport.armorClass)||Math.floor(armorReport.armorClass)!==armorReport.armorClass||armorReport.armorClass<1||armorReport.armorClass>9007199254740991)throw new Error('Derived target Armor Class result is invalid.');var armorClass=armorReport.armorClass;
var attackerChildren=ctx.children&&ctx.children.attackerEffects,targetChildren=ctx.children&&ctx.children.targetEffects;if(!Array.isArray(attackerChildren)||attackerChildren.length!==1||!Array.isArray(targetChildren)||targetChildren.length!==1)throw new Error('Exactly one condition state-effects result is required for each Unarmed Strike participant.');
var attacker=readEffects(attackerChildren[0],subject.id,'attackRoll'),defender=readEffects(targetChildren[0],target.id,'attackAgainst'),advantage=caller.advantage,disadvantage=caller.disadvantage,merged=caller.items.concat(attacker.circumstances,defender.circumstances),n;
for(n=0;n<attacker.circumstances.length;n++)if(attacker.circumstances[n].kind==='advantage')advantage=true;else disadvantage=true;
for(n=0;n<defender.circumstances.length;n++)if(defender.circumstances[n].kind==='advantage')advantage=true;else disadvantage=true;
var mode=advantage&&!disadvantage?'advantage':disadvantage&&!advantage?'disadvantage':'normal',rolls=[ctx.randomInt(1,20)];if(mode!=='normal')rolls.push(ctx.randomInt(1,20));var roll=rolls[0];if(mode==='advantage'&&rolls[1]>roll)roll=rolls[1];if(mode==='disadvantage'&&rolls[1]<roll)roll=rolls[1];
var strengthModifier=Math.floor((abilityState.str-10)/2),proficiencyBonus=2+Math.floor((levelState.level-1)/4),modifiers=[{source:'str '+abilityState.str,value:strengthModifier},{source:'unarmed strike proficiency (level '+levelState.level+')',value:proficiencyBonus}];for(n=0;n<attacker.modifiers.length;n++)modifiers.push(attacker.modifiers[n]);var total=roll;for(n=0;n<modifiers.length;n++)total+=modifiers[n].value;var hit=total>=armorClass,critical=false,reason='armor-class';if(roll===20){hit=true;critical=true;reason='natural-20';}else if(roll===1){hit=false;reason='natural-1';}var damageOnHit=Math.max(0,1+strengthModifier),potentialDamage=hit?damageOnHit:0;
ctx.log('Unarmed Strike ('+mode+'): d20 '+roll+', total '+total+' vs AC '+armorClass+', '+reason+'.');
return {narration:subject.name+' makes an unarmed strike against '+target.name+': '+(hit?'hit':'miss')+' ('+reason+').',effects:[],data:{test:'unarmed-strike-damage',subjectId:subject.id,targetId:target.id,ability:'str',targetArmorClass:armorClass,strengthModifier:strengthModifier,proficiencyBonusDerived:proficiencyBonus,proficiencyBonusApplied:proficiencyBonus,modifiers:modifiers,die:'1d20',rollMode:mode,rolls:rolls,roll:roll,rollCircumstances:caller.items,attackerDerivedCircumstances:attacker.circumstances,targetDerivedCircumstances:defender.circumstances,mergedCircumstances:merged,attackerConditionsKnown:attacker.known,targetConditionsKnown:defender.known,total:total,hit:hit,critical:critical,hitReason:reason,damageType:'bludgeoning',damageOnHit:damageOnHit,potentialDamage:potentialDamage,source:'SRD 5.2.1 - Rules Glossary > Unarmed Strike'}};
