var subject=ctx.roles&&ctx.roles.subject,definitionId='dnd2024.character.death-saves';
function object(v){return !!v&&typeof v==='object'&&!Array.isArray(v);}
function exact(v,keys){if(!object(v))return false;var a=Object.keys(v).sort(),e=keys.slice().sort();if(a.length!==e.length)return false;for(var n=0;n<e.length;n++)if(a[n]!==e[n])return false;return true;}
function tally(v){return Number.isInteger(v)&&v>=0&&v<=3;}
function operationRef(v){return exact(v,['operationId'])&&/^[0-9a-f]{32}$/.test(v.operationId);}
function valid(v){if(!object(v))return false;var keys=Object.prototype.hasOwnProperty.call(v,'lastChangeRef')?['status','successes','failures','lastChangeRef']:['status','successes','failures'];return exact(v,keys)&&['dying','stable','dead'].indexOf(v.status)>=0&&tally(v.successes)&&tally(v.failures)&&!(v.status==='stable'&&(v.successes!==0||v.failures!==0))&&(!v.lastChangeRef||operationRef(v.lastChangeRef));}
if(!subject)throw new Error('A subject role is required.');
if(!object(ctx.input)||typeof ctx.input.mode!=='string')throw new Error('Input must be a closed death-state transition object with a mode.');
var raw=subject.components&&subject.components[definitionId],previous=null;if(raw){try{previous=typeof raw==='string'?JSON.parse(raw):raw;}catch(error){throw new Error('The stored death-save state is malformed.');}if(!valid(previous))throw new Error('The stored death-save state is invalid.');}
if(ctx.input.mode==='begin'){if(!exact(ctx.input,['mode']))throw new Error('Beginning death state requires exactly {"mode":"begin"}.');if(previous)throw new Error('Death state is already present and cannot begin again.');var begun={status:'dying',successes:0,failures:0};return {narration:subject.name+' begins death state.',effects:[{type:'component.add',entityId:subject.id,definitionId:definitionId,data:JSON.stringify(begun)}],data:{mode:'begin',previous:null,state:begun}};}
if(ctx.input.mode==='end'){if(!exact(ctx.input,['mode']))throw new Error('Ending death state requires exactly {"mode":"end"}.');if(!previous)throw new Error('Death state is absent and cannot end.');if(previous.status==='dead')throw new Error('Terminal death state cannot end.');return {narration:subject.name+'\'s death state ends.',effects:[{type:'component.remove',entityId:subject.id,definitionId:definitionId}],data:{mode:'end',previous:previous,state:null}};}
if(ctx.input.mode!=='correct'||!exact(ctx.input,['dead','failures','mode','stable','successes']))throw new Error('Correcting death state requires exactly mode, successes, failures, stable, and dead.');
if(!previous)throw new Error('Death state is absent. Use mode "begin".');
var status=ctx.input.dead?'dead':ctx.input.stable?'stable':'dying',corrected={status:status,successes:ctx.input.successes,failures:ctx.input.failures};if(previous.lastChangeRef)corrected.lastChangeRef=previous.lastChangeRef;if(!tally(corrected.successes)||!tally(corrected.failures)||!valid(corrected))throw new Error('Corrected death state is invalid. Stable resets tallies.');if(previous.status==='dead'&&!ctx.input.dead)throw new Error('Terminal death state cannot be cleared.');return {narration:subject.name+'\'s death state is corrected.',effects:[{type:'component.set',entityId:subject.id,definitionId:definitionId,data:JSON.stringify(corrected)}],data:{mode:'correct',previous:previous,state:corrected}};
