var subject=ctx.roles.subject,weapon=ctx.roles.weapon,activity=ctx.roles.activity,input=ctx.input,ABILITIES='dnd2024.creature.ability-scores',MEMBERSHIP='dnd2024.activity.membership',VERSION='dnd2024.core.version',ATTACK='dnd2024.activity.attack',DAMAGE='dnd2024.activity.damage',ACTIVITY_ARCHETYPE='dnd2024.archetype.activity-definition',ABILITY_IDS={str:'dnd2024.vocabulary.ability.strength',dex:'dnd2024.vocabulary.ability.dexterity'},DIE_SIDES={'dnd2024.vocabulary.die.d4':4,'dnd2024.vocabulary.die.d6':6,'dnd2024.vocabulary.die.d8':8,'dnd2024.vocabulary.die.d10':10,'dnd2024.vocabulary.die.d12':12},DAMAGE_TYPES=['bludgeoning','piercing','slashing'];
function object(value){return value!==null&&!Array.isArray(value)&&typeof value==='object';}
function closed(value,keys){if(!object(value))return false;var actual=Object.keys(value).sort(),expected=keys.slice().sort();if(actual.length!==expected.length)return false;for(var n=0;n<expected.length;n++)if(actual[n]!==expected[n])return false;return true;}
function parse(raw,label){try{var value=typeof raw==='string'?JSON.parse(raw):raw;if(!object(value))throw 0;return value;}catch(error){throw new Error(label+' is malformed.');}}
function reference(value){if(!object(value)||typeof value.entityId!=='string'||value.entityId.length<1||value.entityId.length>200)return false;var keys=Object.keys(value).sort();return keys.length===1&&keys[0]==='entityId'||keys.length===2&&keys[0]==='entityId'&&keys[1]==='expectedArchetype'&&typeof value.expectedArchetype==='string';}
function active(value){return object(value)&&Number.isInteger(value.revision)&&value.revision>0&&value.status==='active';}
function membership(value,id){if(!closed(value,['activities'])||!Array.isArray(value.activities))return false;var seen={},found=false;for(var n=0;n<value.activities.length;n++){var item=value.activities[n];if(!reference(item)||seen[item.entityId])return false;seen[item.entityId]=true;if(item.entityId===id){if(item.expectedArchetype!==undefined&&item.expectedArchetype!==ACTIVITY_ARCHETYPE)return false;found=true;}}return found;}
function attackState(value){if(!object(value)||(value.mode!=='melee'&&value.mode!=='ranged')||!Array.isArray(value.abilityOptions)||value.abilityOptions.length<1)return false;var keys=Object.keys(value),allowed={mode:true,abilityOptions:true,classification:true,proficiencySources:true,attackRoll:true,criticalThresholdOverride:true},seen={};for(var n=0;n<keys.length;n++)if(!allowed[keys[n]])return false;for(n=0;n<value.abilityOptions.length;n++){var item=value.abilityOptions[n];if(!reference(item)||(item.entityId!==ABILITY_IDS.str&&item.entityId!==ABILITY_IDS.dex)||seen[item.entityId])return false;seen[item.entityId]=true;}return value.criticalThresholdOverride===undefined||Number.isInteger(value.criticalThresholdOverride)&&value.criticalThresholdOverride>=1&&value.criticalThresholdOverride<=20;}
function damageState(value){if(!object(value)||value.delivery!=='on-hit'||value.criticalBehavior!=='eligible'||!Array.isArray(value.parts)||value.parts.length!==1)return false;var keys=Object.keys(value),allowed={parts:true,delivery:true,criticalBehavior:true,successfulSaveBehavior:true};for(var n=0;n<keys.length;n++)if(!allowed[keys[n]])return false;var part=value.parts[0];if(!closed(part,['amount','damageType'])||!reference(part.damageType))return false;var prefix='dnd2024.vocabulary.damage-type.',type=part.damageType.entityId.indexOf(prefix)===0?part.damageType.entityId.substring(prefix.length):'';if(DAMAGE_TYPES.indexOf(type)<0)return false;if(Number.isInteger(part.amount))return part.amount>=0&&part.amount<=1000;return closed(part.amount,['count','dieRef','modifier'])&&Number.isInteger(part.amount.count)&&part.amount.count>0&&part.amount.count<=100&&reference(part.amount.dieRef)&&DIE_SIDES[part.amount.dieRef.entityId]!==undefined&&Number.isInteger(part.amount.modifier)&&Math.abs(part.amount.modifier)<=1000;}
if(!subject||!weapon||!activity||!closed(input,['ability','critical'])||(input.ability!=='str'&&input.ability!=='dex')||typeof input.critical!=='boolean')throw new Error('Weapon-damage input must contain ability and critical only.');
var abilities=parse(subject.components[ABILITIES],'Attacker abilities'),weaponMembership=parse(weapon.components[MEMBERSHIP],'Weapon activity membership'),activityVersion=parse(activity.components[VERSION],'Activity version'),attack=parse(activity.components[ATTACK],'Attack activity'),damageDefinition=parse(activity.components[DAMAGE],'Damage activity');
if(!object(abilities.scores)||!Number.isInteger(abilities.scores[ABILITY_IDS[input.ability]])||abilities.scores[ABILITY_IDS[input.ability]]<0||abilities.scores[ABILITY_IDS[input.ability]]>100||!membership(weaponMembership,activity.id)||!active(activityVersion)||!attackState(attack)||!damageState(damageDefinition))throw new Error('Weapon-damage state is invalid.');
var abilityAllowed=false;for(var a=0;a<attack.abilityOptions.length;a++)if(attack.abilityOptions[a].entityId===ABILITY_IDS[input.ability])abilityAllowed=true;if(!abilityAllowed)throw new Error('The selected ability is not permitted by this weapon activity.');
var part=damageDefinition.parts[0],prefix='dnd2024.vocabulary.damage-type.',type=part.damageType.entityId.substring(prefix.length),rolls=[],subtotal=0,staticModifier=0,abilityModifier=0,amountKind;
if(Number.isInteger(part.amount)){subtotal=part.amount;amountKind='fixed';}else{amountKind='dice';var sides=DIE_SIDES[part.amount.dieRef.entityId],dice=part.amount.count*(input.critical?2:1);for(var n=0;n<dice;n++){var roll=ctx.randomInt(1,sides);rolls.push(roll);subtotal+=roll;}staticModifier=part.amount.modifier;abilityModifier=Math.floor((abilities.scores[ABILITY_IDS[input.ability]]-10)/2);}
var totalModifier=staticModifier+abilityModifier,resolved=Math.max(0,subtotal+totalModifier);
return {narration:subject.name+' rolls '+activity.name+' damage.',data:{test:'weapon-damage',subjectId:subject.id,weaponId:weapon.id,activityId:activity.id,attackMode:attack.mode,ability:input.ability,abilityRef:ABILITY_IDS[input.ability],critical:input.critical,amountKind:amountKind,type:type,damageTypeRef:part.damageType,rolls:rolls,subtotal:subtotal,staticModifier:staticModifier,abilityModifier:abilityModifier,modifier:totalModifier,damage:resolved},effects:[],events:[],notifications:[]};
