var s=ctx.roles.subject,e=ctx.roles.encounter,i=ctx.input,PART='dnd2024.encounter.participation',ROUND='dnd2024.encounter.round',TURN='dnd2024.encounter.turn',BUDGET='dnd2024.combat.turn-budget',MOVE='dnd2024.creature.movement',ACTOR='encounter.participation.for-actor',MEMBER='encounter.has-participation',HASROUND='encounter.has-round',HASTURN='encounter.has-turn',ACTIVETURN='encounter.active-turn',WALK='dnd2024.vocabulary.movement-mode.walk',METER='dnd2024.vocabulary.distance-unit.meter',MAX=9007199254740991;
function closed(v,k){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length!==k.length)return false;for(var n=0;n<k.length;n++)if(!Object.prototype.hasOwnProperty.call(v,k[n]))return false;return true;}
function id(v){return typeof v==='string'&&v.length>0&&v.length<=200&&v===v.trim();}
function integer(v,min,max){return typeof v==='number'&&isFinite(v)&&Math.floor(v)===v&&v>=min&&v<=max;}
function ref(v){return closed(v,['entityId'])&&id(v.entityId);}
function gcd(a,b){while(b){var r=a%b;a=b;b=r;}return a;}
function fraction(n,d){if(!integer(n,0,1000000000)||!integer(d,1,1000000000))throw new Error('Distance rational is outside the safe boundary.');var g=gcd(n,d);return {n:n/g,d:d/g};}
function add(a,b){var g=gcd(a.d,b.d),left=b.d/g,right=a.d/g,n=a.n*left+b.n*right,d=a.d*left;if(!Number.isSafeInteger(n)||!Number.isSafeInteger(d))throw new Error('Distance arithmetic exceeds the safe boundary.');return fraction(n,d);}
function compare(a,b){var left=a.n*b.d,right=b.n*a.d;if(!Number.isSafeInteger(left)||!Number.isSafeInteger(right))throw new Error('Distance comparison exceeds the safe boundary.');return left-right;}
function subtractFloor(a,b){if(compare(a,b)<=0)return {n:0,d:1};var n=a.n*b.d-b.n*a.d,d=a.d*b.d;if(!Number.isSafeInteger(n)||!Number.isSafeInteger(d))throw new Error('Distance arithmetic exceeds the safe boundary.');return fraction(n,d);}
function measurement(v,positive){if(!closed(v,['dimension','value','unit'])||v.dimension!=='distance'||!closed(v.value,['numerator','denominator'])||!closed(v.unit,['entityId'])||v.unit.entityId!==METER)return null;var f=fraction(v.value.numerator,v.value.denominator);return positive&&f.n===0?null:f;}
function parse(raw,name){try{return typeof raw==='string'?JSON.parse(raw):raw;}catch(error){throw new Error(name+' is corrupt.');}}
function related(role,kind){var all=role.related||[],values=[];for(var n=0;n<all.length;n++)if(all[n].kind===kind)values.push(all[n]);return values;}
function validBudget(v,turnId){if(!closed(v,['turn','remaining','movementSpent','interactionsUsed'])||!ref(v.turn)||v.turn.entityId!==turnId||!closed(v.remaining,['actions','bonusActions','reactions'])||!integer(v.remaining.actions,0,100)||!integer(v.remaining.bonusActions,0,100)||!integer(v.remaining.reactions,0,100)||!Array.isArray(v.movementSpent)||v.movementSpent.length>100||!integer(v.interactionsUsed,0,100))return false;for(var n=0;n<v.movementSpent.length;n++){var x=v.movementSpent[n];if(!closed(x,['mode','distance'])||!ref(x.mode)||measurement(x.distance,false)===null)return false;}return true;}
if(!s||!e||!i||typeof i!=='object'||Array.isArray(i))throw new Error('A subject, encounter, and object input are required.');var resource=i.resource;if(['action','bonusAction','reaction','interaction','movement'].indexOf(resource)<0)throw new Error('resource must be action, bonusAction, reaction, interaction, or movement.');var requested=null;if(resource==='movement'){if(!closed(i,['resource','distance'])||(requested=measurement(i.distance,true))===null)throw new Error('Movement spending requires exactly one positive exact metre distance.');}else if(!closed(i,['resource']))throw new Error('Non-movement spending accepts only resource.');
var subjectParts=related(s,ACTOR),participation=null;for(var pIndex=0;pIndex<subjectParts.length;pIndex++){var candidate=subjectParts[pIndex],state=parse(candidate.components&&candidate.components[PART],'Encounter participation');if(closed(state,['membershipRelationship','status'])&&state.status==='active'&&closed(state.membershipRelationship,['stateSpaceId','fromEntityId','toEntityId','qualifiedKind'])&&state.membershipRelationship.stateSpaceId===ctx.stateSpaceId&&state.membershipRelationship.fromEntityId===e.id&&state.membershipRelationship.toEntityId===candidate.id&&state.membershipRelationship.qualifiedKind==='dnd2024.'+MEMBER){if(participation)throw new Error('The subject has ambiguous encounter participation.');participation=candidate;}}if(!participation)throw new Error('The subject is not an active participant in this encounter.');
var roundRows=related(e,HASROUND),rounds={};for(var rIndex=0;rIndex<roundRows.length;rIndex++){var rr=roundRows[rIndex],round=parse(rr.components&&rr.components[ROUND],'Encounter round');if(!closed(round,['encounter','number','status'])||!ref(round.encounter)||round.encounter.entityId!==e.id||!integer(round.number,1,MAX)||rounds[rr.id])throw new Error('Encounter round history is invalid.');rounds[rr.id]=round;}
var turnRows=related(e,HASTURN),latest=null,latestRound=0,seenRound={};for(var tIndex=0;tIndex<turnRows.length;tIndex++){var tr=turnRows[tIndex],turn=parse(tr.components&&tr.components[TURN],'Encounter turn'),budget=parse(tr.components&&tr.components[BUDGET],'Encounter turn budget');if(!closed(turn,['encounter','round','participant','ordinal','status'])||!ref(turn.encounter)||!ref(turn.round)||!ref(turn.participant)||turn.encounter.entityId!==e.id||!rounds[turn.round.entityId]||!integer(turn.ordinal,0,99)||['active','complete','skipped'].indexOf(turn.status)<0||!validBudget(budget,tr.id))throw new Error('Encounter turn history is invalid.');if(turn.participant.entityId===participation.id){var number=rounds[turn.round.entityId].number;if(seenRound[number])throw new Error('The participant has ambiguous turn history.');seenRound[number]=true;if(number>latestRound){latest={node:tr,turn:turn,budget:budget};latestRound=number;}}}if(!latest)throw new Error('The participant has no turn budget yet.');var activeRows=related(e,ACTIVETURN);if(activeRows.length!==1)throw new Error('Encounter has no single active turn.');var active=activeRows[0],activeTurn=parse(active.components&&active.components[TURN],'Active encounter turn');if(!closed(activeTurn,['encounter','round','participant','ordinal','status'])||activeTurn.status!=='active'||!ref(activeTurn.participant)||activeTurn.encounter.entityId!==e.id)throw new Error('Active encounter turn is invalid.');if(resource!=='reaction'&&(latest.node.id!==active.id||activeTurn.participant.entityId!==participation.id))throw new Error('Only the active participant may spend '+resource+'.');
var kids=ctx.children&&ctx.children.stateEffects;if(!Array.isArray(kids)||kids.length!==1)throw new Error('Exactly one Condition state-effects result is required.');var state;try{state=JSON.parse(kids[0].output&&kids[0].output.data?kids[0].output.data:'{}');}catch(error){throw new Error('Condition state-effects result is unreadable.');}if(!state||state.test!=='d20-test-state-effects'||state.subjectId!==s.id||!integer(state.exhaustionLevel,0,6)||!Array.isArray(state.prohibitions))throw new Error('Condition state-effects result is invalid.');for(var z=0;z<state.prohibitions.length;z++){var prohibition=state.prohibitions[z];if(!closed(prohibition,['resource','reason']))throw new Error('Condition prohibition is invalid.');if(prohibition.resource===resource)throw new Error('The '+resource+' resource is prohibited by '+prohibition.reason+'.');}
var budget=latest.budget,next={turn:budget.turn,remaining:{actions:budget.remaining.actions,bonusActions:budget.remaining.bonusActions,reactions:budget.remaining.reactions},movementSpent:budget.movementSpent.slice(),interactionsUsed:budget.interactionsUsed},before,after,data={test:'turn-budget-spend',encounterId:e.id,subjectId:s.id,participationId:participation.id,turnId:latest.node.id,activeTurnId:active.id,resource:resource};if(resource==='action'||resource==='bonusAction'||resource==='reaction'){var field=resource==='action'?'actions':resource==='bonusAction'?'bonusActions':'reactions';before=next.remaining[field];if(before<1)throw new Error('The '+resource+' resource is already spent.');after=before-1;next.remaining[field]=after;data.before=before;data.after=after;}else if(resource==='interaction'){before=next.interactionsUsed;if(before>=1)throw new Error('The free interaction is already spent.');after=before+1;next.interactionsUsed=after;data.before=before;data.after=after;}else{var movement=parse(s.components&&s.components[MOVE],'Creature movement'),walk=movement&&movement.speeds&&movement.speeds[WALK];if(!walk||!closed(walk,['distance','enabled','sourceRefs'])||walk.enabled!==true||!Array.isArray(walk.sourceRefs))throw new Error('The subject has no valid walk Speed.');var maximum=measurement(walk.distance,false);if(maximum===null)throw new Error('The subject has no valid metric walk Speed.');maximum=subtractFloor(maximum,fraction(381*state.exhaustionLevel,250));var spent={n:0,d:1};for(var m=0;m<next.movementSpent.length;m++)if(next.movementSpent[m].mode.entityId===WALK)spent=add(spent,measurement(next.movementSpent[m].distance,false));after=add(spent,requested);if(compare(after,maximum)>0)throw new Error('The requested movement exceeds the remaining walk allowance.');next.movementSpent.push({mode:{entityId:WALK},distance:i.distance});data.distance=i.distance;data.totalWalkMeters={numerator:after.n,denominator:after.d};data.maximumWalkMeters={numerator:maximum.n,denominator:maximum.d};}
return {narration:s.name+' spends '+resource+'.',data:data,effects:[{type:'component.set',entityId:latest.node.id,definitionId:BUDGET,data:JSON.stringify(next)}],events:[],notifications:[]};
