var weapon=ctx.roles.weapon,activity=ctx.roles.activity,input=ctx.input,WEAPON='dnd2024.item.weapon',MEMBERSHIP='dnd2024.activity.membership',VERSION='dnd2024.core.version',ACTIVATION='dnd2024.activity.activation',ATTACK='dnd2024.activity.attack',DAMAGE='dnd2024.activity.damage',RANGE='dnd2024.activity.range',ACTIVITY_ARCHETYPE='dnd2024.archetype.activity-definition',CATEGORIES=['dnd2024.equipment.weapon-category.simple','dnd2024.equipment.weapon-category.martial'],ABILITIES=['dnd2024.vocabulary.ability.strength','dnd2024.vocabulary.ability.dexterity'],DICE=['dnd2024.vocabulary.die.d4','dnd2024.vocabulary.die.d6','dnd2024.vocabulary.die.d8','dnd2024.vocabulary.die.d10','dnd2024.vocabulary.die.d12'],DAMAGE_TYPES=['dnd2024.vocabulary.damage-type.bludgeoning','dnd2024.vocabulary.damage-type.piercing','dnd2024.vocabulary.damage-type.slashing'];
function object(value){return value!==null&&!Array.isArray(value)&&typeof value==='object';}
function closed(value,keys){if(!object(value))return false;var actual=Object.keys(value).sort(),expected=keys.slice().sort();if(actual.length!==expected.length)return false;for(var n=0;n<expected.length;n++)if(actual[n]!==expected[n])return false;return true;}
function parse(raw,label){try{var value=typeof raw==='string'?JSON.parse(raw):raw;if(!object(value))throw 0;return value;}catch(error){throw new Error(label+' is malformed.');}}
function optional(raw,label){return raw===undefined?null:parse(raw,label);}
function reference(value){if(!object(value)||typeof value.entityId!=='string'||value.entityId.length<1||value.entityId.length>200)return false;var keys=Object.keys(value).sort();return keys.length===1&&keys[0]==='entityId'||keys.length===2&&keys[0]==='entityId'&&keys[1]==='expectedArchetype'&&typeof value.expectedArchetype==='string';}
function weaponState(value){if(!object(value)||!reference(value.category)||CATEGORIES.indexOf(value.category.entityId)<0)return false;var keys=Object.keys(value);for(var n=0;n<keys.length;n++)if(keys[n]!=='category'&&keys[n]!=='properties'&&keys[n]!=='masteryProperty')return false;if(value.properties!==undefined){if(!Array.isArray(value.properties))return false;var seen={};for(n=0;n<value.properties.length;n++){var property=value.properties[n];if(!reference(property)||seen[property.entityId])return false;seen[property.entityId]=true;}}return value.masteryProperty===undefined||reference(value.masteryProperty);}
function membershipState(value){if(!closed(value,['activities'])||!Array.isArray(value.activities))return false;var seen={};for(var n=0;n<value.activities.length;n++){var item=value.activities[n];if(!reference(item)||seen[item.entityId])return false;seen[item.entityId]=true;}return true;}
function versionState(value){if(!object(value)||!Number.isInteger(value.revision)||value.revision<1||value.status!=='active')return false;var keys=Object.keys(value);for(var n=0;n<keys.length;n++)if(keys[n]!=='revision'&&keys[n]!=='status'&&keys[n]!=='supersedesRef'&&keys[n]!=='compatibleWithRefs')return false;return true;}
function abilityList(value){if(!Array.isArray(value)||value.length<1||value.length>ABILITIES.length)throw new Error('abilityIds must be a nonempty duplicate-free canonical ability list.');var selected={},result=[];for(var n=0;n<value.length;n++){if(ABILITIES.indexOf(value[n])<0||selected[value[n]])throw new Error('abilityIds must be a nonempty duplicate-free canonical ability list.');selected[value[n]]=true;}for(n=0;n<ABILITIES.length;n++)if(selected[ABILITIES[n]])result.push({entityId:ABILITIES[n]});return result;}
function damageInput(value){if(!object(value))throw new Error('damage must declare one canonical fixed or dice amount.');if(value.kind==='dice'){if(!closed(value,['count','dieId','kind','typeId'])||!Number.isInteger(value.count)||value.count<1||value.count>100||DICE.indexOf(value.dieId)<0||DAMAGE_TYPES.indexOf(value.typeId)<0)throw new Error('Dice damage is invalid.');return {parts:[{amount:{count:value.count,dieRef:{entityId:value.dieId},modifier:0},damageType:{entityId:value.typeId}}],delivery:'on-hit',criticalBehavior:'eligible'};}if(value.kind==='fixed'){if(!closed(value,['amount','kind','typeId'])||!Number.isInteger(value.amount)||value.amount<0||value.amount>1000||DAMAGE_TYPES.indexOf(value.typeId)<0)throw new Error('Fixed damage is invalid.');return {parts:[{amount:value.amount,damageType:{entityId:value.typeId}}],delivery:'on-hit',criticalBehavior:'eligible'};}throw new Error('damage must declare one canonical fixed or dice amount.');}
function rangeInput(value,mode){var keys=object(value)?Object.keys(value).sort():[],hasLong=keys.length===2&&keys[0]==='longFeet'&&keys[1]==='normalFeet';if(!(keys.length===1&&keys[0]==='normalFeet'||hasLong)||!Number.isInteger(value.normalFeet)||value.normalFeet<1||value.normalFeet>10000)throw new Error('range must declare bounded integer source feet.');if(mode==='melee'&&(hasLong||value.normalFeet!==5&&value.normalFeet!==10))throw new Error('A base melee activity must declare 5- or 10-foot reach only.');if(mode==='ranged'&&(!hasLong||!Number.isInteger(value.longFeet)||value.longFeet<value.normalFeet||value.longFeet>10000))throw new Error('A ranged activity must declare normal and long range.');function gcd(a,b){while(b){var next=a%b;a=b;b=next;}return a;}function measure(feet){var numerator=feet*381,denominator=1250,divisor=gcd(numerator,denominator);return {dimension:'distance',value:{numerator:numerator/divisor,denominator:denominator/divisor},unit:{entityId:'dnd2024.vocabulary.distance-unit.meter'}};}var result={kind:'distance',normal:measure(value.normalFeet)};if(hasLong)result.long=measure(value.longFeet);return {range:result};}
function existingActivation(value){return closed(value,['economy'])&&value.economy==='none';}
function existingAttack(value){if(!closed(value,['abilityOptions','mode'])||(value.mode!=='melee'&&value.mode!=='ranged')||!Array.isArray(value.abilityOptions)||value.abilityOptions.length<1)return false;var seen={};for(var n=0;n<value.abilityOptions.length;n++){var item=value.abilityOptions[n];if(!reference(item)||ABILITIES.indexOf(item.entityId)<0||seen[item.entityId])return false;seen[item.entityId]=true;}return true;}
function existingDamage(value){if(!closed(value,['criticalBehavior','delivery','parts'])||value.delivery!=='on-hit'||value.criticalBehavior!=='eligible'||!Array.isArray(value.parts)||value.parts.length!==1)return false;var part=value.parts[0];if(!closed(part,['amount','damageType'])||!reference(part.damageType)||DAMAGE_TYPES.indexOf(part.damageType.entityId)<0)return false;if(Number.isInteger(part.amount))return part.amount>=0;return closed(part.amount,['count','dieRef','modifier'])&&Number.isInteger(part.amount.count)&&part.amount.count>0&&reference(part.amount.dieRef)&&DICE.indexOf(part.amount.dieRef.entityId)>=0&&Number.isInteger(part.amount.modifier);}
function measurement(value){return closed(value,['dimension','unit','value'])&&value.dimension==='distance'&&closed(value.value,['denominator','numerator'])&&Number.isInteger(value.value.numerator)&&value.value.numerator>0&&Number.isInteger(value.value.denominator)&&value.value.denominator>0&&reference(value.unit)&&value.unit.entityId==='dnd2024.vocabulary.distance-unit.meter';}
function existingRange(value){if(!closed(value,['range'])||!object(value.range)||value.range.kind!=='distance'||!measurement(value.range.normal))return false;var keys=Object.keys(value.range).sort();return keys.length===2&&keys[0]==='kind'&&keys[1]==='normal'||keys.length===3&&keys[0]==='kind'&&keys[1]==='long'&&keys[2]==='normal'&&measurement(value.range.long)&&value.range.long.value.numerator*value.range.normal.value.denominator>=value.range.normal.value.numerator*value.range.long.value.denominator;}
if(!weapon||!activity||!weapon.components||!activity.components||!closed(input,['abilityIds','attackMode','categoryId','damage','mode','range'])||(input.mode!=='record'&&input.mode!=='correct')||CATEGORIES.indexOf(input.categoryId)<0||(input.attackMode!=='melee'&&input.attackMode!=='ranged'))throw new Error('Normalized weapon-profile input is invalid.');
var version=parse(activity.components[VERSION],'Activity version');if(!versionState(version))throw new Error('The selected activity must be active.');
var abilities=abilityList(input.abilityIds),damage=damageInput(input.damage),range=rangeInput(input.range,input.attackMode),attack={mode:input.attackMode,abilityOptions:abilities},activation={economy:'none'},priorWeapon=optional(weapon.components[WEAPON],'Weapon definition'),priorMembership=optional(weapon.components[MEMBERSHIP],'Weapon activity membership'),priorActivation=optional(activity.components[ACTIVATION],'Activity activation'),priorAttack=optional(activity.components[ATTACK],'Attack activity'),priorDamage=optional(activity.components[DAMAGE],'Damage activity'),priorRange=optional(activity.components[RANGE],'Activity range');
if(priorWeapon&&!weaponState(priorWeapon)||priorMembership&&!membershipState(priorMembership)||priorActivation&&!existingActivation(priorActivation)||priorAttack&&!existingAttack(priorAttack)||priorDamage&&!existingDamage(priorDamage)||priorRange&&!existingRange(priorRange))throw new Error('Existing normalized weapon activity state is invalid.');
var member=false,members=priorMembership?priorMembership.activities.slice():[];for(var m=0;m<members.length;m++)if(members[m].entityId===activity.id)member=true;
if(input.mode==='record'&&(member||priorActivation||priorAttack||priorDamage||priorRange))throw new Error('The weapon activity is already recorded.');
if(input.mode==='correct'&&(!priorWeapon||!priorMembership||!member||!priorActivation||!priorAttack||!priorDamage||!priorRange))throw new Error('The weapon activity is absent.');
if(input.mode==='record'&&priorWeapon&&priorWeapon.category.entityId!==input.categoryId)throw new Error('The weapon category conflicts with existing authored state.');
var nextWeapon=priorWeapon||{category:{entityId:input.categoryId}};if(nextWeapon.category.entityId!==input.categoryId){nextWeapon={category:{entityId:input.categoryId}};if(priorWeapon.properties!==undefined)nextWeapon.properties=priorWeapon.properties;if(priorWeapon.masteryProperty!==undefined)nextWeapon.masteryProperty=priorWeapon.masteryProperty;}
if(!member){members.push({entityId:activity.id,expectedArchetype:ACTIVITY_ARCHETYPE});members.sort(function(a,b){return a.entityId<b.entityId?-1:a.entityId>b.entityId?1:0;});}
var effects=[];if(!priorWeapon||priorWeapon.category.entityId!==input.categoryId)effects.push({type:priorWeapon?'component.set':'component.add',entityId:weapon.id,definitionId:WEAPON,data:JSON.stringify(nextWeapon)});if(!member)effects.push({type:priorMembership?'component.set':'component.add',entityId:weapon.id,definitionId:MEMBERSHIP,data:JSON.stringify({activities:members})});function facet(id,prior,value){effects.push({type:prior?'component.set':'component.add',entityId:activity.id,definitionId:id,data:JSON.stringify(value)});}facet(ACTIVATION,priorActivation,activation);facet(ATTACK,priorAttack,attack);facet(DAMAGE,priorDamage,damage);facet(RANGE,priorRange,range);
return {narration:weapon.name+' weapon activity '+(input.mode==='record'?'recorded.':'corrected.'),data:{test:'weapon-profile-write',mode:input.mode,weaponId:weapon.id,activityId:activity.id,categoryId:input.categoryId,attackMode:input.attackMode,abilityIds:abilities.map(function(value){return value.entityId;}),damage:damage,range:range},effects:effects,events:[],notifications:[]};
