var subject=ctx.roles.subject,weapon=ctx.roles.weapon,activity=ctx.roles.activity,target=ctx.roles.target,input=ctx.input,HP='dnd2024.creature.hit-points',TEMP='dnd2024.creature.temporary-hit-points',EPISODE='dnd2024.rest-episode',POLICY='dnd2024.rest-policy',ROOT='game.core.world.root',CLOCK='game.core.world.clock',REST='rest.world',STANDARD_POLICY='dnd2024.content.rest-policy.standard.v1',REST_SOURCE='dnd2024.source.srd-5.2.1',TYPES=['acid','bludgeoning','cold','fire','force','lightning','necrotic','piercing','poison','psychic','radiant','slashing','thunder'],MAX=Number.MAX_SAFE_INTEGER,RESTMAX=1000000000;
function object(value){return value!==null&&!Array.isArray(value)&&typeof value==='object';}
function closed(value,keys){if(!object(value)||Object.keys(value).length!==keys.length)return false;for(var n=0;n<keys.length;n++)if(!Object.prototype.hasOwnProperty.call(value,keys[n]))return false;return true;}
function parse(raw,label){try{var value=typeof raw==='string'?JSON.parse(raw):raw;if(!object(value))throw 0;return value;}catch(error){throw new Error(label+' is corrupt.');}}
function safe(value,minimum){return Number.isSafeInteger(value)&&value>=minimum&&value<=MAX;}
function reference(value){return object(value)&&typeof value.entityId==='string'&&value.entityId.length>0&&value.entityId.length<=200&&Object.keys(value).every(function(key){return key==='entityId'||key==='expectedArchetype';});}
function damageTypes(values){if(!Array.isArray(values)||values.length>TYPES.length)return false;var seen={};for(var n=0;n<values.length;n++){if(TYPES.indexOf(values[n])<0||seen[values[n]])return false;seen[values[n]]=true;}return true;}
function integer(value,minimum,maximum){return Number.isSafeInteger(value)&&value>=minimum&&value<=maximum;}
function exactSource(value,locator){return closed(value,['sourceId','locator'])&&value.sourceId===REST_SOURCE&&value.locator===locator;}
function validClock(value){return closed(value,['calendarId','currentMinute','revision'])&&typeof value.calendarId==='string'&&value.calendarId.length>0&&value.calendarId.length<=100&&integer(value.currentMinute,0,RESTMAX)&&integer(value.revision,0,2147483647);}
function validPolicy(value){return closed(value,['longRest','policyKey','policyVersion','shortRest','sourceRef'])&&value.policyKey==='standard'&&value.policyVersion===1&&exactSource(value.sourceRef,'Rules Glossary > Long Rest and Short Rest, PDF pages 185 and 187')&&closed(value.shortRest,['benefits','interruptions','minimumHitPoints','minimumMinutes','permittedActivity'])&&value.shortRest.minimumMinutes===60&&value.shortRest.minimumHitPoints===1&&value.shortRest.permittedActivity==='light'&&JSON.stringify(value.shortRest.interruptions)===JSON.stringify(['initiative','non-cantrip-spell','damage'])&&closed(value.longRest,['additionalMinutesPerInterruption','benefits','interruptions','maximumLightActivityMinutes','minimumHitPoints','minimumMinutes','minimumSleepMinutes','partialShortRestMinutes','permittedActivity','restartWaitMinutes'])&&value.longRest.minimumMinutes===480&&value.longRest.minimumSleepMinutes===360&&value.longRest.maximumLightActivityMinutes===120&&value.longRest.minimumHitPoints===1&&value.longRest.restartWaitMinutes===960&&value.longRest.partialShortRestMinutes===60&&value.longRest.additionalMinutesPerInterruption===60&&value.longRest.permittedActivity==='light'&&JSON.stringify(value.longRest.interruptions)===JSON.stringify(['initiative','non-cantrip-spell','damage','walking-or-physical-exertion']);}
function validEpisode(value,policy){if(!object(value)||value.policyEntityId!==STANDARD_POLICY||typeof value.worldId!=='string'||value.worldId.length===0||value.worldId.length>200||!integer(value.startedAtMinute,0,RESTMAX)||!integer(value.observedAtMinute,value.startedAtMinute,RESTMAX)||!integer(value.observedClockRevision,0,2147483647)||(value.status!=='active'&&value.status!=='ready'))return false;var elapsed=value.observedAtMinute-value.startedAtMinute;if(value.kind==='short')return closed(value,['kind','lightActivityMinutes','observedAtMinute','observedClockRevision','policyEntityId','requiredMinutes','sourceRef','startedAtMinute','status','worldId'])&&value.requiredMinutes===policy.shortRest.minimumMinutes&&integer(value.lightActivityMinutes,0,RESTMAX)&&value.lightActivityMinutes===elapsed&&exactSource(value.sourceRef,'Rules Glossary > Short Rest, PDF page 187')&&(value.status==='ready')===(value.lightActivityMinutes>=value.requiredMinutes);if(value.kind!=='long'||!closed(value,['interruptionCount','kind','lightActivityMinutes','observedAtMinute','observedClockRevision','policyEntityId','requiredMinutes','sleepMinutes','sourceRef','startedAtMinute','status','worldId'])||!integer(value.sleepMinutes,0,RESTMAX)||!integer(value.lightActivityMinutes,0,policy.longRest.maximumLightActivityMinutes)||!integer(value.interruptionCount,0,16666658)||value.requiredMinutes!==policy.longRest.minimumMinutes+policy.longRest.additionalMinutesPerInterruption*value.interruptionCount||value.requiredMinutes>RESTMAX||value.sleepMinutes+value.lightActivityMinutes!==elapsed||!exactSource(value.sourceRef,'Rules Glossary > Long Rest, PDF page 185'))return false;var ready=elapsed>=value.requiredMinutes&&value.sleepMinutes>=policy.longRest.minimumSleepMinutes&&value.lightActivityMinutes<=policy.longRest.maximumLightActivityMinutes;return (value.status==='ready')===ready;}
function damageRestInterruption(finalDamage,effects){if(finalDamage===0||!Object.prototype.hasOwnProperty.call(target.components,EPISODE))return null;var episode=parse(target.components[EPISODE],'Rest episode'),policyReference=ctx.references&&ctx.references[episode.policyEntityId],policy=policyReference&&parse(policyReference.components[POLICY],'Rest policy');if(!policyReference||policyReference.id!==STANDARD_POLICY||!validPolicy(policy)||!validEpisode(episode,policy))throw new Error('Damage requires valid rest policy and episode state.');var related=target.related||[],memberships=[];for(var index=0;index<related.length;index++){var candidate=related[index];if(candidate.kind===REST&&candidate.fromEntityId===candidate.id&&candidate.toEntityId===target.id)memberships.push(candidate);}if(memberships.length!==1||memberships[0].data!=='{}')throw new Error('Rest episode requires exactly one matching world membership.');var world=memberships[0],root=parse(world.components[ROOT],'World root'),clock=parse(world.components[CLOCK],'World clock');if(!closed(root,['status','summary','visibility'])||root.status!=='active'||!validClock(clock)||episode.worldId!==world.id||clock.currentMinute!==episode.observedAtMinute||clock.revision!==episode.observedClockRevision)throw new Error('Damage rest context is invalid or stale.');if(episode.status==='ready')return null;var interruptions=episode.kind==='short'?policy.shortRest.interruptions:policy.longRest.interruptions;if(interruptions.indexOf('damage')<0)throw new Error('Damage is not a permitted rest interruption.');if(episode.kind==='short'){effects.push({type:'component.remove',entityId:target.id,definitionId:EPISODE},{type:'relationship.remove',entityId:world.id,toEntityId:target.id,kind:REST});return {outcome:'short-stopped',worldId:world.id,benefitsGranted:false};}if(episode.requiredMinutes>RESTMAX-policy.longRest.additionalMinutesPerInterruption||episode.interruptionCount>=16666658)throw new Error('Long Rest interruption exceeds the supported duration bounds.');var next={policyEntityId:episode.policyEntityId,kind:'long',worldId:episode.worldId,startedAtMinute:episode.startedAtMinute,observedAtMinute:episode.observedAtMinute,observedClockRevision:episode.observedClockRevision,requiredMinutes:episode.requiredMinutes+policy.longRest.additionalMinutesPerInterruption,sleepMinutes:episode.sleepMinutes,lightActivityMinutes:episode.lightActivityMinutes,interruptionCount:episode.interruptionCount+1,status:'active',sourceRef:episode.sourceRef};effects.push({type:'component.set',entityId:target.id,definitionId:EPISODE,data:JSON.stringify(next)});return {outcome:'long-resumed',worldId:world.id,interruptionCount:next.interruptionCount,requiredMinutes:next.requiredMinutes,benefitsGranted:false};}
if(!subject||!weapon||!activity||!target||!closed(input,['ability','critical'])||(input.ability!=='str'&&input.ability!=='dex')||typeof input.critical!=='boolean')throw new Error('Weapon damage application requires exact roles and ability/critical input.');
var hp=parse(target.components[HP],'Target Hit Points'),hpKeys=Object.keys(hp).sort().join(',');
if((hpKeys!=='current,maximum'&&hpKeys!=='current,maximum,maximumReduction')||!safe(hp.current,0)||!safe(hp.maximum,1)||hp.current>hp.maximum||hp.maximumReduction!==undefined&&!safe(hp.maximumReduction,0))throw new Error('Target Hit Points are invalid.');
var damageChildren=ctx.children&&ctx.children.damage,mitigationChildren=ctx.children&&ctx.children.mitigation;
if(!Array.isArray(damageChildren)||damageChildren.length!==1||!Array.isArray(mitigationChildren)||mitigationChildren.length!==1)throw new Error('Exactly one damage and mitigation child are required.');
var damageEntry=damageChildren[0],damage=parse(damageEntry.output&&damageEntry.output.data,'Damage child');
if(!damageEntry.roleEntityIds||damageEntry.roleEntityIds.subject!==subject.id||damageEntry.roleEntityIds.weapon!==weapon.id||damageEntry.roleEntityIds.activity!==activity.id||damage.test!=='weapon-damage'||damage.subjectId!==subject.id||damage.weaponId!==weapon.id||damage.activityId!==activity.id||damage.ability!==input.ability||damage.critical!==input.critical||TYPES.indexOf(damage.type)<0||!safe(damage.damage,0))throw new Error('Damage child is invalid for this action.');
var mitigationEntry=mitigationChildren[0],mitigation=parse(mitigationEntry.output&&mitigationEntry.output.data,'Mitigation child');
if(!mitigationEntry.roleEntityIds||mitigationEntry.roleEntityIds.defender!==target.id||mitigation.test!=='damage-mitigation-profile'||mitigation.defenderId!==target.id||typeof mitigation.mitigationKnown!=='boolean'||typeof mitigation.conditionsKnown!=='boolean'||typeof mitigation.petrified!=='boolean'||!damageTypes(mitigation.immunities)||!damageTypes(mitigation.resistances)||!damageTypes(mitigation.vulnerabilities))throw new Error('Mitigation child is invalid for this target.');
if(!mitigation.mitigationKnown&&(mitigation.immunities.length||mitigation.resistances.length||mitigation.vulnerabilities.length)||!mitigation.conditionsKnown&&mitigation.petrified)throw new Error('Mitigation child claims unavailable state.');
var raw=damage.damage,immune=mitigation.immunities.indexOf(damage.type)>=0,reasons=[];
if(mitigation.resistances.indexOf(damage.type)>=0)reasons.push('damage-mitigation:'+damage.type);
if(mitigation.petrified)reasons.push('condition:petrified');
var resistanceApplied=!immune&&reasons.length>0,vulnerabilityApplied=!immune&&mitigation.vulnerabilities.indexOf(damage.type)>=0,finalDamage=immune?0:raw;
if(resistanceApplied)finalDamage=Math.floor(finalDamage/2);
if(vulnerabilityApplied){if(finalDamage>Math.floor(MAX/2))throw new Error('Vulnerability exceeds the safe damage limit.');finalDamage*=2;}
var temporaryRaw=target.components[TEMP],temporary=temporaryRaw?parse(temporaryRaw,'Target Temporary Hit Points'):null;
if(temporary&&(!closed(temporary,['amount','sourceRef'])||!safe(temporary.amount,1)||!reference(temporary.sourceRef)))throw new Error('Target Temporary Hit Points are invalid.');
var temporaryBefore=temporary?temporary.amount:0,temporaryAbsorbed=Math.min(temporaryBefore,finalDamage),temporaryAfter=temporaryBefore-temporaryAbsorbed,hitPointDamage=finalDamage-temporaryAbsorbed,after={current:Math.max(0,hp.current-hitPointDamage),maximum:hp.maximum},overkill=Math.max(0,hitPointDamage-hp.current),effects=[];
if(hp.maximumReduction!==undefined)after.maximumReduction=hp.maximumReduction;
if(temporaryAbsorbed>0){if(temporaryAfter>0)effects.push({type:'component.set',entityId:target.id,definitionId:TEMP,data:JSON.stringify({amount:temporaryAfter,sourceRef:temporary.sourceRef})});else effects.push({type:'component.remove',entityId:target.id,definitionId:TEMP});}
if(hitPointDamage>0)effects.push({type:'component.set',entityId:target.id,definitionId:HP,data:JSON.stringify(after)});
var restInterruption=damageRestInterruption(finalDamage,effects);
return {narration:target.name+' takes '+finalDamage+' weapon damage.',effects:effects,events:[],notifications:[],data:{test:'weapon-damage-apply',subjectId:subject.id,weaponId:weapon.id,activityId:activity.id,targetId:target.id,rawDamage:raw,damage:finalDamage,type:damage.type,immune:immune,resistanceApplied:resistanceApplied,resistanceReasons:reasons,vulnerabilityApplied:vulnerabilityApplied,temporaryBefore:temporaryBefore,temporaryAfter:temporaryAfter,temporaryAbsorbed:temporaryAbsorbed,hitPointDamage:hitPointDamage,beforeCurrent:hp.current,afterCurrent:after.current,maximum:hp.maximum,overkill:overkill,mitigationChildMechanicId:'dnd2024.mechanic.damage.resolve',restInterruption:restInterruption}};
