var s=ctx.roles.subject,w=ctx.roles.weapon,t=ctx.roles.target,i=ctx.input,SID='source.dnd2024.srd-5.2.1',HLOC='Playing the Game > Damage and Healing > Hit Points',TLOC='Playing the Game > Damage and Healing > Temporary Hit Points (PDF p. 18)',MLOC='Playing the Game > Damage and Healing > Resistance and Vulnerability; Immunity (PDF p. 17)',PLOC='Rules Glossary > Petrified > Resist Damage (PDF p. 186)',TYPES=['acid','bludgeoning','cold','fire','force','lightning','necrotic','piercing','poison','psychic','radiant','slashing','thunder'],MAX=9007199254740991;
function closed(v,k){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length!==k.length)return false;for(var x=0;x<k.length;x++)if(!Object.prototype.hasOwnProperty.call(v,k[x]))return false;return true;}
function parse(raw,label){try{return typeof raw==='string'?JSON.parse(raw):raw;}catch(error){throw new Error(label+' is corrupt.');}}
function safe(v,min){return typeof v==='number'&&isFinite(v)&&Math.floor(v)===v&&v>=min&&v<=MAX;}
function source(v,loc){return closed(v,['sourceId','locator'])&&v.sourceId===SID&&v.locator===loc;}
function ordered(v){if(!Array.isArray(v)||v.length>TYPES.length)return false;var previous=-1,n,index;for(n=0;n<v.length;n++){index=TYPES.indexOf(v[n]);if(index<=previous)return false;previous=index;}return true;}
function has(v,x){return v.indexOf(x)>=0;}
if(!s||!w||!t||!closed(i,['ability','critical'])||(i.ability!=='str'&&i.ability!=='dex')||typeof i.critical!=='boolean')throw new Error('Weapon damage application requires exact roles and ability/critical input.');
var hp=parse(t.components&&t.components['dnd2024.hit-points'],'Target Hit Points');if(!closed(hp,['current','maximum','sourceRef'])||!safe(hp.current,0)||!safe(hp.maximum,1)||hp.current>hp.maximum||!source(hp.sourceRef,HLOC))throw new Error('Target Hit Points are invalid.');
var damageChildren=ctx.children&&ctx.children.damage,mitigationChildren=ctx.children&&ctx.children.mitigation;if(!Array.isArray(damageChildren)||damageChildren.length!==1||!Array.isArray(mitigationChildren)||mitigationChildren.length!==1)throw new Error('Weapon damage application requires exactly one damage and one mitigation child.');
var damageEntry=damageChildren[0],child=parse(damageEntry.output&&damageEntry.output.data,'Damage child');if(!damageEntry.roleEntityIds||damageEntry.roleEntityIds.subject!==s.id||damageEntry.roleEntityIds.weapon!==w.id||!closed(child,['test','subjectId','weaponId','ability','critical','type','rolls','subtotal','modifier','damage'])||child.test!=='weapon-damage'||child.subjectId!==s.id||child.weaponId!==w.id||child.ability!==i.ability||child.critical!==i.critical||TYPES.indexOf(child.type)<0||!safe(child.damage,0))throw new Error('Damage child is invalid for this action.');
var mitigationEntry=mitigationChildren[0],profile=parse(mitigationEntry.output&&mitigationEntry.output.data,'Mitigation child');if(!mitigationEntry.roleEntityIds||mitigationEntry.roleEntityIds.defender!==t.id||!closed(profile,['test','defenderId','mitigationKnown','conditionsKnown','immunities','resistances','vulnerabilities','petrified','sourceRef','petrifiedSourceRef'])||profile.test!=='damage-mitigation-profile'||profile.defenderId!==t.id||typeof profile.mitigationKnown!=='boolean'||typeof profile.conditionsKnown!=='boolean'||typeof profile.petrified!=='boolean'||!ordered(profile.immunities)||!ordered(profile.resistances)||!ordered(profile.vulnerabilities)||!source(profile.sourceRef,MLOC)||!source(profile.petrifiedSourceRef,PLOC)||(!profile.mitigationKnown&&(profile.immunities.length||profile.resistances.length||profile.vulnerabilities.length))||(!profile.conditionsKnown&&profile.petrified))throw new Error('Mitigation child is invalid for this target.');
var raw=child.damage,immune=has(profile.immunities,child.type),reasons=[];if(has(profile.resistances,child.type))reasons.push('damage-mitigation:'+child.type);if(profile.petrified)reasons.push('condition:petrified');var resistanceApplied=!immune&&reasons.length>0,vulnerabilityApplied=!immune&&has(profile.vulnerabilities,child.type),finalDamage=immune?0:raw;if(resistanceApplied)finalDamage=Math.floor(finalDamage/2);if(vulnerabilityApplied){if(finalDamage>Math.floor(MAX/2))throw new Error('Vulnerability would exceed the safe damage limit.');finalDamage*=2;}
var temporaryRaw=t.components&&t.components['dnd2024.temporary-hit-points'],temporary=null;if(temporaryRaw){temporary=parse(temporaryRaw,'Target Temporary Hit Points');if(!closed(temporary,['amount','sourceRef'])||!safe(temporary.amount,1)||!source(temporary.sourceRef,TLOC))throw new Error('Target Temporary Hit Points are invalid.');}
var temporaryBefore=temporary?temporary.amount:0,temporaryAbsorbed=Math.min(temporaryBefore,finalDamage),temporaryAfter=temporaryBefore-temporaryAbsorbed,hitPointDamage=finalDamage-temporaryAbsorbed,after={current:Math.max(0,hp.current-hitPointDamage),maximum:hp.maximum,sourceRef:hp.sourceRef},overkill=Math.max(0,hitPointDamage-hp.current),effects=[];
if(temporaryAbsorbed>0){if(temporaryAfter>0)effects.push({type:'component.set',entityId:t.id,definitionId:'dnd2024.temporary-hit-points',data:JSON.stringify({amount:temporaryAfter,sourceRef:temporary.sourceRef})});else effects.push({type:'component.remove',entityId:t.id,definitionId:'dnd2024.temporary-hit-points'});}
if(hitPointDamage>0)effects.push({type:'component.set',entityId:t.id,definitionId:'dnd2024.hit-points',data:JSON.stringify(after)});
return {narration:t.name+' takes '+finalDamage+' weapon damage.',data:{test:'weapon-damage-apply',rawDamage:raw,damage:finalDamage,type:child.type,immune:immune,resistanceApplied:resistanceApplied,resistanceReasons:reasons,vulnerabilityApplied:vulnerabilityApplied,temporaryBefore:temporaryBefore,temporaryAfter:temporaryAfter,temporaryAbsorbed:temporaryAbsorbed,hitPointDamage:hitPointDamage,beforeCurrent:hp.current,afterCurrent:after.current,maximum:hp.maximum,overkill:overkill,mitigationChildMechanicId:'mechanic.dnd2024.damage.resolve'},effects:effects,events:[],notifications:[]};
