var subject=ctx.roles.subject,weapon=ctx.roles.weapon,activity=ctx.roles.activity,target=ctx.roles.target,input=ctx.input,HP='dnd2024.creature.hit-points',TEMP='dnd2024.creature.temporary-hit-points',TYPES=['acid','bludgeoning','cold','fire','force','lightning','necrotic','piercing','poison','psychic','radiant','slashing','thunder'],MAX=Number.MAX_SAFE_INTEGER;
function object(value){return value!==null&&!Array.isArray(value)&&typeof value==='object';}
function closed(value,keys){if(!object(value)||Object.keys(value).length!==keys.length)return false;for(var n=0;n<keys.length;n++)if(!Object.prototype.hasOwnProperty.call(value,keys[n]))return false;return true;}
function parse(raw,label){try{var value=typeof raw==='string'?JSON.parse(raw):raw;if(!object(value))throw 0;return value;}catch(error){throw new Error(label+' is corrupt.');}}
function safe(value,minimum){return Number.isSafeInteger(value)&&value>=minimum&&value<=MAX;}
function reference(value){return object(value)&&typeof value.entityId==='string'&&value.entityId.length>0&&value.entityId.length<=200&&Object.keys(value).every(function(key){return key==='entityId'||key==='expectedArchetype';});}
function damageTypes(values){if(!Array.isArray(values)||values.length>TYPES.length)return false;var seen={};for(var n=0;n<values.length;n++){if(TYPES.indexOf(values[n])<0||seen[values[n]])return false;seen[values[n]]=true;}return true;}
if(!subject||!weapon||!activity||!target||!closed(input,['ability','critical'])||(input.ability!=='str'&&input.ability!=='dex')||typeof input.critical!=='boolean')throw new Error('Weapon damage application requires exact roles and ability/critical input.');
var hp=parse(target.components[HP],'Target Hit Points'),hpKeys=Object.keys(hp).sort().join(',');
if((hpKeys!=='current,maximum'&&hpKeys!=='current,maximum,maximumReduction')||!safe(hp.current,0)||!safe(hp.maximum,1)||hp.current>hp.maximum||hp.maximumReduction!==undefined&&!safe(hp.maximumReduction,0))throw new Error('Target Hit Points are invalid.');
var damageChildren=ctx.children&&ctx.children.damage,mitigationChildren=ctx.children&&ctx.children.mitigation;
if(!Array.isArray(damageChildren)||damageChildren.length!==1||!Array.isArray(mitigationChildren)||mitigationChildren.length!==1)throw new Error('Exactly one damage and mitigation child are required.');
var damageEntry=damageChildren[0],damage=parse(damageEntry.output&&damageEntry.output.data,'Damage child');
if(!damageEntry.roleEntityIds||damageEntry.roleEntityIds.subject!==subject.id||damageEntry.roleEntityIds.weapon!==weapon.id||damageEntry.roleEntityIds.activity!==activity.id||damage.test!=='weapon-damage'||damage.subjectId!==subject.id||damage.weaponId!==weapon.id||damage.activityId!==activity.id||damage.ability!==input.ability||damage.critical!==input.critical||TYPES.indexOf(damage.type)<0||!safe(damage.damage,0))throw new Error('Damage child is invalid for this action.');
var mitigationEntry=mitigationChildren[0],mitigation=parse(mitigationEntry.output&&mitigationEntry.output.data,'Mitigation child');
if(!mitigationEntry.roleEntityIds||mitigationEntry.roleEntityIds.defender!==target.id||mitigation.test!=='damage-mitigation-profile'||mitigation.defenderId!==target.id||typeof mitigation.mitigationKnown!=='boolean'||typeof mitigation.conditionsKnown!=='boolean'||typeof mitigation.petrified!=='boolean'||!damageTypes(mitigation.immunities)||!damageTypes(mitigation.resistances)||!damageTypes(mitigation.vulnerabilities))throw new Error('Mitigation child is invalid for this target.');
if(!mitigation.mitigationKnown&&(mitigation.immunities.length||mitigation.resistances.length||mitigation.vulnerabilities.length)||!mitigation.conditionsKnown&&mitigation.petrified)throw new Error('Mitigation child claims unavailable state.');
var raw=damage.damage,immune=mitigation.immunities.indexOf(damage.type)>=0,reasons=[];
if(mitigation.resistances.indexOf(damage.type)>=0)reasons.push('damage-mitigation:'+damage.type);
if(mitigation.petrified)reasons.push('condition:petrified');
var resistanceApplied=!immune&&reasons.length>0,vulnerabilityApplied=!immune&&mitigation.vulnerabilities.indexOf(damage.type)>=0,finalDamage=immune?0:raw;
if(resistanceApplied)finalDamage=Math.floor(finalDamage/2);
if(vulnerabilityApplied){if(finalDamage>Math.floor(MAX/2))throw new Error('Vulnerability exceeds the safe damage limit.');finalDamage*=2;}
var temporaryRaw=target.components[TEMP],temporary=temporaryRaw?parse(temporaryRaw,'Target Temporary Hit Points'):null;
if(temporary&&(!closed(temporary,['amount','sourceRef'])||!safe(temporary.amount,1)||!reference(temporary.sourceRef)))throw new Error('Target Temporary Hit Points are invalid.');
var temporaryBefore=temporary?temporary.amount:0,temporaryAbsorbed=Math.min(temporaryBefore,finalDamage),temporaryAfter=temporaryBefore-temporaryAbsorbed,hitPointDamage=finalDamage-temporaryAbsorbed,after={current:Math.max(0,hp.current-hitPointDamage),maximum:hp.maximum},overkill=Math.max(0,hitPointDamage-hp.current),effects=[];
if(hp.maximumReduction!==undefined)after.maximumReduction=hp.maximumReduction;
if(temporaryAbsorbed>0){if(temporaryAfter>0)effects.push({type:'component.set',entityId:target.id,definitionId:TEMP,data:JSON.stringify({amount:temporaryAfter,sourceRef:temporary.sourceRef})});else effects.push({type:'component.remove',entityId:target.id,definitionId:TEMP});}
if(hitPointDamage>0)effects.push({type:'component.set',entityId:target.id,definitionId:HP,data:JSON.stringify(after)});
return {narration:target.name+' takes '+finalDamage+' weapon damage.',effects:effects,events:[],notifications:[],data:{test:'weapon-damage-apply',subjectId:subject.id,weaponId:weapon.id,activityId:activity.id,targetId:target.id,rawDamage:raw,damage:finalDamage,type:damage.type,immune:immune,resistanceApplied:resistanceApplied,resistanceReasons:reasons,vulnerabilityApplied:vulnerabilityApplied,temporaryBefore:temporaryBefore,temporaryAfter:temporaryAfter,temporaryAbsorbed:temporaryAbsorbed,hitPointDamage:hitPointDamage,beforeCurrent:hp.current,afterCurrent:after.current,maximum:hp.maximum,overkill:overkill,mitigationChildMechanicId:'mechanic.dnd2024.damage.resolve',restInterruption:null}};
