var DEF='dnd2024.damage-mitigation',SID='source.dnd2024.srd-5.2.1',LOC='Playing the Game > Damage and Healing > Resistance and Vulnerability; Immunity (PDF p. 17)',ORDER=['acid','bludgeoning','cold','fire','force','lightning','necrotic','piercing','poison','psychic','radiant','slashing','thunder'],s=ctx.roles.subject,i=ctx.input;
function closed(v,keys){if(!v||typeof v!=='object'||Array.isArray(v))return false;var actual=Object.keys(v).sort(),expected=keys.slice().sort(),n;if(actual.length!==expected.length)return false;for(n=0;n<expected.length;n++)if(actual[n]!==expected[n])return false;return true;}
function canonical(v){if(!Array.isArray(v)||v.length>ORDER.length)return null;var seen={},result=[],n,type;for(n=0;n<v.length;n++){type=v[n];if(ORDER.indexOf(type)<0||seen[type])return null;seen[type]=true;result.push(type);}result.sort(function(a,b){return ORDER.indexOf(a)-ORDER.indexOf(b);});return result;}
function ordered(v){var normalized=canonical(v),n;if(!normalized||normalized.length!==v.length)return false;for(n=0;n<v.length;n++)if(v[n]!==normalized[n])return false;return true;}
function source(v){return closed(v,['sourceId','locator'])&&v.sourceId===SID&&v.locator===LOC;}
function valid(v){return closed(v,['resistances','immunities','vulnerabilities','sourceRef'])&&ordered(v.resistances)&&ordered(v.immunities)&&ordered(v.vulnerabilities)&&source(v.sourceRef);}
function parse(raw){try{return typeof raw==='string'?JSON.parse(raw):raw;}catch(error){throw new Error('The existing damage-mitigation component is malformed.');}}
if(!s)throw new Error('A subject role is required.');
if(!closed(i,['mode','resistances','immunities','vulnerabilities'])||(i.mode!=='record'&&i.mode!=='correct'))throw new Error('Input must contain exactly record/correct mode and complete resistance, immunity, and vulnerability lists.');
var resistances=canonical(i.resistances),immunities=canonical(i.immunities),vulnerabilities=canonical(i.vulnerabilities);if(!resistances||!immunities||!vulnerabilities)throw new Error('Each mitigation list must contain only unique canonical D&D 2024 damage types.');
var present=!!(s.components&&Object.prototype.hasOwnProperty.call(s.components,DEF)),previous=null;if(present){previous=parse(s.components[DEF]);if(!valid(previous))throw new Error('The existing damage-mitigation component is invalid and cannot be corrected.');}
if(i.mode==='record'&&present)throw new Error('Damage mitigation is already recorded. Use correct mode.');if(i.mode==='correct'&&!present)throw new Error('Damage mitigation is absent. Use record mode.');
var next={resistances:resistances,immunities:immunities,vulnerabilities:vulnerabilities,sourceRef:{sourceId:SID,locator:LOC}};
return {narration:s.name+' damage mitigation is '+(i.mode==='record'?'recorded.':'corrected.'),data:{mode:i.mode,resistances:next.resistances,immunities:next.immunities,vulnerabilities:next.vulnerabilities,previous:previous,sourceRef:next.sourceRef},effects:[{type:i.mode==='record'?'component.add':'component.set',entityId:s.id,definitionId:DEF,data:JSON.stringify(next)}],events:[],notifications:[]};
