var SID='source.dnd2024.srd-5.2.1',LOC='Playing the Game > Damage and Healing > Resistance and Vulnerability; Immunity (PDF p. 17)',PLOC='Rules Glossary > Petrified > Resist Damage (PDF p. 186)',CLOC='Rules Glossary',DEF='dnd2024.damage-mitigation',TYPES=['acid','bludgeoning','cold','fire','force','lightning','necrotic','piercing','poison','psychic','radiant','slashing','thunder'],CONDITIONS=['blinded','charmed','deafened','frightened','grappled','incapacitated','invisible','paralyzed','petrified','poisoned','prone','restrained','stunned','unconscious','exhaustion'],d=ctx.roles.defender,i=ctx.input;
function closed(v,keys){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length!==keys.length)return false;for(var n=0;n<keys.length;n++)if(!Object.prototype.hasOwnProperty.call(v,keys[n]))return false;return true;}
function source(v,locator){return closed(v,['sourceId','locator'])&&v.sourceId===SID&&v.locator===locator;}
function ordered(v,order){if(!Array.isArray(v)||v.length>order.length)return false;var previous=-1,n,index;for(n=0;n<v.length;n++){index=order.indexOf(v[n]);if(index<=previous)return false;previous=index;}return true;}
function valid(v){return closed(v,['resistances','immunities','vulnerabilities','sourceRef'])&&ordered(v.resistances,TYPES)&&ordered(v.immunities,TYPES)&&ordered(v.vulnerabilities,TYPES)&&source(v.sourceRef,LOC);}
function parse(raw,label){try{return typeof raw==='string'?JSON.parse(raw):raw;}catch(error){throw new Error('The '+label+' data is malformed.');}}
if(!d)throw new Error('A defender role is required.');if(!closed(i,[]))throw new Error('Reading a damage-mitigation profile requires exactly an empty object input.');
var present=!!(d.components&&Object.prototype.hasOwnProperty.call(d.components,DEF)),mitigation={resistances:[],immunities:[],vulnerabilities:[]};if(present){mitigation=parse(d.components[DEF],'stored damage-mitigation');if(!valid(mitigation))throw new Error('The stored damage-mitigation state is invalid.');}
var children=ctx.children&&ctx.children.stateEffects;if(!Array.isArray(children)||children.length!==1)throw new Error('Exactly one Condition state-effects child is required.');var child=parse(children[0].output&&children[0].output.data,'Condition state-effects child');
if(!child||typeof child!=='object'||Array.isArray(child)||child.test!=='d20-test-state-effects'||child.subjectId!==d.id||typeof child.conditionsKnown!=='boolean'||!ordered(child.effectiveConditions,CONDITIONS)||!source(child.sourceRef,CLOC))throw new Error('The Condition state-effects child is invalid for this defender.');
var petrified=child.effectiveConditions.indexOf('petrified')>=0;
return {narration:d.name+' has '+(present?'known':'unknown')+' stored damage mitigation.',data:{test:'damage-mitigation-profile',defenderId:d.id,mitigationKnown:present,conditionsKnown:child.conditionsKnown,immunities:mitigation.immunities,resistances:mitigation.resistances,vulnerabilities:mitigation.vulnerabilities,petrified:petrified,sourceRef:{sourceId:SID,locator:LOC},petrifiedSourceRef:{sourceId:SID,locator:PLOC}},effects:[],events:[],notifications:[]};
