var SID='dnd2024.source.srd-5.2.1',LOC='Rules Glossary > Speed',DEF='dnd2024.creature.movement',MODES=['walk','burrow','climb','fly','swim'],s=ctx.roles.subject,i=ctx.input;
function closed(v,keys){if(!v||typeof v!=='object'||Array.isArray(v))return false;var a=Object.keys(v);if(a.length!==keys.length)return false;for(var n=0;n<keys.length;n++)if(!Object.prototype.hasOwnProperty.call(v,keys[n]))return false;return true;}
function rational(v){return closed(v,['numerator','denominator'])&&Number.isSafeInteger(v.numerator)&&v.numerator>=0&&Number.isSafeInteger(v.denominator)&&v.denominator>0;}
function validDistance(v){return closed(v,['dimension','value','unit'])&&v.dimension==='distance'&&rational(v.value)&&closed(v.unit,['entityId'])&&v.unit.entityId==='dnd2024.vocabulary.distance-unit.meter';}
function valid(v){if(!closed(v,['speeds'])||!v.speeds||typeof v.speeds!=='object')return false;for(var n=0;n<MODES.length;n++){var id='dnd2024.vocabulary.movement-mode.'+MODES[n],entry=v.speeds[id];if(!entry||!closed(entry,['distance','enabled','sourceRefs'])||!validDistance(entry.distance)||typeof entry.enabled!=='boolean'||!Array.isArray(entry.sourceRefs)||entry.sourceRefs.length<1) return false;for(var sourceIndex=0;sourceIndex<entry.sourceRefs.length;sourceIndex++)if(!closed(entry.sourceRefs[sourceIndex],['entityId'])||entry.sourceRefs[sourceIndex].entityId!==SID)return false;}return true;}
if(!s)throw new Error('A subject role is required.');
if(!closed(i,['mode','walkFeet','burrowFeet','climbFeet','flyFeet','swimFeet']))throw new Error('Input must contain exactly mode and the five base speeds. Do not supply provenance, remaining movement, terrain, position, route, pace, or effects.');
if(i.mode!=='record'&&i.mode!=='correct')throw new Error('mode must be exactly record or correct.');
function speed(v,min){return typeof v==='number'&&isFinite(v)&&Math.floor(v)===v&&v>=min&&v<=1000&&v%5===0;}
function distance(feet){return {dimension:'distance',value:{numerator:feet*381,denominator:1250},unit:{entityId:'dnd2024.vocabulary.distance-unit.meter'}};}
var next={speeds:{}};for(var modeIndex=0;modeIndex<MODES.length;modeIndex++){var mode=MODES[modeIndex],feet=i[mode+'Feet'];if(!speed(feet,mode==='walk'?5:0))throw new Error('walkFeet must be a 5..1000 multiple of five and each special Speed must be a 0..1000 multiple of five.');next.speeds['dnd2024.vocabulary.movement-mode.'+mode]={distance:distance(feet),enabled:feet>0,sourceRefs:[{entityId:SID}]};}
if(!valid(next))throw new Error('The metric movement state is invalid.');
var raw=s.components&&s.components[DEF],previous=null;
if(raw){try{previous=typeof raw==='string'?JSON.parse(raw):raw;}catch(error){throw new Error('Existing Speed is corrupt and cannot be corrected by this rule.');}if(!valid(previous))throw new Error('Existing Speed is invalid and cannot be corrected by this rule.');}
if(i.mode==='record'&&raw)throw new Error('Speed is already recorded. Use correct to replace a valid complete profile.');
if(i.mode==='correct'&&!raw)throw new Error('Speed is absent. Use record to create the first profile.');
return {narration:s.name+'\'s Speed is '+(i.mode==='record'?'recorded.':'corrected.'),data:{mode:i.mode,walkFeet:i.walkFeet,burrowFeet:i.burrowFeet,climbFeet:i.climbFeet,flyFeet:i.flyFeet,swimFeet:i.swimFeet,previous:previous,sourceRef:{sourceId:SID,locator:LOC}},effects:[{type:i.mode==='record'?'component.add':'component.set',entityId:s.id,definitionId:DEF,data:JSON.stringify(next)}],events:[],notifications:[]};
