var C={root:'game.core.campaign.root',session:'game.core.campaign.session',recap:'game.core.campaign.session-recap',chapter:'game.core.campaign.chapter',arc:'game.core.campaign.arc',visit:'game.core.campaign.location-visit'};
function object(v){return v!==null&&!Array.isArray(v)&&typeof v==='object';}
function parse(raw,label){try{var v=JSON.parse(raw);if(!object(v))throw 0;return v;}catch(e){throw new Error(label+' is malformed.');}}
function read(e,id,label,optional){var raw=e.components&&e.components[id];if(typeof raw!=='string'){if(optional)return null;throw new Error(label+' is missing.');}return parse(raw,label);}
if(!ctx.roles||!ctx.roles.campaign||!object(ctx.input)||Object.keys(ctx.input).length)throw new Error('Recent consequences requires one campaign and empty input.');
var c=ctx.roles.campaign,root=read(c,C.root,'Campaign root',false);if(root.status!=='active')throw new Error('Campaign is not active.');
var sessions=[],chapters=[],arcs=[],visits=[],related=c.related||[];
for(var i=0;i<related.length;i++){var r=related[i];if(r.kind==='game.core.campaign.has-session'){var s=read(r,C.session,'Campaign session',false),recap=read(r,C.recap,'Session recap',true);if(s.status==='ended'){if(!recap)throw new Error('Ended session is missing its recap.');sessions.push({sessionId:r.id,ordinal:s.ordinal,chapter:recap.chapter,arc:recap.arc,milestones:recap.milestones});}}else if(r.kind==='game.core.campaign.has-chapter'){var ch=read(r,C.chapter,'Campaign chapter',false);if(ch.status==='closed')chapters.push({chapterId:r.id,title:ch.title,closingSummary:ch.closingSummary});}else if(r.kind==='game.core.campaign.has-arc'){var a=read(r,C.arc,'Campaign arc',false);if(a.status==='resolved'||a.status==='abandoned')arcs.push({arcId:r.id,status:a.status,title:a.title,closingSummary:a.closingSummary});}else if(r.kind==='game.core.campaign.has-location-visit'){var v=read(r,C.visit,'Location visit',false);visits.push({visitId:r.id,status:v.status,summary:v.summary,memory:v.memory,lastVisitedMinute:v.lastVisitedMinute,visitCount:v.visitCount});}}
sessions.sort(function(a,b){return b.ordinal-a.ordinal||a.sessionId.localeCompare(b.sessionId);});chapters.sort(function(a,b){return a.chapterId.localeCompare(b.chapterId);});arcs.sort(function(a,b){return a.arcId.localeCompare(b.arcId);});visits.sort(function(a,b){return b.lastVisitedMinute-a.lastVisitedMinute||a.visitId.localeCompare(b.visitId);});
return {narration:'Projected bounded party-visible recorded consequences.',effects:[],events:[],notifications:[],data:{version:1,campaignId:c.id,endedSessions:sessions.slice(0,5),closedChapters:chapters.slice(-5),resolvedArcs:arcs.slice(-5),locationVisits:visits.slice(0,10)}};

