var w=ctx.roles.world,l=ctx.roles.location,i=ctx.input,ROOT='game.core.campaign.root',WORLD='game.core.world.root',LOCATION='game.core.world.location',INWORLD='game.core.campaign.in-world',REF='game.core.campaign.references';
function exact(v,keys){if(!v||Array.isArray(v)||typeof v!=='object')return false;var a=Object.keys(v).sort(),b=keys.slice().sort();return JSON.stringify(a)===JSON.stringify(b);}
function text(v,max){return typeof v==='string'&&v.trim().length>0&&v.length<=max;}
function texts(v,min,max,count){return Array.isArray(v)&&v.length>=min&&v.length<=count&&v.every(function(x){return text(x,max);});}
function edge(e,from,to,kind){return (e.relationships||[]).some(function(x){return x.fromEntityId===from&&x.toEntityId===to&&(x.kind===kind||x.kind==='dnd2024.'+kind);});}
function contains(nodes,id){return (nodes||[]).some(function(x){return x.id===id||contains(x.contains,id);});}
if(!w||!l||!w.components||!l.components||!w.components[WORLD]||!l.components[LOCATION])throw new Error('Campaign creation requires one World root and one location in that World.');
if(!exact(i,['campaignId','title','premise','partyGoals','toneAndBoundaries','reviewFingerprint'])||!/^campaign\.[a-z0-9]+(?:[.-][a-z0-9]+)*$/.test(i.campaignId)||!text(i.title,160)||!text(i.premise,1000)||!texts(i.partyGoals,1,500,3)||!texts(i.toneAndBoundaries,1,300,8)||!(/^[0-9a-f]{64}$/.test(i.reviewFingerprint)))throw new Error('Campaign input must use the exact reviewed campaign creation contract.');
if(!contains(w.contains,l.id)&&!edge(l,l.id,w.id,'game.core.world.location.in-world'))throw new Error('The starting location is not linked to or contained anywhere beneath the selected World.');
var root={status:'active',title:i.title,premise:i.premise,partyGoals:i.partyGoals,toneAndBoundaries:i.toneAndBoundaries,rulesetScope:'dnd2024',creationMethod:'manual',reviewFingerprint:i.reviewFingerprint};
return {narration:i.title+' is created in '+w.name+'.',effects:[{type:'entity.create',entityId:i.campaignId,name:i.title},{type:'component.add',entityId:i.campaignId,definitionId:ROOT,data:JSON.stringify(root)},{type:'relationship.create',entityId:i.campaignId,toEntityId:w.id,kind:INWORLD,data:'{}'},{type:'relationship.create',entityId:i.campaignId,toEntityId:l.id,kind:REF,data:JSON.stringify({role:'start',audience:'party'})}],events:[],notifications:[],data:{campaignId:i.campaignId,worldId:w.id,startingLocationId:l.id,reviewFingerprint:i.reviewFingerprint}};
