var C={root:'game.core.campaign.root',scene:'game.core.campaign.current-scene',affordances:'game.core.campaign.scene-affordances',arc:'game.core.campaign.arc',chapter:'game.core.campaign.chapter',session:'game.core.campaign.session',recap:'game.core.campaign.session-recap',participation:'game.core.campaign.character-participation'};
function object(v){return v!==null&&!Array.isArray(v)&&typeof v==='object';}
function parse(raw,label){try{var v=JSON.parse(raw);if(!object(v))throw 0;return v;}catch(e){throw new Error(label+' is malformed.');}}
function component(entity,id,label,optional){var raw=entity.components&&entity.components[id];if(typeof raw!=='string'){if(optional)return null;throw new Error(label+' is missing.');}return parse(raw,label);}
function ref(v){return object(v)&&Object.keys(v).length===1&&typeof v.entityId==='string'&&v.entityId.length>0?v.entityId:null;}
function sameScene(a,b){return ref(a.location)===ref(b.location)&&ref(a.conversation||{})===ref(b.conversation||{})&&ref(a.encounter||{})===ref(b.encounter||{});}
if(!ctx.roles||!ctx.roles.campaign||!object(ctx.input)||Object.keys(ctx.input).length)throw new Error('Campaign resume requires one campaign and empty input.');
var c=ctx.roles.campaign,root=component(c,C.root,'Campaign root',false),scene=component(c,C.scene,'Current scene',true),aff=component(c,C.affordances,'Scene affordances',true),related=c.related||[];
if(root.status!=='active'||root.rulesetScope!=='dnd2024'||typeof root.title!=='string'||typeof root.premise!=='string'||!Array.isArray(root.partyGoals)||!Array.isArray(root.toneAndBoundaries))throw new Error('Campaign root is invalid.');
var arcs=[],chapters=[],sessions=[],activeMembers=0;
for(var i=0;i<related.length;i++){var r=related[i];if(r.kind==='game.core.campaign.has-arc')arcs.push({entity:r,state:component(r,C.arc,'Campaign arc',false)});else if(r.kind==='game.core.campaign.has-chapter')chapters.push({entity:r,state:component(r,C.chapter,'Campaign chapter',false)});else if(r.kind==='game.core.campaign.has-session')sessions.push({entity:r,state:component(r,C.session,'Campaign session',false),recap:component(r,C.recap,'Session recap',true)});else if(r.kind==='game.core.campaign.has-character-participation'){var p=component(r,C.participation,'Campaign participation',false);if(p.status==='active')activeMembers++;}}
var activeArcs=arcs.filter(function(v){return v.state.status==='active';}),activeChapters=chapters.filter(function(v){return v.state.status==='active';}),activeSessions=sessions.filter(function(v){return v.state.status==='active';});
if(activeArcs.length>1||activeChapters.length>1||activeSessions.length>1)throw new Error('Campaign active continuity is ambiguous.');
function arc(v){return v?{id:v.entity.id,name:v.entity.name,title:v.state.title,partyStake:v.state.partyStake}:null;}
function chapter(v){return v?{id:v.entity.id,name:v.entity.name,title:v.state.title,partyQuestion:v.state.partyQuestion}:null;}
function session(v){return v?{id:v.entity.id,name:v.entity.name,ordinal:v.state.ordinal,status:v.state.status}:null;}
var ended=sessions.filter(function(v){return v.state.status==='ended'&&v.recap;}).sort(function(a,b){return b.state.ordinal-a.state.ordinal||a.entity.id.localeCompare(b.entity.id);}),latest=ended.length?ended[0]:null;
var safeAff=[];if(scene&&aff){if(!sameScene(scene,aff.scene))throw new Error('Scene affordances are stale.');if(!Array.isArray(aff.items))throw new Error('Scene affordances are malformed.');safeAff=aff.items.filter(function(v){return v.visibility==='party';}).map(function(v){return {key:v.key,label:v.label,summary:v.summary};});}
var sceneOut=null;if(scene){var locationId=ref(scene.location);if(!locationId)throw new Error('Current scene is malformed.');sceneOut={locationId:locationId,conversationId:ref(scene.conversation||{}),encounterId:ref(scene.encounter||{})};}
var latestOut=null;if(latest){var recap=latest.recap;if(recap.protocolVersion!=='session.s0.c3-only.v1'||!object(recap.chapter)||!object(recap.arc)||!Array.isArray(recap.milestones))throw new Error('Latest session recap is malformed.');latestOut={sessionId:latest.entity.id,ordinal:latest.state.ordinal,chapter:{id:recap.chapter.id,title:recap.chapter.title,partyQuestion:recap.chapter.partyQuestion},arc:{id:recap.arc.id,title:recap.arc.title,partyStake:recap.arc.partyStake},milestones:recap.milestones.map(function(v){return {chapterId:v.chapterId,title:v.title,closingSummary:v.closingSummary,timestamp:v.timestamp,sequence:v.sequence};})};}
return {narration:'Projected the current party-visible campaign resume context.',effects:[],events:[],notifications:[],data:{version:1,campaign:{id:c.id,name:c.name,title:root.title,premise:root.premise,partyGoals:root.partyGoals,toneAndBoundaries:root.toneAndBoundaries},party:{activeMemberCount:activeMembers},scene:sceneOut,activeArc:arc(activeArcs[0]),activeChapter:chapter(activeChapters[0]),activeSession:session(activeSessions[0]),latestRecap:latestOut,affordances:safeAff}};

