var c=ctx.roles.campaign,w=ctx.roles.world,l=ctx.roles.location,v=ctx.roles.visit,ROOT='dnd2024.game.core.campaign.root',WROOT='dnd2024.game.core.world.root',CLOCK='dnd2024.game.core.world.clock',LOCATION='dnd2024.game.core.world.location',VISIT='dnd2024.game.core.campaign.location-visit',INWORLD='dnd2024.game.core.campaign.in-world',RELEVANT='dnd2024.game.core.campaign.references',HAS='dnd2024.game.core.campaign.has-location-visit',AT='dnd2024.game.core.campaign.location-visit.at-location',MAX=9007199254740991;
function object(x){return x!==null&&!Array.isArray(x)&&typeof x==='object';}
function parse(x,n){try{var y=JSON.parse(x);if(!object(y))throw 0;return y;}catch(e){throw new Error(n+' is invalid.');}}
function text(x,n){return typeof x==='string'&&x===x.trim()&&Array.from(x).length>0&&Array.from(x).length<=n;}
function edge(r,f,to,k){var local=k.slice(8);return (r.relationships||[]).some(function(e){return e.fromEntityId===f&&e.toEntityId===to&&e.kind===local&&e.data==='{}';});}
function exact(x,keys){return object(x)&&Object.keys(x).sort().join(',')===keys.slice().sort().join(',');}
if(!exact(ctx.input,['status','summary','memory','gmContext'])||['current','departed'].indexOf(ctx.input.status)<0||!text(ctx.input.summary,1000)||!text(ctx.input.memory,2000)||(ctx.input.gmContext!==null&&!text(ctx.input.gmContext,2000)))throw new Error('Visit input requires status, summary, memory, and nullable gmContext.');
var root=parse(c.components[ROOT],'Campaign'),world=parse(w.components[WROOT],'World'),clock=parse(w.components[CLOCK],'World clock'),location=parse(l.components[LOCATION],'Location');
if(root.status!=='active'||world.status!=='active'||location.status!=='active'||!Number.isSafeInteger(clock.currentMinute)||clock.currentMinute<0||clock.currentMinute>MAX)throw new Error('Campaign, World, clock, or location state is invalid.');
if(!edge(c,c.id,w.id,INWORLD)||!edge(c,c.id,l.id,RELEVANT))throw new Error('Campaign World scope or location relevance is missing.');
var visitId=c.id+'.visit.'+l.id;if(!/^[a-z][a-z0-9.-]{0,199}$/.test(visitId))throw new Error('The derived visit identity is outside the supported bound.');
var next,effects=[],priorCount=0;
if(v){var prior=parse(v.components[VISIT],'Location visit');if(v.id!==visitId||!edge(c,c.id,v.id,HAS)||!edge(v,v.id,l.id,AT))throw new Error('Existing visit ownership or location is invalid.');if(!Number.isSafeInteger(prior.firstVisitedMinute)||!Number.isSafeInteger(prior.lastVisitedMinute)||!Number.isSafeInteger(prior.visitCount)||prior.visitCount<1||prior.visitCount>=1000000||prior.lastVisitedMinute<prior.firstVisitedMinute||clock.currentMinute<prior.lastVisitedMinute)throw new Error('Existing visit state or clock order is invalid.');priorCount=prior.visitCount;next={firstVisitedMinute:prior.firstVisitedMinute,lastVisitedMinute:clock.currentMinute,visitCount:prior.visitCount+1,status:ctx.input.status,summary:ctx.input.summary,memory:ctx.input.memory};if(ctx.input.gmContext!==null)next.gmContext=ctx.input.gmContext;effects.push({type:'component.set',entityId:v.id,definitionId:VISIT,data:JSON.stringify(next)});}else{if((c.relationships||[]).some(function(e){return e.fromEntityId===c.id&&e.toEntityId===visitId&&e.kind===HAS.slice(8);} ))throw new Error('The existing visit role is required to update this location.');next={firstVisitedMinute:clock.currentMinute,lastVisitedMinute:clock.currentMinute,visitCount:1,status:ctx.input.status,summary:ctx.input.summary,memory:ctx.input.memory};if(ctx.input.gmContext!==null)next.gmContext=ctx.input.gmContext;effects.push({type:'entity.create',entityId:visitId,name:l.name+' campaign visit'},{type:'component.add',entityId:visitId,definitionId:VISIT,data:JSON.stringify(next)},{type:'relationship.create',entityId:c.id,toEntityId:visitId,kind:HAS,data:'{}'},{type:'relationship.create',entityId:visitId,toEntityId:l.id,kind:AT,data:'{}'});}
return {narration:l.name+' visit '+(priorCount?'updated.':'recorded.'),effects:effects,events:[],notifications:[],data:{test:'campaign-location-visit-record',campaignId:c.id,worldId:w.id,locationId:l.id,visitId:visitId,minute:clock.currentMinute,previousVisitCount:priorCount,visitCount:next.visitCount,status:next.status}};
