var SID="source.dnd2024.srd-5.2.1",O=["str","dex","con","int","wis","cha"],s=ctx.roles.subject,i=ctx.input;
function closed(o,n){if(!o||typeof o!=="object"||Array.isArray(o)){return false;}var k=Object.keys(o).sort(),wanted=n.slice().sort();if(k.length!==wanted.length){return false;}for(var j=0;j<wanted.length;j++){if(k[j]!==wanted[j]){return false;}}return true;}
if(!i||typeof i!=="object"||Array.isArray(i)){throw new Error("Input must be an object.");}
var k=Object.keys(i).sort();if(k.length>1||(k.length===1&&k[0]!=="rollCircumstances")){throw new Error("Input must contain only optional rollCircumstances.");}
var circumstances=[],hasAdv=false,hasDis=false,duplicates={};
if(k.length===1){if(!Array.isArray(i.rollCircumstances)){throw new Error("rollCircumstances must be an array when present.");}for(var z=0;z<i.rollCircumstances.length;z++){var c=i.rollCircumstances[z];if(!c||typeof c!=="object"||Array.isArray(c)){throw new Error("Each roll circumstance must be an object.");}var ck=Object.keys(c).sort();if(ck.length!==2||ck[0]!=="kind"||ck[1]!=="source"){throw new Error("Each roll circumstance must contain only kind and source.");}if(c.kind!=="advantage"&&c.kind!=="disadvantage"){throw new Error("roll circumstance kind must be advantage or disadvantage.");}if(typeof c.source!=="string"||c.source.length===0||c.source.trim()!==c.source){throw new Error("roll circumstance source must be a nonempty trimmed string.");}if(c.source.indexOf("condition:")===0){throw new Error("rollCircumstances source prefix condition: is reserved for derived condition state.");}var key=c.kind+"\u0000"+c.source;if(duplicates[key]){throw new Error("rollCircumstances must not repeat an exact kind and source pair.");}duplicates[key]=true;circumstances.push({kind:c.kind,source:c.source});if(c.kind==="advantage"){hasAdv=true;}else{hasDis=true;}}}
var kids=ctx.children&&ctx.children.stateEffects;if(!Array.isArray(kids)||kids.length!==1){throw new Error("Exactly one condition state-effects result is required.");}
var stateEffects;try{stateEffects=JSON.parse(kids[0].output&&kids[0].output.data?kids[0].output.data:"{}");}catch(error){throw new Error("Condition state-effects result is unreadable.");}
if(!stateEffects||typeof stateEffects!=="object"||Array.isArray(stateEffects)||stateEffects.test!=="d20-test-state-effects"||stateEffects.subjectId!==s.id||typeof stateEffects.conditionsKnown!=="boolean"||!stateEffects.byTest||typeof stateEffects.byTest!=="object"||Array.isArray(stateEffects.byTest)||!Array.isArray(stateEffects.byTest.initiative)||!Array.isArray(stateEffects.derivedModifiers)){throw new Error("Condition state-effects result has an invalid shape.");}
var derived=stateEffects.byTest.initiative;for(var d=0;d<derived.length;d++){var dc=derived[d],dk=dc&&typeof dc==="object"&&!Array.isArray(dc)?Object.keys(dc).sort():[];if(dk.length!==2||dk[0]!=="kind"||dk[1]!=="source"||(dc.kind!=="advantage"&&dc.kind!=="disadvantage")||typeof dc.source!=="string"||dc.source.indexOf("condition:")!==0){throw new Error("Condition state-effects Initiative circumstances are invalid.");}if(dc.kind==="advantage"){hasAdv=true;}else{hasDis=true;}}
var derivedModifiers=stateEffects.derivedModifiers;for(var dm=0;dm<derivedModifiers.length;dm++){var modifier=derivedModifiers[dm],mk=modifier&&typeof modifier==="object"&&!Array.isArray(modifier)?Object.keys(modifier).sort():[],levelFromModifier=modifier&&typeof modifier.value==="number"?-modifier.value/2:0;if(mk.length!==2||mk[0]!=="source"||mk[1]!=="value"||!isFinite(modifier.value)||Math.floor(modifier.value)!==modifier.value||levelFromModifier<1||levelFromModifier>6||Math.floor(levelFromModifier)!==levelFromModifier||modifier.source!=="condition:exhaustion (level "+levelFromModifier+")"){throw new Error("Condition state-effects derived modifiers are invalid.");}}
var merged=circumstances.concat(derived);
if(!s||!s.components||!s.components["dnd2024.abilities"]){throw new Error("Subject is missing dnd2024.abilities.");}
var abilities=JSON.parse(s.components["dnd2024.abilities"]);if(!closed(abilities,O)){throw new Error("Subject ability state is invalid.");}
for(var a=0;a<O.length;a++){var sc=abilities[O[a]];if(typeof sc!=="number"||!isFinite(sc)||Math.floor(sc)!==sc||sc<1||sc>30){throw new Error("Subject ability state is invalid.");}}
var score=abilities.dex,mod=Math.floor((score-10)/2),rollMode="normal";if(hasAdv&&!hasDis){rollMode="advantage";}else if(hasDis&&!hasAdv){rollMode="disadvantage";}
var rolls=[ctx.randomInt(1,20)];if(rollMode!=="normal"){rolls.push(ctx.randomInt(1,20));}var roll=rolls[0];if(rollMode==="advantage"&&rolls[1]>roll){roll=rolls[1];}if(rollMode==="disadvantage"&&rolls[1]<roll){roll=rolls[1];}
var mods=[{source:"dex "+score,value:mod}];for(var md=0;md<derivedModifiers.length;md++){mods.push(derivedModifiers[md]);}var initiative=roll;for(var mi=0;mi<mods.length;mi++){initiative+=mods[mi].value;}ctx.log("D&D 2024 Initiative ("+rollMode+"): roll "+roll+", count "+initiative+".");
return {narration:s.name+" rolls Initiative ("+rollMode+"): "+roll+" + "+mod+" = "+initiative+".",data:{test:"initiative",ability:"dex",die:"1d20",rollMode:rollMode,rolls:rolls,roll:roll,rollCircumstances:circumstances,derivedCircumstances:derived,mergedCircumstances:merged,conditionsKnown:stateEffects.conditionsKnown,modifiers:mods,initiative:initiative,source:"SRD 5.2.1 - Playing the Game: Combat > The Order of Combat > Initiative"},effects:[]};
