var t=ctx.roles.traveller,r=ctx.roles.route,w=ctx.roles.world,TRAVELLER='game.core.world.traveller',ROUTE='game.core.world.route',AVAILABLE='game.core.world.route.availability',PROFILE='dnd2024.exploration.route-profile',ROOT='game.core.world.root',CLOCK='game.core.world.clock',DURABILITY='dnd2024.object.durability';
function object(v){return v!==null&&!Array.isArray(v)&&typeof v==='object';}
function parse(raw,label){try{var v=JSON.parse(raw);if(!object(v))throw 0;return v;}catch(e){throw new Error(label+' is malformed.');}}
function ref(v){return object(v)&&Object.keys(v).length===1&&typeof v.entityId==='string'&&v.entityId.length>0;}
if(!t||!r||!w||!object(ctx.input)||Object.keys(ctx.input).length!==0)throw new Error('Travel status requires traveller, route, world, and empty input.');
var traveller=parse(t.components[TRAVELLER],'Traveller'),route=parse(r.components[ROUTE],'Route'),availability=parse(r.components[AVAILABLE],'Route availability'),profile=parse(r.components[PROFILE],'Route profile'),root=parse(w.components[ROOT],'World root'),clock=parse(w.components[CLOCK],'World clock'),durability=t.components[DURABILITY]?parse(t.components[DURABILITY],'Traveller durability'):null;
if(!ref(profile.world)||!ref(profile.origin)||!ref(profile.destination)||profile.world.entityId!==w.id||profile.origin.entityId===profile.destination.entityId||!object(profile.distance)||!Array.isArray(profile.allowedModes)||!ref(profile.terrain)||!ref(profile.visibility)||!object(profile.navigation)||!object(profile.exposure)||profile.arrivalPolicy!=='move-record-and-visit'||!Number.isSafeInteger(profile.revision)||profile.revision<1||typeof profile.fingerprint!=='string'||!/^[0-9A-F]{64}$/.test(profile.fingerprint))throw new Error('Travel status route profile is incomplete or stale.');
if(root.status!=='active'||!Number.isSafeInteger(clock.currentMinute)||clock.currentMinute<0||!Number.isSafeInteger(clock.revision)||clock.revision<0)throw new Error('Travel status world or clock is invalid.');
var active=traveller.status==='active',usable=!durability||durability.destroyed!==true,routeActive=route.status==='active'&&route.mode==='on-foot',open=availability.status==='open',atOrigin=t.containerId===profile.origin.entityId&&t.containerSlot==='presence',requirements=[{code:'traveller-active',satisfied:active},{code:'traveller-usable',satisfied:usable},{code:'route-active',satisfied:routeActive},{code:'route-open',satisfied:open},{code:'traveller-at-origin',satisfied:atOrigin}],ready=active&&usable&&routeActive&&open&&atOrigin,status=ready?'ready':!active?'traveller-inactive':!usable?'traveller-destroyed':!routeActive?'route-inactive':!open?'route-closed':'wrong-origin',missing=['input.travel.journeyId','input.travel.exposureScheduleId','input.travel.pace'];if(profile.navigation.required===true)missing.push('role.navigator','input.navigationCheck');
var exposure={enabled:profile.exposure.enabled===true};if(exposure.enabled){if(!Number.isSafeInteger(profile.exposure.cadenceMinutes)||profile.exposure.cadenceMinutes<1||!ref(profile.exposure.hazard))throw new Error('Travel exposure policy is invalid.');exposure.cadenceMinutes=profile.exposure.cadenceMinutes;}
return {narration:'Projected current route travel status for '+t.name+'.',effects:[],events:[],notifications:[],data:{version:1,traveller:{id:t.id,name:t.name,currentLocationId:t.containerSlot==='presence'?t.containerId:null,active:active,usable:usable},route:{id:r.id,name:r.name,status:route.status,availability:availability.status,summary:route.summary,revision:profile.revision,fingerprint:profile.fingerprint,worldId:profile.world.entityId,originId:profile.origin.entityId,destinationId:profile.destination.entityId,distance:profile.distance,allowedModeIds:profile.allowedModes.map(function(v){if(!ref(v))throw new Error('Travel modes are invalid.');return v.entityId;}),terrainId:profile.terrain.entityId,visibilityId:profile.visibility.entityId,navigationRequired:profile.navigation.required===true,exposure:exposure},clock:{calendarId:clock.calendarId,minute:clock.currentMinute,revision:clock.revision},status:status,requirements:requirements,nextActions:[{capabilityId:'dnd2024.mechanic.travel.execute',roles:{traveller:t.id,origin:profile.origin.entityId,destination:profile.destination.entityId,route:r.id,world:w.id},input:{travel:{mode:'walk',expectedRouteRevision:profile.revision,expectedRouteFingerprint:profile.fingerprint,expectedClockRevision:clock.revision}},missingValues:missing,ready:false}]}};
