var ids={pin:'trail-survival.scenario-pin',run:'trail-survival.run',clock:'trail-survival.clock',pending:'trail-survival.pending-choice',outcome:'trail-survival.outcome',scenario:'trail-survival.scenario',party:'trail-survival.party',resources:'trail-survival.resources',member:'trail-survival.member'};
function closed(v,k){if(v===null||Array.isArray(v)||typeof v!=='object')return false;var a=Object.keys(v).sort(),b=k.slice().sort();if(a.length!==b.length)return false;for(var i=0;i<b.length;i++)if(a[i]!==b[i])return false;return true;}
function parse(v,n){if(typeof v!=='string')throw new Error(n+' is corrupt.');try{return JSON.parse(v);}catch(e){throw new Error(n+' is corrupt.');}}
function integer(v,min,max){return typeof v==='number'&&Number.isSafeInteger(v)&&v>=min&&v<=max;}
function nodeWith(nodes,id){for(var i=0;i<(nodes||[]).length;i++)if(nodes[i].components&&nodes[i].components[id])return nodes[i];return null;}
var role=ctx.roles.run;if(!role||!role.components||!role.components[ids.pin]||!role.components[ids.run]||!role.components[ids.clock])throw new Error('Rest requires a complete run root.');if(role.components[ids.pending])throw new Error('Rest is blocked by a pending choice.');if(role.components[ids.outcome])throw new Error('Rest is blocked on a terminal run.');if(!closed(ctx.input,[]))throw new Error('Rest input must be an empty object.');
var pin=parse(role.components[ids.pin],'Scenario pin'),run=parse(role.components[ids.run],'Run'),clock=parse(role.components[ids.clock],'Clock');if(!closed(run,['partyId','phase','randomSeed','seedCursor','turn'])||run.phase!=='travel'||!integer(run.turn,0,2147483646)||!integer(run.randomSeed,1,4294967295)||!integer(run.seedCursor,0,2147483646)||!closed(clock,['elapsedMinutes'])||!integer(clock.elapsedMinutes,0,1000000000))throw new Error('Rest requires an active bounded travel run.');
var expected=((run.randomSeed>>>0)^Math.imul(run.seedCursor+1,2654435761))>>>0;if(ctx.seed!==expected)throw new Error('Rest action seed is stale or invalid.');var reference=ctx.references[pin.scenarioId];if(!reference||!reference.components||!reference.components[ids.scenario])throw new Error('Pinned scenario is unavailable.');var scenario=parse(reference.components[ids.scenario],'Scenario');if(scenario.scenarioId!==pin.scenarioId||scenario.scenarioVersion!==pin.scenarioVersion||scenario.scenarioContentHash!==pin.scenarioContentHash||scenario.rulesProfileId!==pin.rulesProfileId)throw new Error('Pinned scenario parity failed.');
if(!scenario.rest||!integer(scenario.rest.minutes,1,1000000000)||!integer(scenario.rest.foodPerMember,0,1000000000)||!integer(scenario.rest.healthGain,0,1000000)||clock.elapsedMinutes>1000000000-scenario.rest.minutes)throw new Error('Scenario rest tuning exceeds state bounds.');
var partyNode=nodeWith(role.contains,ids.party);if(!partyNode||!partyNode.components[ids.resources])throw new Error('Rest party state is unavailable.');var resources=parse(partyNode.components[ids.resources],'Resources'),members=[];for(var n=0;n<(partyNode.contains||[]).length;n++)if(partyNode.contains[n].components&&partyNode.contains[n].components[ids.member])members.push(partyNode.contains[n]);if(members.length<1)throw new Error('Rest requires party members.');
var living=[];for(var m=0;m<members.length;m++){var value=parse(members[m].components[ids.member],'Member');if(value.status!=='dead'&&value.status!=='departed')living.push({node:members[m],value:value});}if(living.length<1)throw new Error('Rest requires at least one living member.');var foodCost=scenario.rest.foodPerMember*living.length;if(!Number.isSafeInteger(foodCost)||foodCost>1000000000)throw new Error('Rest food cost exceeds the supported bound.');var nextEntries=resources.entries.map(function(v){return {resourceId:v.resourceId,quantity:v.quantity};}),food=null;for(var e=0;e<nextEntries.length;e++)if(nextEntries[e].resourceId===scenario.foodResourceId)food=nextEntries[e];if(!food||food.quantity<foodCost)throw new Error('Rest food is insufficient.');food.quantity-=foodCost;
var effects=[{type:'component.set',entityId:partyNode.id,definitionId:ids.resources,data:JSON.stringify({entries:nextEntries})}];for(var l=0;l<living.length;l++){var member=living[l].value,nextHealth=Math.min(scenario.memberMaxHealth,member.healthPoints+scenario.rest.healthGain),nextMember={name:member.name,roleId:member.roleId,status:nextHealth>0?'active':member.status,healthPoints:nextHealth,conditionIds:member.conditionIds};effects.push({type:'component.set',entityId:living[l].node.id,definitionId:ids.member,data:JSON.stringify(nextMember)});}
var nextClock={elapsedMinutes:clock.elapsedMinutes+scenario.rest.minutes},nextRun={phase:run.phase,turn:run.turn+1,partyId:run.partyId,randomSeed:run.randomSeed,seedCursor:run.seedCursor+1};effects.push({type:'component.set',entityId:role.id,definitionId:ids.clock,data:JSON.stringify(nextClock)});effects.push({type:'component.set',entityId:role.id,definitionId:ids.run,data:JSON.stringify(nextRun)});return {narration:'The party rests.',effects:effects,events:[],data:{command:'rest',foodCost:foodCost,elapsedMinutes:nextClock.elapsedMinutes,turn:nextRun.turn}};
