var ids={pin:'trail-survival.scenario-pin',run:'trail-survival.run',clock:'trail-survival.clock',pending:'trail-survival.pending-choice',outcome:'trail-survival.outcome',scenario:'trail-survival.scenario',party:'trail-survival.party',resources:'trail-survival.resources',conveyance:'trail-survival.conveyance'};
function closed(v,k){if(v===null||Array.isArray(v)||typeof v!=='object')return false;var a=Object.keys(v).sort(),b=k.slice().sort();if(a.length!==b.length)return false;for(var i=0;i<b.length;i++)if(a[i]!==b[i])return false;return true;}
function parse(v,n){if(typeof v!=='string')throw new Error(n+' is corrupt.');try{return JSON.parse(v);}catch(e){throw new Error(n+' is corrupt.');}}
function integer(v,min,max){return typeof v==='number'&&Number.isSafeInteger(v)&&v>=min&&v<=max;}
function nodeWith(nodes,id){for(var i=0;i<(nodes||[]).length;i++)if(nodes[i].components&&nodes[i].components[id])return nodes[i];return null;}
var role=ctx.roles.run;if(!role||!role.components||!role.components[ids.pin]||!role.components[ids.run]||!role.components[ids.clock])throw new Error('Forage requires a complete run root.');if(role.components[ids.pending])throw new Error('Forage is blocked by a pending choice.');if(role.components[ids.outcome])throw new Error('Forage is blocked on a terminal run.');if(!closed(ctx.input,[]))throw new Error('Forage input must be an empty object.');
var pin=parse(role.components[ids.pin],'Scenario pin'),run=parse(role.components[ids.run],'Run'),clock=parse(role.components[ids.clock],'Clock');if(!closed(run,['partyId','phase','randomSeed','seedCursor','turn'])||run.phase!=='travel'||!integer(run.turn,0,2147483646)||!integer(run.randomSeed,1,4294967295)||!integer(run.seedCursor,0,2147483646)||!closed(clock,['elapsedMinutes'])||!integer(clock.elapsedMinutes,0,1000000000))throw new Error('Forage requires an active bounded travel run.');var expected=((run.randomSeed>>>0)^Math.imul(run.seedCursor+1,2654435761))>>>0;if(ctx.seed!==expected)throw new Error('Forage action seed is stale or invalid.');
var reference=ctx.references[pin.scenarioId];if(!reference||!reference.components||!reference.components[ids.scenario])throw new Error('Pinned scenario is unavailable.');var scenario=parse(reference.components[ids.scenario],'Scenario');if(scenario.scenarioId!==pin.scenarioId||scenario.scenarioVersion!==pin.scenarioVersion||scenario.scenarioContentHash!==pin.scenarioContentHash||scenario.rulesProfileId!==pin.rulesProfileId)throw new Error('Pinned scenario parity failed.');if(!scenario.forage||!integer(scenario.forage.minutes,1,1000000000)||!integer(scenario.forage.minimumYield,0,1000000000)||!integer(scenario.forage.maximumYield,scenario.forage.minimumYield,1000000000)||clock.elapsedMinutes>1000000000-scenario.forage.minutes)throw new Error('Scenario forage tuning exceeds state bounds.');
var partyNode=nodeWith(role.contains,ids.party),conveyanceNode=partyNode&&nodeWith(partyNode.contains,ids.conveyance);if(!partyNode||!partyNode.components[ids.resources]||!conveyanceNode)throw new Error('Forage party state is unavailable.');var resources=parse(partyNode.components[ids.resources],'Resources'),conveyance=parse(conveyanceNode.components[ids.conveyance],'Conveyance'),yielded=ctx.randomInt(scenario.forage.minimumYield,scenario.forage.maximumYield),nextEntries=resources.entries.map(function(v){return {resourceId:v.resourceId,quantity:v.quantity};}),food=null;for(var e=0;e<nextEntries.length;e++)if(nextEntries[e].resourceId===scenario.foodResourceId)food=nextEntries[e];if(!food){food={resourceId:scenario.foodResourceId,quantity:0};nextEntries.push(food);}if(food.quantity>1000000000-yielded)throw new Error('Forage yield would overflow food.');food.quantity+=yielded;
var weight=0;for(var i=0;i<nextEntries.length;i++){var unit=null;for(var o=0;o<scenario.market.offers.length;o++)if(scenario.market.offers[o].resourceId===nextEntries[i].resourceId)unit=scenario.market.offers[o].unitWeight;if(unit===null)throw new Error('Scenario lacks cargo weight for a stored resource.');var part=unit*nextEntries[i].quantity;if(!Number.isSafeInteger(part)||weight>1000000000-part)throw new Error('Cargo weight exceeds the supported bound.');weight+=part;}if(weight>conveyance.cargoCapacity)throw new Error('Forage yield would exceed cargo capacity.');nextEntries.sort(function(a,b){return a.resourceId<b.resourceId?-1:a.resourceId>b.resourceId?1:0;});var nextClock={elapsedMinutes:clock.elapsedMinutes+scenario.forage.minutes},nextRun={phase:run.phase,turn:run.turn+1,partyId:run.partyId,randomSeed:run.randomSeed,seedCursor:run.seedCursor+1};return {narration:'The party forages.',effects:[{type:'component.set',entityId:partyNode.id,definitionId:ids.resources,data:JSON.stringify({entries:nextEntries})},{type:'component.set',entityId:role.id,definitionId:ids.clock,data:JSON.stringify(nextClock)},{type:'component.set',entityId:role.id,definitionId:ids.run,data:JSON.stringify(nextRun)}],events:[],data:{command:'forage',yield:yielded,elapsedMinutes:nextClock.elapsedMinutes,turn:nextRun.turn}};
