var SID="source.dnd2024.srd-5.2.1",O=["str","dex","con","int","wis","cha"],s=ctx.roles.subject,i=ctx.input;
function closed(o,n){if(!o||typeof o!=="object"||Array.isArray(o)){return false;}var k=Object.keys(o).sort(),wanted=n.slice().sort();if(k.length!==wanted.length){return false;}for(var j=0;j<wanted.length;j++){if(k[j]!==wanted[j]){return false;}}return true;}
if(!i||typeof i!=="object"||Array.isArray(i)){throw new Error("Input must be an object.");}
var k=Object.keys(i).sort();if(k.length>1||(k.length===1&&k[0]!=="rollCircumstances")){throw new Error("Input must contain only optional rollCircumstances.");}
var circumstances=[],hasAdv=false,hasDis=false,duplicates={};
if(k.length===1){if(!Array.isArray(i.rollCircumstances)){throw new Error("rollCircumstances must be an array when present.");}for(var z=0;z<i.rollCircumstances.length;z++){var c=i.rollCircumstances[z];if(!c||typeof c!=="object"||Array.isArray(c)){throw new Error("Each roll circumstance must be an object.");}var ck=Object.keys(c).sort();if(ck.length!==2||ck[0]!=="kind"||ck[1]!=="source"){throw new Error("Each roll circumstance must contain only kind and source.");}if(c.kind!=="advantage"&&c.kind!=="disadvantage"){throw new Error("roll circumstance kind must be advantage or disadvantage.");}if(typeof c.source!=="string"||c.source.length===0||c.source.trim()!==c.source){throw new Error("roll circumstance source must be a nonempty trimmed string.");}var key=c.kind+"\u0000"+c.source;if(duplicates[key]){throw new Error("rollCircumstances must not repeat an exact kind and source pair.");}duplicates[key]=true;circumstances.push({kind:c.kind,source:c.source});if(c.kind==="advantage"){hasAdv=true;}else{hasDis=true;}}}
if(!s||!s.components||!s.components["dnd2024.abilities"]){throw new Error("Subject is missing dnd2024.abilities.");}
var abilities=JSON.parse(s.components["dnd2024.abilities"]);if(!closed(abilities,O)){throw new Error("Subject ability state is invalid.");}
for(var a=0;a<O.length;a++){var sc=abilities[O[a]];if(typeof sc!=="number"||!isFinite(sc)||Math.floor(sc)!==sc||sc<1||sc>30){throw new Error("Subject ability state is invalid.");}}
var score=abilities.dex,mod=Math.floor((score-10)/2),rollMode="normal";if(hasAdv&&!hasDis){rollMode="advantage";}else if(hasDis&&!hasAdv){rollMode="disadvantage";}
var rolls=[ctx.randomInt(1,20)];if(rollMode!=="normal"){rolls.push(ctx.randomInt(1,20));}var roll=rolls[0];if(rollMode==="advantage"&&rolls[1]>roll){roll=rolls[1];}if(rollMode==="disadvantage"&&rolls[1]<roll){roll=rolls[1];}
var initiative=roll+mod,mods=[{source:"dex "+score,value:mod}];ctx.log("D&D 2024 Initiative ("+rollMode+"): roll "+roll+", count "+initiative+".");
return {narration:s.name+" rolls Initiative ("+rollMode+"): "+roll+" + "+mod+" = "+initiative+".",data:{test:"initiative",ability:"dex",die:"1d20",rollMode:rollMode,rolls:rolls,roll:roll,rollCircumstances:circumstances,modifiers:mods,initiative:initiative,source:"SRD 5.2.1 - Playing the Game: Combat > The Order of Combat > Initiative"},effects:[]};
