var s=ctx.roles.source,STATE='dnd2024.exploration.social-attitude',FACT='game.core.world.fact',HAS='social-attitude.has-record',REASON='social-attitude.reason',KIND='dnd2024.social-attitude.toward',ATTITUDES=['dnd2024.vocabulary.attitude.friendly','dnd2024.vocabulary.attitude.indifferent','dnd2024.vocabulary.attitude.hostile'];
function object(v){return v!==null&&!Array.isArray(v)&&typeof v==='object';}
function parse(raw,label){try{var v=JSON.parse(raw);if(!object(v))throw 0;return v;}catch(e){throw new Error(label+' is malformed.');}}
if(!ctx.audience||(ctx.audience.perspective!=='player'&&ctx.audience.perspective!=='dm'))throw new Error('The host-authorized social audience is unavailable.');
var dm=ctx.audience.perspective==='dm',related=s.related||[],facts={},records=[];
for(var n=0;n<related.length;n++){var item=related[n];if(item.kind===REASON&&item.fromEntityId===s.id&&typeof item.components[FACT]==='string'){var f=parse(item.components[FACT],'Social reason fact');if(f.status!=='active'||typeof f.summary!=='string'||typeof f.provenance!=='string'||['public','party','gm'].indexOf(f.visibility)<0)throw new Error('A social reason fact is invalid.');facts[item.id]=f;}}
for(var x=0;x<related.length;x++){var row=related[x];if(row.kind!==HAS||row.fromEntityId!==s.id||typeof row.components[STATE]!=='string')continue;var state=parse(row.components[STATE],'Social attitude');var attitude=state.attitude&&state.attitude.entityId,rel=state.relationship;if(!object(rel)||rel.stateSpaceId!==ctx.stateSpaceId||rel.fromEntityId!==s.id||rel.qualifiedKind!==KIND||ATTITUDES.indexOf(attitude)<0||!Array.isArray(state.reasons)||!Number.isSafeInteger(state.revision)||state.revision<1||(state.visibility!=='party'&&state.visibility!=='gm')||!state.changedByOperation||typeof state.changedByOperation.operationId!=='string')throw new Error('A social-attitude record is invalid.');if(!dm&&state.visibility==='gm')continue;var reasons=[];for(var y=0;y<state.reasons.length;y++){var id=state.reasons[y]&&state.reasons[y].entityId,fact=facts[id];if(!fact)throw new Error('A social-attitude reason is unavailable.');if(dm||fact.visibility!=='gm')reasons.push({factId:id,summary:fact.summary,provenance:fact.provenance,visibility:fact.visibility});}records.push({relationshipId:row.id,sourceActorId:s.id,targetEntityId:rel.toEntityId,attitudeId:attitude,reasons:reasons,revision:state.revision,visibility:state.visibility,changedByOperationId:state.changedByOperation.operationId,evidenceCount:Array.isArray(state.evidenceReceipts)?state.evidenceReceipts.length:0});}
records.sort(function(a,b){return a.targetEntityId.localeCompare(b.targetEntityId)||a.relationshipId.localeCompare(b.relationshipId);});
return {narration:'Projected authorized current social context.',effects:[],events:[],notifications:[],data:{version:1,sourceActorId:s.id,perspective:ctx.audience.perspective,attitudes:records}};
